### PR TITLE
Fix direction radio button losing visual state during DnD reorder

### LINKED ISSUE #20261: Aggregation builder: Direction radio button can loose value visually when changing grouping order.
## Description

Example:
direction

The option does not loose it's value and will be displayed correctly when opening the widget it again.
The bug does not occur in `5.2`

* Graylog Version: `6.0`

### PR DESCRIPTION
**Pull request by dennisoelkers**
**Note:** This needs a backport.

## How Has This Been Tested?

The DragOverlay renders a clone of the dragged item including radio inputs with the same `name` attribute. When React sets `checked=true` on the clone, the browser enforces radio group exclusivity and unchecks the original. After the drag ends, React skips re-setting `checked` because it believes the value hasn't changed, leaving the original visually unchecked.

Rendering the overlay content in a portal scopes its radio group separately, preventing interference with the original inputs.

Fixes #20261

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have requested a documentation update.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx [hunk 1]
```diff
@@ -54,20 +52,24 @@ const ListItemDragOverlay = <ItemType extends ListItemType>({
...
+          <SortableListItemOverlay
+            isDragging
+            alignItemContent={alignItemContent}
+            customContentRender={customContentRender}
+            customListItemRender={customListItemRender}
+            dragHandleProps={{}}
+            index={activeItemIndex}
+            item={activeItem}
+          />
+        </form>
```
[the remark this answers is not in the document]
Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx]: This bug is caused by specific browser handling of two inputs with the same `name` within the same `form`-element. We cannot test this within JSDom.

File: graylog2-web-interface/src/components/common/SortableList/SortableList.tsx [hunk 2]
```diff
@@ -44,6 +44,7 @@ export type Props<ItemType extends ListItemType> = {
   customContentRender?: CustomContentRender<ItemType>;
   customListItemRender?: CustomListItemRender<ItemType>;
   disableDragging?: boolean;
+  /** @deprecated The overlay is now always rendered in a portal. This prop is ignored. */
   displayOverlayInPortal?: boolean;
```
[the remark this answers is not in the document]
Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/SortableList/SortableList.tsx]: :white_check_mark:

File: graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx [hunk 3]
```diff
@@ -54,20 +52,26 @@ const ListItemDragOverlay = <ItemType extends ListItemType>({
...
       ) : null}
     </DragOverlay>
   );
 
-  return displayOverlayInPortal ? createPortal(dragOverlay, document.body) : dragOverlay;
+  // Always render the drag overlay in a portal to document.body and wrap it in an isolated
+  // <form> to prevent form input interference (e.g. radio group exclusivity) between cloned
+  // inputs in the overlay and the originals, regardless of whether the originals are inside
+  // a parent <form>.
+  return createPortal(dragOverlay, document.body);
```
Comment (linuspahl) [inline graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx]: It looks like there are cases where the styling changes on drag. I assume because the CSS selectors no longer match for the elements in the portal.

Image

Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx]: Thanks! That should be fixed now.

Comment (linuspahl) [reply graylog2-web-interface/src/components/common/SortableList/ListItemDragOverlay.tsx]: Looks way better. I noticed 
1. there are still some margins which change, between the drag handle and the `Direction` row and between the `Direction` and the `Fields` row. 
2. the `Skip Empty Values` checkbox moves from left to right.

drag example
