### PR TITLE
Delay requests for invalid session

### LINKED ISSUE #1891: Getting started guide does not show up
### Problem description

When login to Graylog for the first time the Getting-started guide does not show up. Reloading startpage shows Getting-started guide

### Steps to reproduce the problem

1. I login to Graylog after building the QA box
2. When login in I expect the Getting-started guide but page is not loading
3. After new logout/ login I am getting directed to /search instead of /getting-started
4. After page reload the Getting-started guide shows up

### Environment

* QA Setup
* `graylog-2.0.0-alpha.5-SNAPSHOT-20160302193709-graylog-server-tarball.tar.gz`
* I am using Firefox 44.0.2

### PR DESCRIPTION
**Pull request by dennisoelkers**
This PR adds a simple check during initialisation of the `SessionStore` which validates that a persisted session id is still valid. If it is not, then all requests coming in will be delayed while listening for the login event, just like in the case where no session id exists at all.

This fixes a number of problems related to stores doing initialisation only once and fail when the session id is stale.

Fixes #1891, #2059.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java [hunk 1]
```diff
@@ -120,6 +119,11 @@ public SessionResponse newSession(@Context ContainerRequestContext requestContex
         throw new NotAuthorizedException("Invalid username or password", "Basic realm=\"Graylog Server session\"");
     }
 
+    @GET
+    @ApiOperation(value = "Validate an existing session", notes = "Checks the session with the given ID: return OK if session is valid.")
```
Comment (edmundoa) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java]: Just a bit of nit-picking: the description says it will return an OK if the session is valid, but it actually responds No Content. We could change the method to return an OK or just say it returns a success code.

**Comment by edmundoa** [comment]
Other than the (tiny) remark with the REST documentation, looks good to me.

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java (hunk 1 above)
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java]: :+1: this is actually Jersey being more intelligent than me :)

**Comment by edmundoa** [comment]
LGTM :+1:
