### PR TITLE
Disable HTTP Notification submit when url field have error

### LINKED ISSUE #12272: Http notification can be saved with wrong URL
Http notification can be saved with wrong URL.

## Expected Behavior
Saving HTTP Notification should not be possible when wrong URL is used. 

## Current Behavior
Http notification can be saved with wrong URL.
If you put invalid URL in the URL field, you will see an error message, but you still can save the notification.
Screenshot 2022-03-14 at 09-08-46 Graylog - New Notification
If you put non-whitelisted URL in the URL field, you will see an error message, but you still can save the notification. 

## Possible Solution
"Create" button is disabled or clicking this button ends up with an error if wrong URL is provided.

## Steps to Reproduce (for bugs)
1. Go to Alerts - > Notifications.
2. Click "Create Notification"
3. Choose "HTTP Notification" from Notification Type selector.
4. Enter invalid URL in the URL input that appears.
5. Notice red warning under URL field.
6. Try to save and see that it is possible, despite wrong URL.

## Your Environment

* Graylog Version: Graylog 4.3.0-beta.1+a752232 (Test Day)

### PR DESCRIPTION
**Pull request by ousmaneo**
Fix #12272 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/URLWhiteListInput.tsx [hunk 1]
```diff
@@ -31,12 +31,13 @@ type Props = {
...
   validationState: string,
   url: string,
+  setIsSubmitEnabled?: (enabled: boolean) => void,
   labelClassName: string,
   wrapperClassName: string,
   urlType: React.ComponentProps<typeof URLWhiteListFormModal>['urlType'],
 };
 
-const URLWhiteListInput = ({ label, onChange, validationMessage, validationState, url, labelClassName, wrapperClassName, urlType }: Props) => {
+const URLWhiteListInput = ({ label, onChange, validationMessage, validationState, url, setIsSubmitEnabled, labelClassName, wrapperClassName, urlType }: Props) => {
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/common/URLWhiteListInput.tsx:40]: While this approach works, I think it is breaking some of the semantics of the form: A form input should not decide if the submit button is enabled or disabled. This is also problematic when we expose this as our API, which is in the end what we do when we change the interface of pluggable entities.

I think the input could call a function once the validation state changes (maybe adding an `onValidationChange` prop that consumers can provide, or adding the validation state to the `onChange` callback). From my perspective, that would make it easier to understand, since it's a similar API one uses with another form, and decoupled from a particular implementation. What do you think?

Comment (ousmaneo) [reply graylog2-web-interface/src/components/common/URLWhiteListInput.tsx:40]: Hi, thank you for your review. I agree about the semantic issue. I will change that to use `onValidationChange.`

**Review by Gaya — APPROVED** [review]
Looks great! Good suggestion @edmundoa
