### PR TITLE
Fix parameters for count query in Searches#count()

### LINKED ISSUE #3841: Error with a SEARCH_RESULT_COUNT widget
## Expected Behavior
A widget created with the "Add count to dashboard" button in a search result should work

## Current Behavior
The widget is never refreshed and /api/dashboards/id/widgets/wid/value replies with a 500 error and the following message: 
```json
{"message":"Unable to perform count query.\n\nrequest does not support [highlight]","details":["request does not support [highlight]"]}
```
No exception is logged.

## Steps to Reproduce
1. Search something
2. Create a widget on a dashboard by clicking on "Add count to dashboard" on the sidebar
3. Go to the dashboard
4. Widget should show "N/A" with a red exclamation triangle

## Context
I am using Graylog with a 2-node Elasticsearch cluster with Docker.
`/api/dashboards/id/widgets/wid` returns this for the widget:
```json
{"id":"ac51e5ec-6b9f-449b-963c-5b6715a4fa17","description":"500 errs","type":"SEARCH_RESULT_COUNT","config":{"timerange":{"type":"relative","range":3600},"lower_is_better":true,"trend":true,"query":"ctxt_response_code:>=500"},"cache_time":10,"creator_user_id":"admin"}
```

## Your Environment
* Graylog Version: 2.3.0-alpha.2+f24e575
* Elasticsearch Version: 5.4.0
* MongoDB Version: 3.4.4
* Operating System: Linux/Debian 8
* Browser version: Chrome 58

### PR DESCRIPTION
**Pull request by joschi**
The [Elasticsearch Count API](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-count.html) doesn't support "limit", "offset", and "highlight" parameters.

Older versions of Elasticsearch ignored unknown parameters but that changed in Elasticsearch 5.x: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking-changes-5.0.html

Fixes #3841

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java [hunk 1]
```diff
@@ -200,13 +200,8 @@ public CountResult count(String query, TimeRange range) {
...
     public CountResult count(String query, TimeRange range, String filter) {
-        final SearchSourceBuilder searchSourceBuilder;
-        if (filter == null) {
-            searchSourceBuilder = standardSearchRequest(query, range);
-        } else {
-            searchSourceBuilder = filteredSearchRequest(query, filter, range);
-        }
-
+        // limit, offset, and highlight are *NOT* supported by count queries
+        final SearchSourceBuilder searchSourceBuilder = standardSearchRequest(query, -1, -1, range, null, null, false);
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java]: What happens with the `filter` parameter?

**Comment by dennisoelkers** [comment]
Can you please add some tests for `count(String, TimeRange, String)` that would catch the misuse/lack of use of the `filter` parameter in a followup PR?
