### PR TITLE
Include role permissions in /roles/{rolename}/members endpoint

### LINKED ISSUE #1529: User permissions not updated on GET /roles/{rolename}/members
Hello,

Graylog 1.2.2. Steps to reproduce it:

- Add a new dashboard.
- Create a new role which allow read access

On API, call 

PUT http://xxxxxxx/roles/{role}/members/{someone}

Now call users member list

GET http://xxxxxxx/roles/{role}/members

=> someone is on the list, but he doesn't have the 

"dashboards:read:55f9ea31e4b0ed002512d90f"

In its permissions array

Now call GET http://xxxxxxx/users/{someone}

=> permission

"dashboards:read:55f9ea31e4b0ed002512d90f"

is available on its permission array.

### PR DESCRIPTION
**Pull request by bernd**
Move common code from UsersResource to UserRolesHelper.

Fixes #1529

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/users/UserRolesHelper.java [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+    private final RoleService roleService;
+    private final InMemoryRolePermissionResolver inMemoryRolePermissionResolver;
+
+    @Inject
+    public UserRolesHelper(RoleService roleService, InMemoryRolePermissionResolver inMemoryRolePermissionResolver) {
+        this.roleService = roleService;
+        this.inMemoryRolePermissionResolver = inMemoryRolePermissionResolver;
+    }
+
+    public Set<String> getRoleNames(User user) throws NotFoundException {
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/users/UserRolesHelper.java]: This method should really be placed either in `RoleService` or in `UserService` (depending on the point of view, I'd place it in `UserService`).

File: graylog2-server/src/main/java/org/graylog2/users/UserRolesHelper.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+        return ImmutableSet.copyOf(
+                Iterables.filter(
+                        Collections2.transform(roleIds, Roles.roleIdToNameFunction(idMap)),
+                        Predicates.notNull()
+                )
+        );
+    }
+
+    public List<String> getPermissionsForUser(User user) {
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/users/UserRolesHelper.java]: Same here, I'd move this class into `UserService` or `RoleService`.

File: graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java [hunk 3]
```diff
@@ -249,4 +259,39 @@ public long count() {
...
+        if (roleIds.isEmpty()) {
+            return Collections.emptySet();
+        }
+
+        Map<String, Role> idMap;
+        try {
+            idMap = roleService.loadAllIdMap();
+        } catch (NotFoundException e) {
+            LOG.error("Unable to load role ID map. Using empty map.", e);
+            idMap = new HashMap<>();
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java]: Minor nitpick: This could be `Collections.emptyMap()`

**Comment by joschi** [comment]
LGTM. :+1:
