### PR TITLE
Fix bytes formatting after numeral major update.

### LINKED ISSUE #6175: Index size display error
## Expected Behavior

When modifying the index settings for rotation, you can set the index size to trigger a rotation.

In previous versions, the index size got displayed human-friendly inside an input group on the right side of the input field as a multiplier of 1024. **Since 3.1 it seems to be 1000.**
Screenshot 2019-07-22 at 14 16 22
Screenshot 2019-07-22 at 14 16 28

## Your Environment

* Graylog Version: Graylog 3.1.0-beta.2
* Browser version: Brave Version 0.66.100 Chromium: 75.0.3770.142 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by bernd**
Numeral 2.0 changed the "b" format modifier and we now have to use "ib"
to get the Graylog 3.0 (and earlier) behavior.

Relevant changelog entry:

> Breaking change / Feature: Bytes are now formatted as: b (base 1000) and ib (base 1024)

Switch TrafficGraph.jsx to use NumberUtils instead of using numeral
directly.

Fixes #6175

### CODE REVIEW

File: graylog2-web-interface/src/components/cluster/TrafficGraph.jsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ import moment from 'moment';
 import crossfilter from 'crossfilter';
 import numeral from 'numeral';
```
Comment (mpfz0r) [inline graylog2-web-interface/src/components/cluster/TrafficGraph.jsx]: `numeral` is not used anymore

Comment (bernd) [reply graylog2-web-interface/src/components/cluster/TrafficGraph.jsx]: Good catch, thanks!
