### PR TITLE
Reloading `CurrentUserStore` when updated user is the current user.

### LINKED ISSUE #2705: Editing the current logged in user does not update the data
## Expected behaviour
When the user logged in the web interface updates their data (i.e. name), the web interface should be updated to reflect the change.

## Current behaviour
Updating the current user does not refresh the information, so the old state is kept until the page is refreshed or there is an action that fetches the user again, like clicking on the Graylog logo

## Possible solution
Update the current logged in user after editing the user information, so the information seen on the screen is accurate. Probably a call to `CurrentUserStore.reload()` should suffice.

## Steps to reproduce (for bugs)
1. Log in to Graylog
2. Click on the user name in the navigation bar, and then edit profile
3. Update your username and press "Update user"
4. The name in the navigation bar is not updated

## Your environment
* Graylog Version: 2.1.0-beta.4-SNAPSHOT (f167fb00d3cd1e512507bfb36d22934e31fe4ac7)

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Description
The `UserForm` component now triggers a reload of the `CurrentUserStore` when it is updating the user which is currently logged in.

## Motivation and Context
Before this change, the current user object was stale after updating it.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Fixes #2705.

### CODE REVIEW

File: graylog2-web-interface/src/components/users/UserForm.jsx [hunk 1]
```diff
@@ -111,6 +111,9 @@ const UserForm = React.createClass({
       if (this.isPermitted(this.state.currentUser.permissions, ['users:list'])) {
         this.props.history.replaceState(null, Routes.SYSTEM.AUTHENTICATION.USERS.LIST);
       }
+      if (this.props.user.username === this.state.currentUser.username) {
+        CurrentUserStore.reload();
+      }
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/users/UserForm.jsx]: I was wondering, shouldn't we do the same when updating permissions or roles? If so, maybe we should trigger the reload from the (ancient) `UsersStore`, or even take the time to convert it to a Reflux store. We should probably wait for that until 2.1 is out, though.

Comment (dennisoelkers) [inline graylog2-web-interface/src/components/users/UserForm.jsx]: Yes, I think we need to. I would vote for refactoring the `UsersStore` into a Reflux store. :+1:

Comment (edmundoa) [inline graylog2-web-interface/src/components/users/UserForm.jsx]: Ok, I'll create a follow up task for that 👍

**Comment by edmundoa** [comment]
LGTM 👍
