### PR TITLE
Fix group membership lookup if DN contains whitespace

### LINKED ISSUE #1790: LDAP group mapping: stringwise comparison fails due to different DN formats
LDAP group mapping is a very appreciated feature for us. Thanks for implementing it!
However, the mapping seems broken if the RDNs are separated without whitespaces in the member attribute of a group (for example "uid=12345,ou=A,o=B").

This is what the trace shows:
`TRACE: org.graylog2.security.ldap.LdapConnector - DN uid=12345, ou=A, o=B == uid=12345,ou=A,o=B member?`

In LdapConnector.findGroups, the DN of ldapEntry is compared stringswise with each member attribute of a group:
```
if (dn.equalsIgnoreCase(member.getString())) {
    groups.add(groupId);
}
```
Since org.apache.directory.api.ldap.model.name.Dn.getName() returns a string where RDNs are separated by comma _and whitespace_, the strings do not match although the DNs are semantically equal.

According to RFC 2253, whitespaces are allowed between RDNs while RFC 4514 defines the string representation without whitespaces. So maybe you could remove whitespaces from the strings before comparing them by something like `replaceAll("\\s","")` or `replaceAll(",\\s",",")`. Perhaps parsing DNs would be another solution.

PS: We are using Graylog 1.3.3

### PR DESCRIPTION
**Pull request by bernd**
Normalize the DN before comparing the strings to avoid mapping problems if the DNs have different whitespace formatting.

Fixes #1790

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java [hunk 1]
```diff
@@ -303,6 +305,32 @@ public LdapEntry search(LdapNetworkConnection connection,
...
+     */
+    private String normalizedDn(String dn) {
+        if (isNullOrEmpty(dn)) {
+            return dn;
+        } else {
+            try {
+                return new Dn(dn).getNormName();
+            } catch (LdapInvalidDnException e) {
+                LOG.warn("Invalid DN", e);
+                return dn;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: Shouldn't this be throwing an exception instead of returning the arguably invalid DN back to the caller?

File: graylog2-server/src/test/resources/org/graylog2/security/ldap/base.ldif [hunk 2]
```diff
@@ -35,6 +35,12 @@ objectClass: top
 cn: Engineers
 uniqueMember: cn=John Doe,ou=users,dc=example,dc=com
 
+dn: cn=Whitespace Engineers,ou=groups,dc=example,dc=com
```
Comment (joschi) [inline graylog2-server/src/test/resources/org/graylog2/security/ldap/base.ldif]: Whitespace Engineers – Engineering something you can't see since 1942 (also non-breaking). 😆

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java [hunk 3]
```diff
@@ -303,6 +305,32 @@ public LdapEntry search(LdapNetworkConnection connection,
...
+     *
+     *   input  = "cn=John Doe, ou=groups, ou=system"
+     *   output = "cn=John Doe,ou=groups,ou=system"
+     *
+     * See: https://github.com/Graylog2/graylog2-server/issues/1790
+     *
+     * @param dn denormalized DN string
+     * @return normalized DN string
+     */
+    private String normalizedDn(String dn) {
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: The method *could* be annotated with `@Nullable`.

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java (hunk 1 above)
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: I didn't want to change the current behavior in case of an invalid DN. If we throw an exception here, we have to handle it somewhere or let it bubble up.

Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: ✅

**Comment by joschi** [comment]
LGTM. 👍
