### PR TITLE
Fix filtering and loader on the Lookup Table pages

### LINKED ISSUE #14318: Search query on paginated tables is cleared when navigating to a different tab, but the actual table filtering isn't reset so table is empty
Not sure how to explain this exactly. For example, when on page System / Lookup Tables, inputting a search query to filter the list of lookup tables will only show search matches:

image

When navigating to a different tab (not sure what these are called?)

image

The page is updated to show the contents of that tab. Everything is working as expected at this point.

Now, if you go back to the original "tab" (again not sure what we refer to these as?) the search box is empty but the page is blank:

image

Using the reset box shows the page contents again:

image

## Expected Behavior

Paginated search box results are always reset on page navigation or changing tabs on the page.

## Current Behavior

Page is empty with no results.

## Possible Solution

Not sure if related to https://github.com/Graylog2/graylog2-server/issues/14108

## Steps to Reproduce (for bugs)

1. Navigate to System / Lookup Tables
2. Input a search term that returns 0 results
3. Click on the 'Data Adapters' "tab"
4. Click on 'Lookup Tables' "tab" to return to original page
5. observe that page is empty

## Your Environment

* Graylog Version: 5.0.1
* Java Version: 17.0.5
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu 20.04 LTS
* Browser version: Google Chrome 108.0.5359.124

### PR DESCRIPTION
**Pull request by ousmaneo**
These changes fix a couple of issues in the Lookup table sections:
- fix `loader` not dismissing if the search returns no result.
- Use `NoEntitiesExist`, `NoSearchResult` when there are no elements to display.
- Reset search when navigating to another page.
fix #14318 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.tsx [hunk 1]
```diff
@@ -168,27 +172,29 @@ const LookupTablesOverview = ({
             </OverlayTrigger>
           </SearchForm>
           <div style={{ overflowX: 'auto' }}>
```
Comment (gally47) [inline graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.tsx:174]: Thanks for working on this. Code LGTM.

Since we want to avoid `inline styles` It will be great if you can use `styled-components` here.

File: graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.tsx [hunk 2]
```diff
@@ -118,24 +122,26 @@ const DataAdaptersOverview = ({ dataAdapters, pagination, errorStates, paginatio
             </OverlayTrigger>
           </SearchForm>
           <div style={{ overflowX: 'auto' }}>
```
Comment (gally47) [inline graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.tsx:124]: same here.

File: graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx [hunk 3]
```diff
@@ -117,24 +121,26 @@ const CachesOverview = ({ caches, pagination, paginationQueryParameter }: Props)
             </OverlayTrigger>
           </SearchForm>
           <div style={{ overflowX: 'auto' }}>
```
Comment (gally47) [inline graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx:123]: and here.

**Review by gally47 — CHANGES_REQUESTED** [review]

File: graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.tsx (hunk 1 above)
Comment (ousmaneo) [reply graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.tsx]: Thank you for spotting this. I fixed it!

**Review by gally47 — APPROVED** [review]
LGTM.
