### PR TITLE
Fix a problem with a random rotation strategy order

### LINKED ISSUE #12246: Create Index Set page randomly selects rotation strategy
Every time I open the _Create Index Set_ page, the _Index Rotation Configuration_ gets randomly selected from provided 3 options. 
 
## Expected Behavior
One default strategy should be pre-selected.

## Current Behavior
Every time random strategy is selected

## Steps to Reproduce (for bugs)
1. Open the System -> Indices page
2. Click on the _Create Index Set_ button
3. Verify which rotation strategy is selected
4. Refresh the page and verify again what strategy is pre-selected now

## Your Environment

* Graylog Version: Graylog 4.3.0-SNAPSHOT+4d97241

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Fixes #12246
Rotation strategies are returned in the same order in /system/indices/rotation/strategies endpoint.
TimeBasedRotationStrategy is the first/default one if nothing is configured in graylog.conf file.
Validator for "enabled_index_rotation_strategies" will not allow to put duplicates in this property.

## Motivation and Context
Every time the Create Index Set page was opened, the Index Rotation Configuration gets randomly selected from provided 3 options. It was caused by the fact that back-end returned the strategies in random order.

## How Has This Been Tested?
   1. Open the System -> Indices page
   2. Click on the Create Index Set button
   3. Verify which rotation strategy is selected
   4. Refresh the page and verify again what strategy is pre-selected now

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java [hunk 1]
```diff
@@ -79,7 +80,7 @@ public RotationStrategies list() {
                 .stream()
                 .filter(this::isEnabledRotationStrategy)
                 .map(this::getRotationStrategyDescription)
-                .collect(Collectors.toSet());
+                .collect(Collectors.toCollection(LinkedHashSet::new));
```
Comment (todvora) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java:83]: Nice fix! Could we change the data type to List everywhere, so we signalize that the collection is ordered?

**Review by todvora — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java (hunk 1 above)
Comment (luk-kaminski) [reply graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java:83]: Yes, I can. I won't propagate this change outside of Resource/AutoValue classes, as I believe that in other places (like ElasticsearchConfiguration), it may be more important to signalize that we do not have duplicates in the collection. Does it sound ok?

**Review by todvora — APPROVED** [review]

**Review by todvora — APPROVED** [review]
Thanks, looks perfect!
