### PR TITLE
Datanode migration: fix invalid hostname

### LINKED ISSUE #19884: Datanode Migration - Validate input for hostname on Step 4
## What?

Validate hostname for migration step 4: Migration Existing data.

Specifically reject user input that is invalid and will cause the migration to fail, such as a trailing `/`

image

Bad: `http://hostname:9200/`

Good: `http://hostname:9200`

## Why?

Users may copy/paste the hostname and it may include the trailing `/`. If we know this input will fail we should prevent the user from inputting data that is not valid, or silently remove the trailing slash.

## Your Environment

* Graylog Version: 6.1.0-alpha.4

### PR DESCRIPTION
**Pull request by moesterheld**
## Description
silently removes trailing slash from hostname

/nocl

## Motivation and Context
fixes #19884 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java [hunk 1]
```diff
@@ -256,7 +256,11 @@ public boolean dataNodeStartupFinished() {
     @Override
     public void startRemoteReindex() {
         final String allowlist = getStateMachineContext().getActionArgumentOpt("allowlist", String.class).orElse(null);
-        final URI hostname = Objects.requireNonNull(URI.create(getStateMachineContext().getActionArgument("hostname", String.class)), "hostname has to be provided");
+        String host = getStateMachineContext().getActionArgument("hostname", String.class);
+        if (host.endsWith("/")) {
+            host = host.substring(0, host.length() - 1);
+        }
+        final URI hostname = Objects.requireNonNull(URI.create(host), "hostname has to be provided");
```
Comment (todvora) [inline graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java:263]: I think the order of checks is wrong here. It's too late to require a nonnull host if we use .endsWith before.

**Review by todvora — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java (hunk 1 above)
Comment (moesterheld) [reply graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java]: good point. I think `getActionArgument` will already throw a `IllegalArgumentException` if the value is missing, but I added a check for a non blank string on top.

**Review by todvora — APPROVED** [review]
LGTM, thanks!
