### PR TITLE
Use relative URLs for web interface assets served by Graylog server and backend API.

### LINKED ISSUE #10267: Graylog Enterprise Report generation failing
First of all, I appreciate all the work the Graylog Community and maintainers put into it to make it a GREAT product.

In my current setup, Graylog Cluster of 3 nodes is setup as follows:

Client -> Load balancer (443) -> Nginx (https 9000) -> Graylog (https 9001)

Client browser accesses Graylog via IP on Load Balancer as url `https://graylog.example.com/` URL. This is also the `http_external_uri`. `graylog.example.com` is not a DNS entry that server can resolve but it works on the client's machines.

Then there's `http_publish_uri` set to `https://<NodeIP>:9001/`.

All of the functionality works as expected. However after installation of the Graylog Small Business Enterprise License for the reporting feature, whenever I try to generate report through the UI, I get following error:

```
2021-03-15T17:05:29.672-04:00 ERROR [ReportRenderJob] Error during report generation: com.github.rholder.retry.RetryException: Retrying failed to complete successfully after 3 attempts. - browser logs: 
2021-03-15T17:05:29.672-04:00 ERROR [ReportRenderJob] Failed to generate report: 
com.github.rholder.retry.RetryException: Retrying failed to complete successfully after 3 attempts.
        at com.github.rholder.retry.Retryer.call(Retryer.java:174) ~[graylog.jar:?]
        at org.graylog.plugins.report.scheduler.ReportRenderJob.doRun(ReportRenderJob.java:74) [graylog-plugin-enterprise-3.3.9.jar:?]
        at org.graylog.plugins.report.scheduler.ReportRenderJob.run(ReportRenderJob.java:60) [graylog-plugin-enterprise-3.3.9.jar:?]
        at org.graylog.plugins.report.scheduler.ReportRenderSystemJob.execute(ReportRenderSystemJob.java:25) [graylog-plugin-enterprise-3.3.9.jar:?]
        at org.graylog2.system.jobs.SystemJobManager$1.run(SystemJobManager.java:89) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: org.graylog.plugins.report.rest.chromedriver.ChromeDriverException: Render engine is unable to fully generate requested report, aborting. Browser logs: 
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/vendor.8d6aa5835c8302c41e2f.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/polyfill.7b2d519528c4e87cbc34.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.0f2e4cf8cefdf620a71d.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.2148ca040de9a7a73c28.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/builtins.7b2d519528c4e87cbc34.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.2d424d9fac3bf38109fc.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/app.7b2d519528c4e87cbc34.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/config.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        [BROWSER]: [2021-03-15T17:02:29-0400] [SEVERE] https://graylog.example.com/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.0898b5f648fe40b44913.js - Failed to load resource: net::ERR_NAME_NOT_RESOLVED
        at org.graylog.plugins.report.api.ReportService.fetchPdf(ReportService.java:260) ~[?:?]
        at org.graylog.plugins.report.scheduler.ReportRenderJob.lambda$doRun$0(ReportRenderJob.java:64) ~[?:?]
        at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
        at com.github.rholder.retry.Retryer.call(Retryer.java:160) ~[graylog.jar:?]
        ... 12 more
```

According to the doc as I understood I need to adjust the `report_render_uri` which I have set to `https://<NodeIP>:9001/`. 

Now I can solve this problem by adding entry for `graylog.example.com` in `/etc/hosts` file but and I also want to know if `report_render_uri` config if its working as expected or not? Did I misconfigure anything?

Here's Nginx configuration for Graylog. Not sure if that makes a difference.

```
server {
    listen 9000 ssl;

    server_name graylog.example.com;



    root /usr/share/nginx/html;

    index index.html index.htm;

    access_log /var/log/nginx/graylog_example_com-access.log;
    error_log /var/log/nginx/graylog_example_com-error.log error;


    ssl_certificate_key /etc/nginx/tls/key.pem;
    ssl_certificate /etc/nginx/tls/cert_chain.pem;

    location / {
      proxy_read_timeout  900;
      proxy_set_header    Host $http_host;
      proxy_set_header    X-Forwarded-Host $host;
      proxy_set_header    X-Forwarded-Server $host;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass          https://127.0.0.1:9001;
    }

}
```

## Expected Behavior
Report plugin to use `report_render_uri` for report generation.

## Current Behavior
Report plugin seems to use `http_external_uri` for report generation.

## Steps to Reproduce (for bugs)
1. Install Graylog Open source.
2. Obtain Small Business License
3. Install plugin package
4. Setup reporting following the doc https://docs.graylog.org/en/3.3/pages/reporting/setup.html
5. Setup a Test report.
6. Click on `Send Report Now` to trigger generation of the particular report to be emailed after completion.

## Context
Trying to configure scheduled reports to be delivered via email.

## Your Environment
* Graylog Version: 3.3.9
* Java Version: java-1.8.0-openjdk-headless-1.8.0.282.b08-1.el7_9.x86_64
* Elasticsearch Version: 5.6.16
* MongoDB Version: 3.6.21
* Operating System: RHEL 7.9
* Browser version: Firefox 86 on Ubuntu Linux 20.04.2

### LINKED ISSUE #10632: Graylog behind a proxy and src parameter
I have Graylog behind NAT and proxy
It listens on 127.0.0.1 and requests are routed to this IP:port from public IP
It’s pretty much the same as described in https://docs.graylog.org/en/4.0/pages/configuration/web_interface.html?highlight=proxy#making-the-web-interface-work-with-load-balancers-proxies

The problem is that absolute path is used inside of index page of Graylog, like

```
<link rel="shortcut icon" href="http://127.0.0.1:9000/assets/favicon.png">
<script src="http://127.0.0.1:9000/config.js">
<script src="http://127.0.0.1:9000/assets/vendor.594b2a39cb22b445205e.js">
```
Browser obviously fails to load resources from 127.0.0.1
What’s the reason of using absolute path and how to correct it?
## Expected Behavior
Graylog web UI is accessible behind a proxy

## Current Behavior
Absolute path in the index page body blocks scripts load
## Possible Solution  
Replace links like    
`<script src="http://127.0.0.1:9000/config.js">   ` 
to    
`<script src="/config.js">    `
## Your Environment

* Graylog Version: 4.0.7
* Java Version: 1.8
* Elasticsearch Version:7.10
* MongoDB Version: 4
* Operating System: Centos 7
* Browser version: Chrome 90

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Prior to this change, all web interface assets as well as all URLs going to the backdend REST API were qualified according from the following data points, in order of precedence:

 - The `X-Graylog-Server-URL` header of the request
 - The `http_external_uri` config setting
 - The `http_publish_uri` config setting

The result of this is used as the "effective external URI".

While this helps us supporting a couple of scenarios where the Graylog server is accessed through a reverse proxy, it also produces issues when naming schemes are different internally and externally and access from both directions is desired. The only scenario which works in these cases is configuring a valid `http_publish_uri`/`http_external_uri` for internal and using the `X-Graylog-Server-URL` on the proxy for external clients.

This is related to all of these settings being absolute URLs, resulting in generating absolute URLs for the web assets as well, unnecessarily.

In all of the cases this complexity of configuration would be unnecessary, if the references to the web assets and the backend API would be relative. This would support all of the aforementioned use cases and does not rely on proper configuration of any of the settings _in order to be able to load the web assets properly_ if there is no additional path prefix.

Therefore, this PR is determining the effective external URI in the same way as listed before, but takes only the path part of it to prefix all web assets.

These are the different scenarios, the current outcome and the desired outcome:

| http_publish_uri       | http_external_uri   | X-Graylog-Server-URL            | current                        | desired |
|------------------------|---------------------|---------------------------------|----------------------------------|---------|
| http://localhost:9000/ |                     |                                 | http://localhost:9000/           | /       |
| http://localhost:9000/ | https://graylog/foo |                                 | http://graylog/foo/              | /foo/   |
| http://localhost:9000/ | https://graylog/foo | https://something-else:8000/bar | https://something-else:8000/bar/ | /bar/   |

This helps us simplifying the http configuration for most scenarios while yielding a more reliable result when accessed internally as well as externally.

Fixes #10632.
Fixes #10267.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by kmerz — COMMENTED** [review]
Code LGTM and the concept sounds solid. :+1: 
Need more time for testing though.

File: graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java [hunk 1]
```diff
@@ -72,11 +73,14 @@ private ProductionIndexHtmlGenerator(final String template,
 
     @Override
     public String get(MultivaluedMap<String, String> headers) {
+        final URI externalUri = RestTools.buildExternalUri(headers, httpConfiguration.getHttpExternalUri());
+        final String path = externalUri.getPath() + (externalUri.getPath().endsWith("/") ? "" : "/");
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java:77]: `RestTools#buildExternalUri` already ensures a trailing `/` at the end of the URI. So think we can remove the check here.

**Review by bernd — CHANGES_REQUESTED** [review]
Thanks for the PR! I like the idea of using relative URLs! :+1: 

Can you please check all usages of `RestTools#buildExternalUri`? It is used in other places like `AppConfigResource`, `DevelopmentIndexHtmlGenerator` and the documentation browser resources. I think we should return relative URLs there as well.

We can probably create a new method in `RestTools` that can be used in the different places.

**Comment by dennisoelkers** [comment]
@bernd: Thanks for the great feedback!

> Can you please check all usages of RestTools#buildExternalUri? It is used in other places like AppConfigResource, DevelopmentIndexHtmlGenerator and the documentation browser resources. I think we should return relative URLs there as well.

> We can probably create a new method in RestTools that can be used in the different places.

I had already prepared a follow-up branch for this, using a relative URL for the backend (see 61b7fcf814a9ae79d99160ba20776b16fa5459e5) which is introducing a method like that. I just wanted to check first if the general idea is reasonable. What would you suggest on how to proceed? Integrate the two PRs? Or merge this one first and following up with the second afterwards?

**Comment by bernd** [comment]
> @bernd: Thanks for the great feedback!
> 
> > Can you please check all usages of RestTools#buildExternalUri? It is used in other places like AppConfigResource, DevelopmentIndexHtmlGenerator and the documentation browser resources. I think we should return relative URLs there as well.
> 
> > We can probably create a new method in RestTools that can be used in the different places.
> 
> I had already prepared a follow-up branch for this, using a relative URL for the backend (see [61b7fcf](https://github.com/Graylog2/graylog2-server/commit/61b7fcf814a9ae79d99160ba20776b16fa5459e5)) which is introducing a method like that. I just wanted to check first if the general idea is reasonable. What would you suggest on how to proceed? Integrate the two PRs? Or merge this one first and following up with the second afterwards?

@dennisoelkers Oh sorry, I didn't notice the other branch. I think we can just do that in this PR. :slightly_smiling_face:

File: graylog2-server/src/main/java/org/graylog2/rest/RestTools.java [hunk 2]
```diff
@@ -120,6 +120,11 @@ public static URI buildExternalUri(@NotNull MultivaluedMap<String, String> httpH
         return uri;
     }
 
+    public static URI buildRelativeExternalUri(@NotNull MultivaluedMap<String, String> httpHeaders, @NotNull URI defaultUri) {
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/rest/RestTools.java:123]: Can we use this method for the following resources as well?

- DevelopmentIndexHtmlGenerator
- DocumentationResource
- DocumentationBrowserResource

**Review by bernd — CHANGES_REQUESTED** [review]
One comment, apart from that it works fine! :+1:

**Review by bernd — APPROVED** [review]
Thanks for addressing the comments! :+1:
