### PR TITLE
Use english locale explicitly when finding widget subclass.

### LINKED ISSUE #11596: Unknown Widget: aggregation error on different computers
I can create and view dashboards on my computer but any other team member can't view dashboards or create new one. We try same admin user on all computers but they all get errors about "Unknown Widget: aggregation" in the dashboard widgets.

## Expected Behavior

It should work on other computers as well

## Current Behavior

Ekran görüntüsü 2021-11-08 10-56-03

## Steps to Reproduce (for bugs)

1. Use Turkish Windows and open "Sources Dashboard" in chrome. It will not work with Widget error. Change Chrome Language to English and restart Chrome, same dashboard works now.
2. Use and English locale Linux distribution. Open "Sources Dashboard" in Chrome (default english language), it will work. Then close all chrome windows and open a linux terminal. execute command "export LANGUAGE=tr_TR", then execute command "google-chrome" from the same terminal window. Chrome will open in Trukish language. Open Graylog "Sources Dashboard" and it wont work with wdiget error.

## Your Environment

* Graylog Version: 4.2.1
* Java Version: OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb11u1)
* Elasticsearch Version: 7.10.2
* MongoDB Version: 5.0.3
* Operating System: Debian 11
* Browser version: Chrome 95.0.4638.69

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

**Note:** This requires a backport to `4.2`.

Prior to this PR we were using the default locales when converting widget types to lower case. For the turkish language, this can lead to certain characters being changed in an unexpected way.

This PR is now using the `en` locale explicitly when lowercasing the widget type.

Thanks to @supahgreg for his work in #11601.

Fixes #11596.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/views/logic/widgets/Widget.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ class Widget {
       streams,
     } = this._value;
 
-    return { id, type: type.toLocaleLowerCase(), config, filter, timerange, query, streams };
+    return { id, type: type.toLowerCase(), config, filter, timerange, query, streams };
```
Comment (supahgreg) [inline graylog2-web-interface/src/views/logic/widgets/Widget.ts:111]: Oh yeah, that's much better.  Went ahead and updated #11601, just in case.

**Review by linuspahl — COMMENTED** [review]
Looks good to me, fixes the described problem!

**Review by linuspahl — APPROVED** [review]
