### PR TITLE
Restore `ClipboardButton` to work in non-secure contexts.

### LINKED ISSUE #19643: Copy functionality (Copy message, copy id, copy token, copy scratchpad) does not work over http but does work over https
Copy functionality (Copy message, copy id, copy token, copy scratchpad) does not work over http but does work over https.

This appears to have been introduced starting with graylog 6.0.

See also https://github.com/Graylog2/graylog2-server/issues/18788

## Expected Behavior

Copy buttons provided in the UX copy text (at the very least show an error to let the user know the copy failed)

## Current Behavior

Copy buttons do not work when accessing a graylog node via http

## Possible Solution

@a-zombie (Rick) theorizes this is a result of the copy function only working via HTTPS: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility

## Steps to Reproduce (for bugs)

Access graylog via http

## Your Environment

* Graylog Version: 6.0.3
* Browser version: Version 125.0.6422.142 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by dennisoelkers**
**Note:** This needs a backport to `6.0`.

## Motivation and Context

This PR is restoring `ClipboardButton`'s functionality to work in non-secure context. In a previous refactoring (#17472), the component was made to use `CopyButton` from Mantine, which works only in secure contexts (+ `localhost`), unfortunately. This PR is now restoring it by removing the usage of Mantine's `CopyButton` and implements an own component for this, which uses our own `copyToClipboard` abstraction, which falls back to a legacy approach in non-secure contexts.

Fixes #19643.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/ClipboardButton.tsx [hunk 1]
```diff
@@ -14,12 +14,15 @@
  * along with this program. If not, see
  * <http://www.mongodb.com/licensing/server-side-public-license>.
  */
-import React from 'react';
-import { CopyButton, Tooltip } from '@mantine/core';
+import * as React from 'react';
+import { useCallback, useState } from 'react';
+import { Tooltip } from '@mantine/core';
```
Comment (linuspahl) [inline graylog2-web-interface/src/components/common/ClipboardButton.tsx:19]: Let's use our abstraction from `common/Tooltip` here.

**Review by linuspahl — APPROVED** [review]
