### PR TITLE
Provide a timeout for request when optimizing index in ES7.

### LINKED ISSUE #10054: All OptimizeIndexJob are timing out after 1m (instead of 1h)
## Environment & Context

* Graylog Version: 4.0.2
* Elasticsearch Version: 7.10.2 (OSS), recently upgraded from 6 (DEB packages)
* Operating System: Ubuntu Server 20.04

## The problem

Shortly after upgrading GL from 4.0.1 to 4.0.2 and **ES from 6 to 7.10.2 (OSS)**, all new OptimizeIndexJob are failing with the following error in the logs (timeout after 60 seconds).

```
2021-02-12T11:44:40.808+01:00 ERROR [SystemJobManager] Unhandled error while running SystemJob <07c50bec-6d1f-11eb-b130-005056afb272> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:134) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:97) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:90) ~[?:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.optimizeIndex(IndicesAdapterES7.java:394) ~[?:?]
        at org.graylog2.indexer.indices.Indices.optimizeIndex(Indices.java:326) ~[graylog.jar:?]
        at org.graylog2.indexer.indices.jobs.OptimizeIndexJob.execute(OptimizeIndexJob.java:71) ~[graylog.jar:?]
        at org.graylog2.system.jobs.SystemJobManager$1.run(SystemJobManager.java:89) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:241) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.net.SocketTimeoutException: 60,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:834) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:259) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.IndicesClient.forcemerge(IndicesClient.java:897) ~[?:?]
        at org.graylog.storage.elasticsearch7.IndicesAdapterES7.lambda$optimizeIndex$22(IndicesAdapterES7.java:394) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:95) ~[?:?]
        ... 13 more
Caused by: java.net.SocketTimeoutException: 60,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
        at org.graylog.shaded.elasticsearch7.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[?:?]
        at org.graylog.shaded.elasticsearch7.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[?:?]
        ... 1 more
```
Reading in the docs and the forums, I was under the impression that timeout for these optimize jobs is controlled via the `elasticsearch_index_optimization_timeout`, which is set to 1 hour (and not 60 seconds).

Here is an excerpt of my server.conf setup :
```
$ cat /etc/graylog/server/server.conf | grep elasticsearch_index_optimization_timeout
elasticsearch_index_optimization_timeout = 1h
```
I have also doubled `elasticsearch_socket_timeout` and `elasticsearch_request_timeout` from 1m to 2m, but the timeouts did not disappear and the OptimizeIndexJob are still failing after 120 seconds. 

Any ideas ?

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

**Note:** This PR requires a backport to `4.0`.

Prior to this change, the force merge request which is used during the index optimization job did not supply a timeout for ES7. This leads to the default timeout (60s) being used, which is too short in most cases.

While this might not result in the force merge request being cancelled ([details](https://github.com/Graylog2/graylog2-server/issues/10054#issuecomment-778460239)), it leads to unnecessarily logging of misleading errors.

This PR is supplying the configured timeout to the request.

Fixes #10054.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java [hunk 1]
```diff
@@ -146,4 +148,14 @@ private boolean isInvalidWriteTargetException(ElasticsearchException elasticsear
     private boolean isIndexNotFoundException(ElasticsearchException e) {
         return e.getMessage().contains("index_not_found_exception");
     }
+
+    public static RequestOptions withTimeout(RequestOptions requestOptions, Duration timeout) {
+        final RequestConfig requestConfigWithTimeout = RequestConfig.copy(requestOptions.getRequestConfig())
+                .setSocketTimeout(Math.toIntExact(timeout.toMilliseconds()))
```
Comment (bernd) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java:154]: How about using `Ints.saturatedCast(long)` here to avoid an exception if the timeout overflows an int?

**Review by bernd — CHANGES_REQUESTED** [review]

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java (hunk 1 above)
Comment (dennisoelkers) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java:154]: I am not sure. This would mean that we would be silently doing something else than requested. Alternatively we could validate the config setting to not be higher than 24 days (~`Integer.MAX_VALUE / (24*60*60*1000)`)?

Comment (bernd) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java:154]: Sounds good. :+1: I guess we can also choose a lower maximum. I doubt that someone wants to have such a high timeout. :smile:

Comment (dennisoelkers) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java:154]: That is true, but I am too uncreative right now to come up with something different, so I just picked 24 days :)

**Review by bernd — APPROVED** [review]
