### PR TITLE
Hide Pagination in PaginatedList when context is not interactive

### LINKED ISSUE #7210: Message list pagination is not working in dashboard full screen mode
The message list pagination is not working, when a dashboard is in full screen mode.
Clicking on a page results in an empty list.

## Possible Solution
Disabling the pagination is in my opinion the best solution. Mainly because no widget is interactive in the full screen mode.

## Steps to Reproduce (for bugs)
1. Create a dashboard
2. Create a message list widget (which displays pagination for the current search)
3. Save the dashboard
4. Start the full screen mode, by clicking on Actions -> Full Screen
5. Use the message list pagination

## Your Environment
* Graylog Version: 3.2.0-beta.4-SNAPSHOT

### PR DESCRIPTION
**Pull request by linuspahl**
As described in #7210, the MessageList pagination does not work in the dashboard full screen mode. This PR hides the pagination inside the PaginatedList, when the `InteractiveContext` defines the context as not interactive. We can safely add this to the shared component because the context is by default interactive.

I would prefer to disable the pagination, but the bootstrap component does not support this functionality and we would have to implement all the styles and logic on our own.

Fixes #7210

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/PaginatedList.jsx [hunk 1]
```diff
@@ -114,23 +115,29 @@ class PaginatedList extends React.Component<Props, State> {
...
-                      maxButtons={10}
-                      activePage={currentPage}
-                      onSelect={this._onChangePage}
-                      prev
-                      next
-                      first
-                      last />
-        </div>
-      </>
+      <InteractiveContext.Consumer>
```
Comment (kmerz) [inline graylog2-web-interface/src/components/common/PaginatedList.jsx]: @dennisoelkers has made a shortcut for that. `<IfInteractive>` 

Take a look here: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/views/components/widgets/Widget.jsx#L291
