### PR TITLE
No sorting on latest aggregation

### LINKED ISSUE #12908: Sorting ascending/descending for `latest(metric)` not working for all metrics
## Expected Behavior
Metrics that can not be sorted should not be shown in the selection on widget creation/editing.

## Current Behavior
All metrics can be selected for latest(), for some the following error occurs:
```
Search type returned error: Invalid aggregation order path [4c2a0c57-7977-44ae-a9a4-b68daa58b238-series-latest(DiskFree)]. Buckets can only be sorted on a sub-aggregator path that is built out of zero or more single-bucket aggregations within the path and a final single-bucket or a metrics aggregation at the path end.
```

## Context

see ticket 942721902

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Fixes #12908 by removing "latest" metrics from the list of possible sorts.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.tsx [hunk 1]
```diff
@@ -61,6 +61,7 @@ const Sort = React.memo(({ index }: Props) => {
   const hasGroupings = otherSorts.find((s) => s.type === 'groupBy');
 
   const metricsOptions: Array<OptionValue> = hasGroupings ? [] : metrics.map(formatSeries)
+    .filter((metric) => !(metric.label.startsWith('latest(')))
```
Comment (linuspahl) [inline graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.tsx:64]: Let's filter `metrics` before formatting them with `formatSeries`. It is a little bit cleaner, because each object still has an id, the `function` attribute.

Comment (linuspahl) [inline graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.tsx:64]: Let's filter `metrics` before formatting them with `formatSeries`. It is a little bit cleaner, because each object still has an id, the `function` attribute.

**Review by linuspahl — APPROVED** [review]
