### PR TITLE
fix(mcp): NPE in ListStreamsTool when stream description is null

### LINKED ISSUE #25214: MCP(ListStreamsTool): NPE when a stream has Null description
## Expected Behavior

The `list_streams` MCP tool should return all streams successfully, even when a stream has a `null` description.

Image

## Current Behavior

When any stream has no description (i.e., `description` is `null`), the `list_streams` tool call fails with `"Tool call failed: null"`.

Image

## Possible Solution

Use `Optional` to handle the nullable `description` field, e.g., `Optional.ofNullable(stream.getDescription()).orElse("")`.

Other nullable fields in the same `Map.of()` call (like `creator_user_id`) should also be audited for the same issue.

## Steps to Reproduce (for bugs)

1. Connect to a Graylog instance via MCP (e.g., using the MCP Inspector with Streamable HTTP transport).
2. Create a stream without a description.
3. Call the `list_streams` tool.
4. Observe error: `"Tool call failed: null"`.

## Context

`StreamDTO.description()` is annotated `@Nullable`, and `StreamImpl.description()` is also `@Nullable`. However, `ListStreamsTool.apply()` passes the result of `stream.getDescription()` directly into `Map.of()` on line 67, which throws a `NullPointerException` on null values. This makes the entire tool call fail if even a single stream has no description.

**Relevant code:**
- `graylog2-server/src/main/java/org/graylog/mcp/tools/ListStreamsTool.java:67`
- `graylog2-server/src/main/java/org/graylog2/streams/StreamImpl.java`

## Your Environment

* Graylog Version: 7.0.5+854 (preview.graylog.cloud)
* Java Version: 21
* OpenSearch Version: N/A (cloud environment)
* MongoDB Version: N/A (cloud environment)
* Operating System: macOS 26.3
* Browser version: Chrome 145.0.0.0

## Checklist

- [x] This issue fix need to be backported.
- [ ] Does this issue have **security** implications?

### PR DESCRIPTION
**Pull request by monrax**
## Description
Handle nullable `description` field in `ListStreamsTool.apply()`. `StreamDTO.description()` and `StreamImpl.description()` are both annotated `@Nullable`, but the value was passed directly into `Map.of()` which throws `NullPointerException` on null values. Wrapped with `Optional.ofNullable(...).orElse("")` to safely default to an empty string.

## Motivation and Context
When any stream has no description, the `list_streams` MCP tool call fails with `"Tool call failed: null"`, making the entire tool unusable if even a single stream lacks a description.

Fixes #25214

## How Has This Been Tested?
Manual testing: created a stream without a description and verified the `list_streams` MCP tool returns all streams successfully.

## Screenshots (if appropriate):
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have requested a documentation update.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/mcp/tools/ListStreamsTool.java [hunk 1]
```diff
@@ -64,7 +65,7 @@ public String apply(PermissionHelper permissionHelper, ListStreamsTool.Parameter
                             .map(stream -> Map.of(
                                     "id", stream.getId(),
                                     "title", stream.getTitle(),
-                                    "description", stream.getDescription(),
+                                    "description", Optional.ofNullable(stream.getDescription()).orElse(""),
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog/mcp/tools/ListStreamsTool.java]: You can use `Objects.requireNonNullElse(stream.getDescription(), "")` to avoid the `Optional` object creation.

**Review by bernd — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog/mcp/tools/ListStreamsTool.java (hunk 1 above)
Comment (monrax) [reply graylog2-server/src/main/java/org/graylog/mcp/tools/ListStreamsTool.java]: thanks for the feedback! I just changed it. Please take a look when you can

**Review by bernd — APPROVED** [review]
