### PR TITLE
Only display a single ContentPackEntity modal at once

### LINKED ISSUE #15015: Content pack entity modals displaying all at once
When inspecting a single entity in a content pack with the `Show` action all entity modals pop up on top of each other. 

## Expected Behavior

When inspecting a single entity in a content pack only the selected entity's modal pops up.

## Current Behavior

When inspecting a single entity in a content pack all entities' modals pop up on top of each other.

## Steps to Reproduce (for bugs)

1. Go to Open Threat Exchange content pack 
2. Select `Show` on the first lookup adapter entity
3. Notice the background is much darker than it should be and the visible modal is not about the lookup adapter

Expected (from version 5.0): 
image

Current (from latest master branch build):
image

## Your Environment

* Graylog Version: latest master

### PR DESCRIPTION
**Pull request by kingzacko1**
## Motivation and Context

fixes #15015 
/nocl since this does not affect any released versions
## How Has This Been Tested?

local dev env
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx [hunk 1]
```diff
@@ -139,14 +140,14 @@ class ContentPackEntitiesList extends React.Component {
...
 
-    const openShowModal = () => {
-      this.setState({ showConfigModal: true });
+    const openShowModal = (entityId) => {
+      this.setState({ showConfigModal: true, showConfigModalId: entityId });
     };
 
-    const showModal = (
+    const showModal = entity.id === this.state.showConfigModalId ? (
       <BootstrapModalWrapper showModal={this.state.showConfigModal}
```
Comment (simonychuang) [inline graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx:151]: Here we can just do `showModal={!!this.state.showConfigModalId}` which will be true when it has a value and be false when it is undefined

**Review by simonychuang — APPROVED** [review]
Looks good and works, just added a nitpick for potential removal of one state variable

**Review by simonychuang — APPROVED** [review]
LGTM
