### PR TITLE
Set option ignore_unavailable for querying

### LINKED ISSUE #18127: Race condition during index delete
HS-2287071296

Race condition during index deletion may cause errors in event queries.

## Expected Behavior

I should be able to delete an index via the Graylog API without triggering any errors due to race conditions.

## Current Behavior

There is a brief lag between deleting an index in OS and in MongoDB. 
Event query execution may thus include the index, even though it is already deleted in OS.

## Possible Solution

- Flip the order of events: first delete the index in Mongo, then in OS. This may run into problems, if another thread decides to rebuild the meta-data.
- use `ignore_unavailable` option. We usually do this, so we should do it here too.

## Steps to Reproduce (for bugs)

Repro is tricky, since it is a short timing window. But if indices are regularly deleted, and event queries are using those indices at the same time, you will eventually see an OS exception `index_not_found_exception, reason=no_such_index`

## Your Environment

* Graylog Version: 5.2.2

### PR DESCRIPTION
**Pull request by patrickmann**
Resolves #18127 

## Description

When issuing a simple search query we now set option `ignoreUnavailable=true` and `allowNoIndices=true`. This serves to suppress the exception in case of missing indices, but otherwise leaves behavior unaltered.

In the case of scroll requests we also catch and handle the exception raised by empty results.

## Motivation and Context

Avoid exceptions when there is a race between querying and deleting an index. See linked issue for details.

### CODE REVIEW

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java [hunk 1]
```diff
@@ -141,7 +140,13 @@ public void scrollEvents(String queryString, TimeRange timeRange, Set<String> af
                              List<UsedSearchFilter> filters, int batchSize, ScrollEventsCallback resultCallback) throws EventProcessorException {
         final ChunkCommand chunkCommand = buildScrollCommand(queryString, timeRange, affectedIndices, filters, streams, batchSize);
 
-        final ChunkedResult chunkedResult = multiChunkResultRetriever.retrieveChunkedResult(chunkCommand);
+        final ChunkedResult chunkedResult;
+        try {
+            chunkedResult = multiChunkResultRetriever.retrieveChunkedResult(chunkCommand);
+        } catch (IllegalArgumentException e) {
+            LOG.warn("Ignoring invalid scroll request", e);
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:147]: Could you please explain why we catch the exception here and don't propagate it further?

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java [hunk 2]
```diff
@@ -255,7 +254,7 @@ public QueryResult doRun(SearchJob job, Query query, ESGeneratedQueryContext que
                     return new SearchRequest()
                             .source(searchTypeQueries.get(searchTypeId))
                             .indices(indices.toArray(new String[0]))
-                            .indicesOptions(IndicesOptions.fromOptions(false, false, true, false));
+                            .indicesOptions(IndicesOptions.fromOptions(true, true, true, false));
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java:257]: allowNoIndices is now set to true. Is this by purpose? Does it help with the issue which is solved by this PR?

**Review by todvora — COMMENTED** [review]
Just two details - the added catch without propagation and the allowNoIndices option introduced together with the ignoreUnavailable.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java (hunk 1 above)
Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:148]: Added comment in code.
This is intended to allow aggregation or correlation event queries to complete, in the presence of unavailable indices. This was another issue uncovered in unit testing.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java [hunk 3]
```diff
@@ -62,7 +61,7 @@
 
 public class MoreSearchAdapterES7 implements MoreSearchAdapter {
     private static final Logger LOG = LoggerFactory.getLogger(MoreSearchAdapterES7.class);
-    public static final IndicesOptions INDICES_OPTIONS = IndicesOptions.fromOptions(false, false, true, false);
+    public static final IndicesOptions INDICES_OPTIONS = IndicesOptions.fromOptions(true, true, true, false);
```
Comment (luk-kaminski) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:64]: Could you replace it with `IndicesOptions.LENIENT_EXPAND_OPEN` which is already present in other places, so that we have the same method of options creation?

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java (hunk 2 above)
Comment (luk-kaminski) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java:257]: The same as here: https://github.com/Graylog2/graylog2-server/pull/18146/files#r1479887434

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java [hunk 4]
```diff
@@ -115,7 +114,7 @@ public Map<DateTime, Map<String, Long>> fieldHistogram(String fieldName, Set<Str
     @Override
     public long count(Set<String> indices, Optional<Set<String>> includedStreams) {
         final CountRequest request = new CountRequest(indices.toArray(new String[0]), buildStreamIdFilter(includedStreams))
-                .indicesOptions(IndicesOptions.fromOptions(true, false, true, false));
+                .indicesOptions(IndicesOptions.fromOptions(true, true, true, false));
```
Comment (luk-kaminski) [inline graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java:117]: The same as here: https://github.com/Graylog2/graylog2-server/pull/18146/files#r1479887434

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java [hunk 5]
```diff
@@ -62,7 +61,7 @@
 
 public class MoreSearchAdapterOS2 implements MoreSearchAdapter {
     private static final Logger LOG = LoggerFactory.getLogger(MoreSearchAdapterOS2.class);
-    public static final IndicesOptions INDICES_OPTIONS = IndicesOptions.fromOptions(false, false, true, false);
+    public static final IndicesOptions INDICES_OPTIONS = IndicesOptions.fromOptions(true, true, true, false);
```
Comment (luk-kaminski) [inline graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java:64]: The same as here: https://github.com/Graylog2/graylog2-server/pull/18146/files#r1479887434

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java [hunk 6]
```diff
@@ -257,7 +257,7 @@ public QueryResult doRun(SearchJob job, Query query, OSGeneratedQueryContext que
                     return new SearchRequest()
                             .source(searchTypeQueries.get(searchTypeId))
                             .indices(indices.toArray(new String[0]))
-                            .indicesOptions(IndicesOptions.fromOptions(false, false, true, false));
+                            .indicesOptions(IndicesOptions.fromOptions(true, true, true, false));
```
Comment (luk-kaminski) [inline graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java:260]: The same as here: https://github.com/Graylog2/graylog2-server/pull/18146/files#r1479887434

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java (hunk 1 above)
Comment (luk-kaminski) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:148]: @patrickmann - I'm sorry if I am saying stupid things, but I do not understand this one.
`MultiChunkResultRetriever` has 4 possible implementations, and you have added options to all 4 of them. 
Why is it still throwing exceptions and requires to handle them manually?

Comment (luk-kaminski) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:148]: It seems that scroll search, when executed on unavailable indices, would not return response with `_scroll_id` field.
Because of that construction will fail on this line:
https://github.com/Graylog2/graylog2-server/blob/813203263b06dda18e2aed68ae92b34277f904b4/graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ScrollResultOS2.java#L48

Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:148]: @luk-kaminski 
You are right - when scroll searching, the exception is thrown from the constructor you mention; not because of a missing `ignoreUnavailable` option. 
Is there a more elegant way of handling that? I was hesitant to make changes to scroll result processing.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java (hunk 3 above)
Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java:64]: I started doing this and realized that we actually use `fromOptions` a lot more than the constant values.
The constants are more declarative, but it's not obvious whether `allowNoIndices` is true or false. Also, it's more obvious what is being changed by this PR, if we stick with the booleans.

Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java]: OK - replaced with `LENIENT_EXPAND_OPEN` or `LENIENT_EXPAND_OPEN_CLOSED` wherever possible.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java (hunk 2 above)
Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java]: done

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java (hunk 4 above)
Comment (patrickmann) [reply graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java]: done

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java (hunk 5 above)
Comment (patrickmann) [reply graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java]: done

File: graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java (hunk 6 above)
Comment (patrickmann) [reply graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java]: done

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ScrollResultES7.java [hunk 7]
```diff
@@ -46,13 +44,16 @@ public ScrollResultES7(ElasticsearchClient client,
...
-        checkArgument(initialResult.getScrollId() != null, "Unable to extract scroll id from supplied search result!");
         this.scroll = scroll;
 
     }
 
     @Override
     protected SearchResponse nextSearchResult() throws IOException {
+        if (this.lastSearchResponse.getScrollId() == null) {
+            //with ignore_unavailable=true and no available indices, response does not contain scrollId
+            return null;
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ScrollResultES7.java:57]: Agreed that it would be cleaner to not return null. But the code that processes the returned value is based on working with null. So are all the tests. We'd have to refactor a bunch more in order to support `Optional`. 
I went ahead and annotated as `Nullable`.
https://github.com/Graylog2/graylog2-server/blob/f04fe4e6dd01f55fcb6ca06d49a05c798109498a/graylog2-server/src/main/java/org/graylog2/indexer/results/ChunkedQueryResult.java#L67-L77

**Review by todvora — APPROVED** [review]
LGTM!
