### PR TITLE
Fix retrying indexing when connection failed to elastic search 7

### LINKED ISSUE #11045: ES Bulk index attempts are not retried
Writing Messages to elastic with `Messages#bulkIndexRequest()` used to retry
indefinitely if the ES server is not reachable.

For ES7 this is not the case anymore. 
Exceptions are thrown directly after the first attempt:
`Caught exception during bulk indexing: ElasticsearchException{message=ElasticsearchException[An error occurred: ]; nested: ConnectException[Connection refused]; nested: ConnectException[Connection refused];, errorDetails=[]}, retrying (attempt #1).`

## Possible Solution
The ES7 client seems to wrap the connection errors within a `ElasticsearchException`  (not to be confused with `org.graylog2.indexer.ElasticsearchException`!

That simple diff works for me:
```
--- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
+++ graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
@@ -76,7 +76,7 @@ public class Messages {
     @SuppressWarnings("UnstableApiUsage")
     private RetryerBuilder<List<IndexingError>> createBulkRequestRetryerBuilder() {
         return RetryerBuilder.<List<IndexingError>>newBuilder()
-                .retryIfException(t -> t instanceof IOException || t instanceof InvalidWriteTargetException)
+                .retryIfException(t -> t instanceof IOException || t instanceof InvalidWriteTargetException || t.getCause().getCause() instanceof IOException)
                 .withWaitStrategy(WaitStrategies.exponentialWait(MAX_WAIT_TIME.getQuantity(), MAX_WAIT_TIME.getUnit()))
                 .withRetryListener(new RetryListener() {
                     @Override

```

## Steps to Reproduce (for bugs)

1. Turn off ES
2. Look at the server.log

## Your Environment

* Graylog Version: 4.2-snap

* Elasticsearch Version: 7.10.2

### PR DESCRIPTION
**Pull request by kmerz**
## Motivation
Prior to this change, the creation of an bulk request retryer failed
with an exception if the connection to elasitc search 7 could not be
established. Since the Exection was wrapped in a new elastsic search
execption.

## Description
This change will check if the error which causes the retryer to be
executed is an IOException and  will not raise a new execption, but
instead retries in configured time.

## How Has This Been Tested?
- Switch off elastic search
- check the error messages 

Fixes #11045

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Backport
Needs backport to 4.1

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java [hunk 1]
```diff
@@ -78,7 +78,7 @@
     @SuppressWarnings("UnstableApiUsage")
     private RetryerBuilder<List<IndexingError>> createBulkRequestRetryerBuilder() {
         return RetryerBuilder.<List<IndexingError>>newBuilder()
-                .retryIfException(t -> t instanceof IOException || t instanceof InvalidWriteTargetException)
+                .retryIfException(t -> t instanceof IOException || t instanceof InvalidWriteTargetException || t.getCause().getCause() instanceof IOException)
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java:81]: Since `t.getCause()` can return `null`, I think we should use `ExceptionUtils.getRootCause()` to make sure we don't throw a `NullPointerException`. The `IOException` also might be deeper than two levels.

```diff
--- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
+++ graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
@@ -53,6 +53,8 @@ import java.util.concurrent.LinkedBlockingQueue;
 import java.util.concurrent.TimeUnit;
 import java.util.stream.Collectors;
 
+import static org.graylog2.shared.utilities.ExceptionUtils.getRootCause;
+
 @Singleton
 public class Messages {
     public interface IndexingListener {
@@ -78,7 +80,7 @@ public class Messages {
     @SuppressWarnings("UnstableApiUsage")
     private RetryerBuilder<List<IndexingError>> createBulkRequestRetryerBuilder() {
         return RetryerBuilder.<List<IndexingError>>newBuilder()
-                .retryIfException(t -> t instanceof IOException || t instanceof InvalidWriteTargetException)
+                .retryIfException(t -> t instanceof IOException || getRootCause(t) instanceof IOException || t instanceof InvalidWriteTargetException)
                 .withWaitStrategy(WaitStrategies.exponentialWait(MAX_WAIT_TIME.getQuantity(), MAX_WAIT_TIME.getUnit()))
                 .withRetryListener(new RetryListener() {
                     @Override
```

**Review by bernd — CHANGES_REQUESTED** [review]
Thank you! One small request:

**Review by bernd — APPROVED** [review]

**Comment by bernd** [comment]
@kmerz I am restarting the build before merging it.
