### PR TITLE
Fix zstd library loading issue on noexec-mounted /tmp directories

### LINKED ISSUE #17837: Server no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Just upgraded Graylog Server to version 5.1.10 via the official repository. The systemd service successfully started and the java process is running, but doesn't fully start up. 
After some waiting, the web interface does become functional. No further error messages.

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system. [in thread "main"]
```

I have zstd-jni installed on this system, and the shared objects are present:
```
/lib/x86_64-linux-gnu/libzstd-jni.so
/lib/x86_64-linux-gnu/libzstd.so.1.5.4
/lib/x86_64-linux-gnu/libzstd-jni.so.1
/lib/x86_64-linux-gnu/libzstd.a
/lib/x86_64-linux-gnu/libzstd.so.1
/lib/x86_64-linux-gnu/libzstd-jni.so.1.5.2-5
/lib/x86_64-linux-gnu/libzstd.so
```

Here is the full output starting the graylog server in foreground:
```
2024-01-03 22:44:11,699 main ERROR An exception occurred processing Appender graylog-internal-logs org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.logUsedFeatureFlags(ImmutableFeatureFlagsCollector.java:81)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.toMap(ImmutableFeatureFlagsCollector.java:66)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:38)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:26)
        at org.graylog2.bootstrap.CmdLineTool.getFeatureFlags(CmdLineTool.java:420)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:269)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:259)
        at org.graylog2.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.luben.zstd.util.Native.load(Native.java:105)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 26 more

2024-01-03 22:44:12,255 main ERROR An exception occurred processing Appender graylog-internal-logs org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.bootstrap.CmdLineTool.loadPlugins(CmdLineTool.java:432)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:285)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:259)
        at org.graylog2.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 22 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system. [in thread "main"]
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.luben.zstd.util.Native.load(Native.java:105)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.logUsedFeatureFlags(ImmutableFeatureFlagsCollector.java:81)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.toMap(ImmutableFeatureFlagsCollector.java:66)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:38)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:26)
        at org.graylog2.bootstrap.CmdLineTool.getFeatureFlags(CmdLineTool.java:420)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:269)
        ... 2 more

2024-01-03 22:44:12,259 main ERROR An exception occurred processing Appender graylog-internal-logs org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.bootstrap.CmdLineTool.loadPlugins(CmdLineTool.java:432)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:285)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:259)
        at org.graylog2.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 22 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system. [in thread "main"]
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.luben.zstd.util.Native.load(Native.java:105)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.logUsedFeatureFlags(ImmutableFeatureFlagsCollector.java:81)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.toMap(ImmutableFeatureFlagsCollector.java:66)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:38)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:26)
        at org.graylog2.bootstrap.CmdLineTool.getFeatureFlags(CmdLineTool.java:420)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:269)
        ... 2 more

2024-01-03 22:44:12,262 main ERROR An exception occurred processing Appender graylog-internal-logs org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.bootstrap.CmdLineTool.loadPlugins(CmdLineTool.java:432)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:285)
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:259)
        at org.graylog2.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdOutputStream
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        ... 22 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni3561088310999350548.so: /tmp/libzstd-jni3561088310999350548.so: failed to map segment from shared object
no zstd-jni in java.library.path: /usr/share/graylog-server/lib/sigar
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system. [in thread "main"]
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.luben.zstd.util.Native.load(Native.java:105)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.setUpCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:91)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.writeIntoCompressedStream(MemoryLimitedCompressingFifoRingBuffer.java:84)
        at org.graylog2.log4j.MemoryLimitedCompressingFifoRingBuffer.add(MemoryLimitedCompressingFifoRingBuffer.java:79)
        at org.graylog2.log4j.MemoryAppender.append(MemoryAppender.java:83)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2034)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1899)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:184)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.logUsedFeatureFlags(ImmutableFeatureFlagsCollector.java:81)
        at org.graylog2.featureflag.ImmutableFeatureFlagsCollector.toMap(ImmutableFeatureFlagsCollector.java:66)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:38)
        at org.graylog2.featureflag.FeatureFlagsFactory.createImmutableFeatureFlags(FeatureFlagsFactory.java:26)
        at org.graylog2.bootstrap.CmdLineTool.getFeatureFlags(CmdLineTool.java:420)
        at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:269)
        ... 2 more
```

## Your Environment

* Graylog Version: 5.1.10
* Java Version: 17.0.9
* OpenSearch Version: 2.11.1
* MongoDB Version: 6.0.12
* Operating System: Debian 12 (6.1.0-13-amd64 Debian 6.1.55-1 (2023-09-29) x86_64)

### PR DESCRIPTION
**Pull request by bernd**
Set the "ZstdTempFolder" system property early in the startup process.

Fixes #17837

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java [hunk 1]
```diff
@@ -272,11 +271,23 @@ public void run() {
...
+
+        // Move the zstd temp folder from /tmp to our native lib dir to avoid issues with noexec-mounted /tmp directories.
+        // See: https://github.com/Graylog2/graylog2-server/issues/17837
+        // WARNING: This needs to be set before the first use of the zstd library. Our in-memory logger is using
+        //          zstd library, so we need to set it before the first usage of the Logger instance.
+        //          Setting it after the first library usage wouldn't have any effect.
+        if (Native.isLoaded()) {
+            LOG.warn("The zstd library is already loaded. Setting the ZstdTempFolder property doesn't have any effect!");
+        }
+        System.setProperty("ZstdTempFolder", pluginLoaderConfig.getNativeLibDir().toAbsolutePath().toString());
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java:284]: I think `data/libnative` will usually not exist yet on a new setup. For the first server start, zstd-jni will fail to extract its libraries. When the server is restarted, our netty libs will be present in that directory so that it exists.

File: graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java [hunk 2]
```diff
@@ -335,8 +346,8 @@ public void doRun(Level logLevel) {
         startCommand();
     }
 
-    protected PluginLoader getPluginLoader(File pluginDir, ChainingClassLoader classLoader) {
-        return new PluginLoader(pluginDir, classLoader);
+    protected PluginLoader getPluginLoader(PluginLoaderConfig pluginLoaderConfig, ChainingClassLoader classLoader) {
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java:349]: Changing the signature will break other `CmdLineTool`s like the Forwarder. I think we should keep the original method and add a second method with the new signature.

**Review by thll — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java (hunk 2 above)
Comment (bernd) [reply graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java:365]: Good catch, thank you! I restored the old method.

File: graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java (hunk 1 above)
Comment (bernd) [reply graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java]: Good catch, thank you! I adjusted the code to create the native lib dir.

**Review by thll — APPROVED** [review]
nice! thank you!
