### PR TITLE
Install a Graylog index template instead of set mappings on index creation

### LINKED ISSUE #1624: ES dynamic template functionality is broken in Graylog 1.3
Hello, 

Since Graylog 1.3, the use of clever dynamic template to specify values type and doc_values is not possible anymore. Since you create the index with your own index template, you prevent anyone to specify any special mapping with a dynamic template. 
Here is the mapping we have now with graylog 1.3

```
{
  "graylog2_321" : {
    "mappings" : {
      "message" : {
        "dynamic_templates" : [ {
          "internal_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "doc_values" : true
            },
            "match" : "gl2_*"
          }
        }, {
          "store_generic" : {
            "mapping" : {
              "index" : "not_analyzed"
            },
            "match" : "*"
          }
        },  {
          "num_suffix" : {
            "mapping" : {
              "type" : "double",
              "doc_values" : true
            },
            "match" : "*_num"
          }
        }, {
          "others" : {
            "mapping" : {
              "index" : "not_analyzed",
              "type" : "string",
              "doc_values" : true
            },
            "match" : "*"
          }
...
"properties" : {
          "thread" : {
            "type" : "long"
          },
...
```
"thread" should here a string, but it is now a long.  Note that also doc_values can not be specified anymore for non analyzed fields.
This is a problem since it was useful to prevent collisions to happen by enforcing conventions with ES.
I have also seen the dynamic_templates features as a solution proposed in some issues. I changed the order of the template but it doesn't help. It is working perfectly fine in 1.2 since the dynamic template mapping of Graylog is applied after the dynamic template present in ES.

### PR DESCRIPTION
**Pull request by bernd**
In commit edf0d8b we changed the index creation process from "create index" + "install index mapping" to one operation to avoid race conditions.

This broke setups where users had installed custom Elasticsearch index templates because the user templates where applied after our mapping was installed into the index. Before edf0d8b the user templates have been applied before we installed our mapping because the index creation was split into two steps.

We now install a "graylog-internal" index template into Elasticsearch with a "order" or -99 to make sure user templates are able to override our settings.

Fixes #1624

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java [hunk 1]
```diff
@@ -211,6 +214,26 @@ public String aliasTarget(String alias) {
         return response.getAliases().isEmpty() ? null : response.getAliases().keysIt().next();
     }
 
+    public boolean createIndexTemplate() {
+        final Map<String, Object> template = indexMapping.messageTemplate(allIndicesAlias(), configuration.getAnalyzer());
+        final PutIndexTemplateRequest itr = c.admin().indices().preparePutTemplate(GRAYLOG_INTERNAL_TEMPLATE_NAME)
+                .setOrder(-99) // Make sure templates with "order: 0" are applied after our template!
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: Why -99 and not -1 or `Integer.MIN_VALUE`?

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java [hunk 2]
```diff
@@ -99,6 +100,8 @@
 
     private static final Logger LOG = LoggerFactory.getLogger(Indices.class);
 
+    private static final String GRAYLOG_INTERNAL_TEMPLATE_NAME = "graylog-internal";
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: Why "internal"? Is there another Graylog index template?

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java [hunk 3]
```diff
@@ -211,6 +214,26 @@ public String aliasTarget(String alias) {
         return response.getAliases().isEmpty() ? null : response.getAliases().keysIt().next();
     }
 
+    public boolean createIndexTemplate() {
+        final Map<String, Object> template = indexMapping.messageTemplate(allIndicesAlias(), configuration.getAnalyzer());
+        final PutIndexTemplateRequest itr = c.admin().indices().preparePutTemplate(GRAYLOG_INTERNAL_TEMPLATE_NAME)
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: Could this cause problems if the template already exists and/or has been modified?

Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: It will just overwrite any changes with our configured values, which is what we want I guess.

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java (hunk 1 above)
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: I chose -99 because I didn't want to use -1 because we might need some space in the future. :wink: 

I will change it to `Integer.MIN_VALUE`.

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java (hunk 2 above)
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: I used that name to make it clear that this is our Graylog internal mapping and because users might have a template named "graylog" already.

**Comment by bernd** [comment]
Updated after some discussions.

File: graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java (hunk 2 above)
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java]: :white_check_mark: Fair enough.

**Comment by joschi** [comment]
LGTM. :+1:

**Comment by joschi** [comment]
Merged into `master` in be54753ed5979af44c53ac05748619be58e231aa.
