### PR TITLE
Do not display login form while loading

### LINKED ISSUE #2770: Search Query Flashes Login Prompt Briefly
After upgrading to Graylog 2.1.0, all search queries flashes the login prompt briefly as it reloads the screen with the results.

We are using Graylog on an input server and a web frontend server set as slave and serving only the web interface using Apache proxy to HTTPS. I verified that even with no Apache proxy, the behavior is the same.

## Steps to Reproduce (for bugs)
Click on the magnifying glass or type in parameter to perform the search

## Your Environment
* Graylog Version: 2.1.0
* Elasticsearch Version: 2.0.5
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version: Chrome 52 / IE 11.0

### PR DESCRIPTION
**Pull request by edmundoa**
When loading Graylog, we currently display the login form while waiting for some resources to load, namely:
- Validate user session
- Load the current logged-in user

Those resources sometimes take a bit to load, and seeing the login form is confusing, as seen in #2770. This PR introduces a loading page that will avoid the confusion of seeing the login form on the screen.

I decided to use the same design used in our login page, as this provides a good transition between the loading and log-in page, which may be show directly before and/or after each other.

Fixes #2770.

### CODE REVIEW

File: graylog2-web-interface/src/pages/LoadingPage.jsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+  },
+
+  componentWillUnmount() {
+    disconnectedStyle.unuse();
+    authStyle.unuse();
+  },
+
+  render() {
+    return (
+      <div>
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/LoadingPage.jsx]: Minor nitpick, do we need this `div`?

**Comment by dennisoelkers** [comment]
Tested it in different scenarios, LGTM. I also like the way it improves logging in/full page refreshes a lot. Good work @edmundoa!

File: graylog2-web-interface/src/pages/LoadingPage.jsx (hunk 1 above)
Comment (edmundoa) [inline graylog2-web-interface/src/pages/LoadingPage.jsx]: I don't think so, must be a leftover from some test. Will take a look 👍
