### PR TITLE
Fix Accept header for non-json endpoints in swagger ui

### LINKED ISSUE #723: API browser error for load balancer status
Trying the `/system/lbstatus` results in an 406 error because of a wrong content type in the request.

g2-api-browser-error

`text/plain` is needed, not `application/json`.

### PR DESCRIPTION
**Pull request by bernd**
Fixes #723

### CODE REVIEW

File: graylog2-server/src/main/resources/swagger/lib/swagger.js [hunk 1]
```diff
@@ -1004,10 +1004,15 @@
       }
       responseContentType = null;
       if (this.type === "POST" || this.type === "GET" || this.type === "PATCH") {
+        responseContentType = "application/json";
```
Comment (joschi) [inline graylog2-server/src/main/resources/swagger/lib/swagger.js]: Couldn't this be pulled into line 1005? The else branch overwrites it with `null` anyway, so this could simply be the initial value of `responseContentType`.

Comment (bernd) [inline graylog2-server/src/main/resources/swagger/lib/swagger.js]: I removed the else branch instead.

**Comment by joschi** [comment]
LGTM.
