### PR TITLE
Fix search results `0` when first item in resultset does not contain a `total`

### LINKED ISSUE #18675: Search results count can be 0 when adding events widget.
## Description

The total result count in the top right corner of the search page can be 0 after adding an events overview widget.

this does not seems to be the case every time when adding a widget.

* Graylog Version: beta for 6.0

### PR DESCRIPTION
**Pull request by janheise**
## Description

fixes #18675 

/nocl

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/views/components/views/ExecutionInfo.tsx [hunk 1]
```diff
@@ -24,12 +24,13 @@ import { Timestamp } from 'components/common';
 
 const ExecutionInfo = () => {
   const result = useAppSelector(selectCurrentQueryResults);
-  const total = result?.searchTypes && Object.values(result?.searchTypes)?.[0]?.total;
 
   if (isEmpty(result)) {
     return <i>No query executed yet.</i>;
   }
 
+  const total = result?.searchTypes && Object.values(result?.searchTypes)?.find((e) => e.total)?.total;
```
Comment (maxiadlovskii) [inline graylog2-web-interface/src/views/components/views/ExecutionInfo.tsx:32]: Since now we have at least 2 widgets where total value doesn't relate to search results, I think would be nice to have some kind of filtration by widget type, and only then try to pick the total value.


```
const SEARCH_TYPES = ['pivot', 'messages', 'logs']
const total = result?.searchTypes && Object.values(result?.searchTypes)?.find((e) => e.total && SEARCH_TYPES.includes(e.type))?.total;
```

**Review by maxiadlovskii — CHANGES_REQUESTED** [review]

**Review by dennisoelkers — APPROVED** [review]

File: graylog2-web-interface/src/views/components/views/ExecutionInfo.tsx (hunk 1 above)
Comment (dennisoelkers) [reply graylog2-web-interface/src/views/components/views/ExecutionInfo.tsx:32]: I think Jan's approach is fine. We should couple it to the result structure instead of the search type's type, otherwise we would have to extend it every time we add a new search type which provides a total count.
