### PR TITLE
Saved searches can be sorted by 3 additional fields

### LINKED ISSUE #14140: Sort for paginated saved searches API endpoint not working as expected.
## Description

When defining a sort when fetching the paginated saved searches the resulting list does not have the expected sort.
It looks like it only works with 'created_at' but not 'title', 'description', 'summary' and 'owner'.

## Your Environment

* Graylog Version: 5.0

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Saved searches can be sorted by 3 additional fields: owner, description and summary.
Proper indexes prepared in Mongo DB for sortable fields.
Fixes #14140.

## Motivation and Context
See #14140.

## How Has This Been Tested?
Manually and with additional integration test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java [hunk 1]
```diff
@@ -62,6 +63,11 @@ protected ViewService(MongoConnection mongoConnection,
         this.viewRequirementsFactory = viewRequirementsFactory;
         this.entityOwnerShipService = entityOwnerShipService;
         this.viewSummaryService = viewSummaryService;
+        for (String sortField : ViewDTO.SORT_FIELDS) {
```
Comment (todvora) [inline graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java:66]: Would it make sense to run this code inside a migration, only once?

**Review by todvora — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java (hunk 1 above)
Comment (luk-kaminski) [reply graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java:66]: Hmm, I feel it should be run on every start-up.
If the index is there, Mongo won't duplicate it, so there is nothing to worry about.
If it is not there (i.e. smb has dropped it), we recreate it.

Comment (todvora) [reply graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java:66]: I checked again and we are doing the same in other services. Let's keep it as it is. Thanks!

**Review by todvora — APPROVED** [review]
