### PR TITLE
Fix dashboard layouts when width or height is 0

### LINKED ISSUE #3765: Dashboard layout broken when dashboard is created from content pack
## Expected Behaviour
Layout of dashboards created from content packs looks fine, even if the widget had no `width` and `height` information.

## Current Behaviour
Layout of dashboards created from content packs is broken when widget does not include `width` and/or `height` information.

## Steps to Reproduce (for bugs)
1. Import and apply a content pack including a dashboard, like: https://github.com/Graylog2/omnibus-graylog2/blob/294decadc40183f47e738b0c9c70df93aedaaac9/files/data/contentpacks/content_pack_appliance.json
2. Go to the dashboard created from the content pack and see that the layout is broken

## Your Environment
* Graylog Version: Graylog 2.3.0-alpha.1

### PR DESCRIPTION
**Pull request by edmundoa**
Dashboards created from content packs always get a value for each widget dimensions, being 0 the default. This behaviour is different than what happens when a widget is created manually and is now taken into account.

Fixes #3765

### CODE REVIEW

File: graylog2-web-interface/src/pages/ShowDashboardPage.jsx [hunk 1]
```diff
@@ -131,8 +134,8 @@ const ShowDashboardPage = React.createClass({
       positions[widget.id] = {
         col: (persistedDimensions.col === undefined ? defaultDimensions.col : persistedDimensions.col),
         row: (persistedDimensions.row === undefined ? defaultDimensions.row : persistedDimensions.row),
-        height: (persistedDimensions.height === undefined ? defaultDimensions.height : persistedDimensions.height),
-        width: (persistedDimensions.width === undefined ? defaultDimensions.width : persistedDimensions.width),
+        height: (this._validDimension(persistedDimensions.height) ? persistedDimensions.height : defaultDimensions.height),
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Minor nitpick: why not just use `persistedDimensions.height || defaultDimensions.height`? It is shorter, saves a function call and makes the intention even clearer.

File: graylog2-web-interface/src/pages/ShowDashboardPage.jsx [hunk 2]
```diff
@@ -131,8 +134,8 @@ const ShowDashboardPage = React.createClass({
...
+        width: (this._validDimension(persistedDimensions.width) ? persistedDimensions.width : defaultDimensions.width),
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Same here.

File: graylog2-web-interface/src/pages/ShowDashboardPage.jsx (hunk 1 above)
Comment (edmundoa) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: For me this is by far more explicit, as I'm calling a function just to say this may have a different value than just `undefined`.

Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Using `||` would do far more than just checking for `undefined`, it also checks for `null` and `0`, so it is doing exactly the same.

Comment (edmundoa) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Yes, but it does not make the intention clearer. We use this shortcut all over the place when we can't be bother to look if it's `undefined` or `null`. Using `||` also checks for `false` and probably two or three other things. In this way I'm clearly stating that this value can be `0` even if it doesn't look like it.

**Comment by bernd** [comment]
@dennisoelkers @edmundoa Can we move on with this? The discussion seems to be around a minor nitpick, not a real issue.

File: graylog2-web-interface/src/pages/ShowDashboardPage.jsx [hunk 3]
```diff
@@ -119,6 +119,9 @@ const ShowDashboardPage = React.createClass({
   _dashboardIsEmpty(dashboard) {
     return dashboard.widgets.length === 0;
   },
+  _validDimension(dimension) {
+    return dimension !== null && dimension !== undefined && dimension !== 0;
```
Comment (joschi) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Shouldn't this be as follows (using [`Number.isInteger()`](https://www.w3schools.com/jsref/jsref_isinteger.asp)):
```javascript
return Number.isInteger(dimension) && dimension > 0;
```

Comment (edmundoa) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: The problem is that `Number.isInteger()` is not implemented in IE. I'll check if the polyfill we use supports it.

Comment (edmundoa) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: It works fine, so I changed the function 👍
