### PR TITLE
Fix "Stats are disabled by default" color on IndexSet page

### LINKED ISSUE #16899: "Stats are disabled by default" not visible
With https://github.com/Graylog2/graylog2-server/pull/15155 implemented it's noted that the "Stats are disabled by default" text is invisible when stats are disabled:
image

This is also noted on the per-index text too:

image

The text is visible when stats are enabled:
image

* Graylog Version: Graylog Cloud 5.2.0 (402), Graylog Cloud 5.2.0 (406), Graylog 5.2.0-beta.1+7c9f2bf

### PR DESCRIPTION
**Pull request by ousmaneo**
These changes fix the issue of "Stats are disabled by default" not being visible because of the text color.

fix #16899
/nocl

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx [hunk 1]
```diff
@@ -35,6 +35,37 @@ import useSendTelemetry from 'logic/telemetry/useSendTelemetry';
 import useLocation from 'routing/useLocation';
 import { TELEMETRY_EVENT_TYPE } from 'logic/telemetry/Constants';
 
+const Toolbar = styled(Row)(({ theme }) => css`
+  border-bottom: 1px solid ${theme.colors.gray[90]};
+  padding-bottom: 15px;
```
Comment (gally47) [inline graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx:40]: is it possible to replace the value with theme spacing?

File: graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx [hunk 2]
```diff
@@ -35,6 +35,37 @@ import useSendTelemetry from 'logic/telemetry/useSendTelemetry';
...
+`);
+
+const GlobalStatsCol = styled(Col)`
+  display: flex;
+  align-items: center;
+  gap: 10px;
```
Comment (gally47) [inline graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx:46]: here too?

**Review by gally47 — APPROVED** [review]
Tested it LGTM. (theme spacing nitpick not a blocker though)
