### PR TITLE
Check periodically if running ES is compatible with initial ES version.

### LINKED ISSUE #9246: Upgrade to ES 7.x from 6.8 requires reboot in order for Graylog search to work
## Expected Behavior
Upgrade to ES 7.x from 6.8 should not require a reboot of the Graylog Servers for Search to work properly

## Current Behavior
Upgraded Graylog to 4.0, upgraded ES to 7.x, and got an error on the search page of a boolean type incompatibility in both the Message Count and All Messages Boxes.  Restarted the service and then began getting stream permission issues on the search screen even though stream permissions had not changed and user had rights to all streams.  Rebooted all Graylog servers in cluster, and everything worked upon the servers coming back up.

## Steps to Reproduce (for bugs)
1. Upgrade GL 3.3.x to 4.0
2. Upgrade ES 6.8 to 7.x
3. Issue will be apparent on the search screen after the upgrade

## Context
This issue would require unnecessary down time of the servers and could lead to an increase in support cases do to how catastrophic the failures appear to be even though the fix is a simple reboot

## Your Environment
This occurred in both Aaron's environment and the SE dev environment in AWS

* Graylog Version: 4.0
* Java Version: 8
* Elasticsearch Version: 7.7 and 7.9
* MongoDB Version:4.0 and 4.2
* Operating System: Ubuntu
* Browser version: Chrome Latest

### LINKED ISSUE #9259: Periodically check if detected ES version is the same major version than current ES version
## What?

Graylog is currently probing ES nodes once during startup to find out the current ES version.
Graylog should periodically do this and compare major versions. If the currently running major version is not matching the one detected during startup, it should raise a notification.

## Why?

As a Graylog admin, I would like to get a heads up if the current ES version is not matching the one which was detected during startup, as this could indicate malfunctions.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Starting with 4.x, the ES version is probed during startup and the code corresponding to the major version is bound. If ES is upgraded to a different major version while Graylog is running, the ES code bound might not be compatible to the ES version running. This can result in indexing/search errors.

To inform users about this condition, this PR is adding a periodical running every 30 seconds, which probes for the current ES version and compares it against the one probed initially during startup. If both are incompatible, a system notification is raised. If they are compatible, it is fixed. If either the version is overridden manually or no version can be probed, no change is performed (although an error is logged in the latter case).

An initial idea was to start the periodical with a delay of 30 seconds, but this would lead to the notification persisting after restarting Graylog, which might irritate users. Therefore the periodical is started immediately, resulting in a (mostly) unneeded first probe.

Fixes #9259.
Fixes #9246.

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+    }
+
+    @Override
+    public boolean startOnThisNode() {
+        return true;
+    }
+
+    @Override
+    public boolean isDaemon() {
+        return false;
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java:78]: I think this can run in the daemon thread pool. What do you think?

File: graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+
+        final Optional<Version> probedVersion = this.versionProbe.probe(this.elasticsearchHosts);
+
+        probedVersion.ifPresent(version -> {
+            if (compatible(this.initialElasticsearchVersion, version)) {
+                notificationService.fixed(Notification.Type.ES_VERSION_MISMATCH);
+            } else {
+                LOG.warn("Elasticsearch version currently running (" + version.toString() + ") is incompatible with the " +
+                        "one Graylog was started with (" + initialElasticsearchVersion.toString() + ")" +
+                        " - a restart is required!");
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java:111]: Tiny nitpick: use placeholder instead of manual string concat makes it a bit more readable. :smile: 
```suggestion
                LOG.warn("Elasticsearch version currently running ({}) is incompatible with the " +
                        "one Graylog was started with ({}) - a restart is required!", version, initialElasticsearchVersion);
```

**Review by bernd — APPROVED** [review]
LGTM apart from two smaller things :+1:

File: graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java (hunk 2 above)
Comment (dennisoelkers) [reply graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java:111]: Indeed! :)

File: graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java (hunk 1 above)
Comment (dennisoelkers) [reply graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java:78]: Good point!

**Review by bernd — APPROVED** [review]
