### PR TITLE
Properly generating link to node's api browser.

### LINKED ISSUE #2131: RC.1 OVA API Browser button does not work
### Problem description

Using the 2.0 rc.1 ova, the System/Nodes page's api browser button does not work.
The URL is missing a `/` between port and path.

### Environment

* Graylog Version: 2.0.0-rc.1 beta OVA

### PR DESCRIPTION
**Pull request by dennisoelkers**
We are now using URI.js to make sure that there is a good number of slashes (more than 0 and less than 2 between host/port and directory) included in the generated link target.

Fixes #2131

### CODE REVIEW

File: graylog2-web-interface/src/components/nodes/NodesActions.jsx [hunk 1]
```diff
@@ -38,6 +39,7 @@ const NodesActions = React.createClass({
     }
   },
   render() {
+    const apiBrowserURI = new URI(this.props.node.transport_address).directory('api-browser');
```
Comment (joschi) [inline graylog2-web-interface/src/components/nodes/NodesActions.jsx]: I'm not 100% sure, but this could cause a problem if the transport address contains a path segment with trailing slash:
```
> URI("http://example.com/foo").directory("bar").toString()
"http://example.com/bar/foo"
> URI("http://example.com/foo/").directory("bar").toString()
"http://example.com/bar/"
```

Comment (dennisoelkers) [inline graylog2-web-interface/src/components/nodes/NodesActions.jsx]: Good point! urijs does not help us at all then :/

Comment (joschi) [inline graylog2-web-interface/src/components/nodes/NodesActions.jsx]: While certainly not nice, this would work:
```
> URI("http://example.com/foo" + "/" + "bar").toString()
"http://example.com/foo/bar"
> URI("http://example.com/foo/" + "/" + "bar").toString()
"http://example.com/foo//bar"
```
Or with the given code snippet:
```javascript
    const apiBrowserURI = new URI(this.props.node.transport_address + '/api-browser');
```
So in the end, this isn't *much* better than simply concatenating those strings but at least the result URI is normalized.

**Comment by dennisoelkers** [comment]
This is based on `master` branch, so it would need to be merged/cherry-picked into `2.0` after merging too.

**Comment by joschi** [comment]
LGTM. :+1:
