### PR TITLE
Issue 4003

### LINKED ISSUE #4003: ExceptionUtils#getRootCauseMessage can NPE
When constructing the root cause message, the Exception's message can be null which leads to an NPE.

### PR DESCRIPTION
**Pull request by kroepke**
Guard against NPE exception in ExceptionUtils#formatMessageCause

fixes #4003

### CODE REVIEW

File: graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+public class ExceptionUtilsTest {
+    @Test
+    public void formatMessageCause() throws Exception {
+
+        final NullPointerException npe = new NullPointerException();
+
+        try {
+            assertThat(ExceptionUtils.formatMessageCause(npe)).isNotBlank();
+        } catch (Exception e) {
+            fail(e.getMessage());
```
Comment (joschi) [inline graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java]: Random nitpick: The test fail anyway if an exception was thrown and not caught in `ExceptionUtils#formatMessageCause(…)`.
