### PR TITLE
Make API Tokens configurable in web interface

### LINKED ISSUE #3318: Show/Create Access Token in Webinterface
Hi

I'm a starter in graylog, so close my case, if you don't experiment this or I missunderstand something. It is also not so important to me, I just want let you know about my experiment.

I created token with curl, no problem.
So maybe I mixed to different function, ot this part of the web interface has big bugs.
I can't create token for non admin user (eg. monitoring user). Maybe good if you can create tokens for other users.

## Expected Behavior

With disable Access Token Authenticator I can't use tokens.
The website shows my current tokens.

## Current Behavior

I don't see the token at the web interface, under System/Authentication/Access Token Authenticator.
If I disable this module, I also can use the api token with success.
And the  "last_access" doesn't updated.
curl  -u  XX:XX  -X GET 'http://IP:9000/api/users/XX/tokens/?pretty=true'
{
  "tokens" : [ {
    "name" : "XX",
    "token" : "XX",
    "last_access" : "1970-01-01T00:00:00.000Z"
  } ]
}
kep

## Possible Solution

I don't see the token at the web interface, under System/Authentication/Access Token Authenticator.
If I disable this module, I also can use the api token with success.

## Steps to Reproduce (for bugs)

1. Create token
2. Check on the web page

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version:
* MongoDB Version:
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Browser version: Firefox 50.0.1

### PR DESCRIPTION
**Pull request by kmerz**
## Description
API Tokens are configurable via REST API but there is till now no way to
create, delete or list them in the web interface.

- I fixed the permissions handling for API Tokens which till now only worked, if the user requested his own tokens regardless of his role (like admin). That meant that even the admin could not alter the API Tokens. Now a normal user can only manage his own Tokens and a user with role *admin* can manage the tokens of other people additionally.
- Add a new TokenList Component which list, create and deletes tokens. I did not wire the UserStore into that component but rather gave handlers as arguments and implemented them by the caller. This is easier to test and easier to use IMHO.

## Motivation and Context
To use tokens a user needed to use the REST API manually to create delete or list
them.

## How Has This Been Tested?
I tested the REST API to ensure that the permissions worked as I described above.
I tested the TokenList manually.

## Screenshots (if appropriate):
graylog - edit tokens of user admin

Fixes #3318 
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
Great work! Maybe it makes more sense to use the [`KeyValueTable](https://graylog2.github.io/frontend-documentation/#keyvaluetable) for listing/modifying the tokens?

File: graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx [hunk 1]
```diff
@@ -115,9 +115,14 @@ const AuthenticationComponent = React.createClass({
...
-      authenticators = [<LinkContainer key="profile-edit" to={Routes.SYSTEM.AUTHENTICATION.USERS.edit(encodeURIComponent(this.state.currentUser.username))}>
-        <NavItem title="Edit User">Edit User</NavItem>
-      </LinkContainer>];
+      authenticators = [
+        <LinkContainer key="profile-edit" to={Routes.SYSTEM.AUTHENTICATION.USERS.edit(encodeURIComponent(this.state.currentUser.username))}>
+          <NavItem title="Edit Profile">Edit Profile</NavItem>
+        </LinkContainer>,
+        <LinkContainer key="profile-edit-tokens" to={Routes.SYSTEM.AUTHENTICATION.USERS.edit_tokens(encodeURIComponent(this.state.currentUser.username))}>
+          <NavItem title="Edit Tokens">Edit Tokens</NavItem>
+        </LinkContainer>
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx]: Another linter nitpick: Missing trailing comma.

File: graylog2-web-interface/src/pages/EditTokensPage.jsx [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    return (
+      <DocumentTitle title={`Edit tokens of user ${this.props.params.username}`}>
+        <span>
+          <PageHeader title={<span>Edit tokens of user <em>{this.props.params.username}</em></span>} subpage>
+            <span>You can create new tokens or delete old ones.</span>
+            {null}
+          </PageHeader>
+          <TokenList tokens={this.state.tokens}
+                     delete={this._deleteToken}
+                     create={this._createToken} />
```
Comment (edmundoa) [inline graylog2-web-interface/src/pages/EditTokensPage.jsx]: We usually name props expecting function handlers with "on" + verb (e.g. `onDelete` or `onCreate`) to differentiate them from other props at first glance.

File: graylog2-web-interface/src/components/users/TokenList.jsx [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+    this.setState({ token_name: '' });
+  }
+
+  itemActionsFactory(token) {
+    const copyButtonProps = {};
+    copyButtonProps['data-clipboard-text'] = token.token;
+
+    return (
+      <span>
+        <Button data-clipboard-button {...copyButtonProps} bsSize="xsmall">
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/users/TokenList.jsx]: Could we use the [`ClipboardButton`](https://graylog2.github.io/frontend-documentation/#clipboardbutton) component here?

File: graylog2-web-interface/src/components/users/TokenList.jsx [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+                id="create-token-input"
+                type="text"
+                placeholder="e.g ServiceName"
+                value={this.state.token_name}
+                onChange={this._onNewTokeChanged} />
+            </Col>
+            <Col sm={2}>
+              <Button id="create-token"
+                      disabled={this.state.token_name === ''}
+                      onClick={this._createToken}
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/users/TokenList.jsx]: We should move this function to the `onSubmit` event handler of the `form` element, and stop the event with `preventDefault()` in the handler. Otherwise clicking the button does a full page reload.

File: graylog2-web-interface/src/stores/users/UsersStore.ts [hunk 5]
```diff
@@ -95,6 +101,43 @@ export const UsersStore = {
...
+    return promise;
+  },
+
+  deleteToken(username: string, token_name: string): Promise<string[]> {
+    const  url = URLUtils.qualifyUrl(ApiRoutes.UsersApiController.delete_token(encodeURIComponent(username),
+      encodeURIComponent(token_name)).url, {});
+    const  promise = fetch('DELETE', url);
+
+    promise.then(() => {
+      UserNotification.success("Token \"" + token_name + "\" of user \"" + username + "\" was deleted successfully");
```
Comment (edmundoa) [inline graylog2-web-interface/src/stores/users/UsersStore.ts]: Could we display in this notification the token name instead of the token itself?

File: graylog2-web-interface/src/pages/EditTokensPage.jsx [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+      [`users:tokenlist:${username}`]);
+  },
+
+  _deleteToken(token) {
+    const promise = UsersStore.deleteToken(this.props.params.username, token);
+    promise.then(() => this._loadTokens(this.props.params.username));
+  },
+
+  _createToken(tokenName) {
+    const promise = UsersStore.createToken(this.props.params.username, tokenName);
```
Comment (edmundoa) [inline graylog2-web-interface/src/pages/EditTokensPage.jsx]: I think we should add a loading indicator when creating and deleting tokens, in case the API takes a while to return in here. Probably changing the button name and disabling it until the list is updated should suffice.

What do you think?

File: graylog2-web-interface/src/components/users/TokenList.jsx [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+    this.props.create(this.state.token_name);
+    this.setState({ token_name: '' });
+  }
+
+  itemActionsFactory(token) {
+    const copyButtonProps = {};
+    copyButtonProps['data-clipboard-text'] = token.token;
+
+    return (
+      <span>
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/users/TokenList.jsx]: I would use a `ButtonToolbar` in here to separate both buttons. If you think putting them together would make more sense, then I would use a `ButtonGroup`, which styles them a bit better for that.

File: graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java [hunk 8]
```diff
@@ -86,9 +86,7 @@
 import static com.google.common.base.MoreObjects.firstNonNull;
 import static java.util.stream.Collectors.groupingBy;
 import static java.util.stream.Collectors.maxBy;
-import static org.graylog2.shared.security.RestPermissions.USERS_EDIT;
-import static org.graylog2.shared.security.RestPermissions.USERS_PERMISSIONSEDIT;
-import static org.graylog2.shared.security.RestPermissions.USERS_ROLESEDIT;
+import static org.graylog2.shared.security.RestPermissions.*;
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java]: Please avoid wildcard imports. You can disable automatic insertion of wildcard imports in your Intellij config (`Code Style`/`Java`).

File: graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java [hunk 9]
```diff
@@ -423,11 +421,14 @@ public void changePassword(
 
     @GET
     @Path("{username}/tokens")
-    @RequiresPermissions(RestPermissions.USERS_TOKENLIST)
     @ApiOperation("Retrieves the list of access tokens for a user")
     public TokenList listTokens(@ApiParam(name = "username", required = true)
                                 @PathParam("username") String username) {
-        final User user = _tokensCheckAndLoadUser(username);
+        final User user = _tokensLoadUser(username);
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java]: I think the naming of that method is suboptimal, for two reasons:

  * Method names are not prefixed with `_` in Java. The signature already reveals that it is a private method.
  * The name `_tokensLoadUser` implies that it is specific to the Token management, which it is not. If it would be called `loadUser`, it would describe accurately what it does and it could be reused by the `changeUser` method.

File: graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java [hunk 10]
```diff
@@ -423,11 +421,14 @@ public void changePassword(
...
+
+        if (!isPermitted(USERS_TOKENLIST, username)) {
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java]: I think we should do the check before fetching the user, so the call cannot be used to find out existing usernames.

File: graylog2-web-interface/src/routing/Routes.jsx [hunk 11]
```diff
@@ -93,6 +93,8 @@ const Routes = {
       USERS: {
         CREATE: '/system/authentication/users/new',
         edit: username => `/system/authentication/users/edit/${username}`,
+        edit_tokens: username => `/system/authentication/users/tokens/${username}`,
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/routing/Routes.jsx]: I think it makes sense to group them as a `TOKENS` subkey, as tokens are a subresource of a user.

File: graylog2-web-interface/src/routing/Routes.jsx [hunk 12]
```diff
@@ -93,6 +93,8 @@ const Routes = {
...
+        TOKENS: '/system/authentication/users/tokens/',
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/routing/Routes.jsx]: This would become `TOKENS.LIST` then.

**Comment by dennisoelkers** [comment]
Would it make sense to allow the user to temporarily disable tokens? That means, a token is not deleted but still not usable for authenticating.

**Comment by edmundoa** [comment]
@dennisoelkers I think it would be a nice to have, although I would not include it in the scope of this PR. I think the goal here is to make authentication tokens visible (and usable) to users, and that is already achieved with the functionality in here. We could of course add that functionality in the future.

**Comment by edmundoa** [comment]
Looks good to me too! 👍

**Comment by laszlo-laszlo** [comment]
Great work!
