### PR TITLE
Encode URI query string params in DataAdapters query

### LINKED ISSUE #4816: Lookup Data Adapter lookup in web interface fails to URI-encode query
The web interface fails to correctly encode HTTP requests sent to the HTTP resource used to look up values on the System/Lookup Tables/   
Data Adapters page (Graylog REST API: `/system/lookup/adapters/{adapterName}/query`) which leads to false negatives if a reserved character such as '+' is being used.

**Example data `phone.csv`**
```text
'phonenumber';'areaname'
'+12226550020';'North Area'
'+12226550021';'South Area'
```

Lookup Data Adapter Query

**HTTP request sent by web interface**
```text
$ curl -u admin:admin 'http://127.0.0.1:9000/api/system/lookup/adapters/phone/query?key=+12226550020&pretty=true'
{
  "single_value" : null,
  "multi_value" : null,
  "ttl" : 9223372036854775807
}
```
**Correct HTTP request with URI-encoded query**
```text
$ curl -u admin:admin 'http://127.0.0.1:9000/api/system/lookup/adapters/phone/query?key=%2B12226550020&pretty=true'
{
  "single_value" : "North Area",
  "multi_value" : {
    "value" : "North Area"
  },
  "ttl" : 9223372036854775807
}
```

Refs https://community.graylog.org/t/lookup-table-potential-bug/5449

### PR DESCRIPTION
**Pull request by radykal-com**
Fixes #4816 

## How Has This Been Tested?
Created a csv file like in the issue description, and verified with the new code the query string params are URI encoded.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

File: graylog2-web-interface/src/stores/lookup-tables/LookupTableDataAdaptersStore.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ const LookupTableDataAdaptersStore = Reflux.createStore({
   },
 
   lookup(adapterName, key) {
-    const promise = fetch('GET', this._url(`adapters/${adapterName}/query?key=${key}`));
+    const promise = fetch('GET', this._url(`adapters/${adapterName}/query?key=${encodeURIComponent(key)}`));
```
Comment (bernd) [inline graylog2-web-interface/src/stores/lookup-tables/LookupTableDataAdaptersStore.js]: Can you please apply the same change to the lookup function in `LookupTablesStore.js` please?
