### PR TITLE
Reformatting component, adding error handler for fetching dashboard.

### LINKED ISSUE #2576: Attempt to access deleted dashboard only displays "Loading..." spinner (no error message shown)
### Problem description
If a dashboard is deleted and a user attempts to access that dashboard (perhaps she already had the Dashboards page open or has the dashboard saved as a favorite) the page only shows the "Loading..." spinner with no error notification.

Note that this differs slightly from streams, where a red "Could not retrieve Stream" notification appears (although the page is still stuck with the "Loading..." spinner).

### Steps to reproduce the problem
1. Log in as an admin
2. Navigate to Dashboards
3. Click the "Create dashboard" button and create a dashboard "Foo"
4. Open a second tab in your browser and navigate to Dashboards, noting that you can see dashboard "Foo"
5. Return to the first tab and select "Delete this dashboard" from the "More actions" menu of dashboard "Foo", confirming you want to delete it
6. Return to the second tab and open your browser's network request monitor
7. Click the link for dashboard "Foo" (e.g. `<GRAYLOG_WEB>/dashboards/579fa11c438960168517f09b`)
8. Note you see the "Loading..." spinner in the content area
9. Note every second you see a `GET` request to `<GRAYLOG_REST>/dashboards/579fa11c438960168517f09b` that returns HTTP 404, and no "Could not retrieve Stream" notification appears

### Environment
* Graylog Version: 2.0.3 and 2.1.0-beta.1+1b940e4
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 47, Chrome 51.0.2704.106m

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Description
This change adds an error handler for the `DashboardsStore.get()` call in the `ShowDashboardPage` which shows an error message and redirects to the dashboard list, if the call returns a 404.

## Motivation and Context
Before this change, going to a nonexisting dashboard link, the page would just show a spinner.

Fixes #2576 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-web-interface/src/pages/ShowDashboardPage.jsx [hunk 1]
```diff
@@ -56,6 +61,11 @@ const ShowDashboardPage = React.createClass({
         if (!this.state.dashboard || !deepEqual(this.state.dashboard, dashboard)) {
           this.setState({ dashboard: dashboard });
         }
+      }, (response) => {
+        if (response.additional && response.additional.status === 404) {
+          UserNotification.error(`Unable to find a dashboard with the id <${dashboardId}>. Maybe it was deleted in the mean time.`);
```
Comment (edmundoa) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: Minor nitpick: Isn't the expression "in the meantime" (without space)?

Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/ShowDashboardPage.jsx]: 👍

**Comment by edmundoa** [comment]
Looking good 👍
