### PR TITLE
Fix: Adding correct handling for streams filter in legacy searches

### LINKED ISSUE #21836: api/search/universal/absolute duplicates
api/search/universal/absolute returns the same log message multiple times even when filtered to a single stream.

## Expected Behavior
Adding "filter=streams:<id>" to the url should cause each log message to return only once.

## Current Behavior
The log message is returned once per stream it appears in

## Steps to Reproduce (for bugs)
Run a query like
https://graylog.xxxxxxxxx/api/search/universal/absolute?query=MyQuery&from=2025-02-28%2000%3A00%3A00&to=2025-02-28%2023%3A59%3A59&limit=100&offset=0&sort=timestamp%3Aasc
Messages get returned multiple times. I believe this is because they appear in multiple streams and i did not filter by stream.

Adjust the query to
https://graylog.xxxxxxxxx/api/search/universal/absolute?query=MyQuery&from=2025-02-28%2000%3A00%3A00&to=2025-02-28%2023%3A59%3A59&limit=100&offset=0&filter=streams%3A1234567890&sort=timestamp%3Aasc
Messages continue to appear multiple times in the results.

## Context
Simple work around is remove the returned duplicates.

## Your Environment
* Graylog Version: Graylog 6.1.7+6ec0bac

### PR DESCRIPTION
**Pull request by janheise**
## Description

Prior to this PR the legacy searches would add stream filters in the query string which is not correct/consistent with other parts of Graylog and does not work.
This PR adds a new API parameter to the endpoints and adds the streams to filter correctly (similar to the UI and SimpleScripting API endpoints)

fixes #21836 
 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java [hunk 1]
```diff
@@ -573,7 +573,7 @@ public void scrollReturnsMultipleChunksRespectingLimit() throws Exception {
 
         when(indexSetRegistry.getForIndices(Collections.singleton("graylog_0"))).thenReturn(Collections.singleton(indexSet));
         final AbsoluteRange range = AbsoluteRange.create(new DateTime(2015, 1, 1, 0, 0, DateTimeZone.UTC).withZone(UTC), new DateTime(2015, 1, 2, 0, 0, DateTimeZone.UTC).withZone(UTC));
-        final ChunkedResult scrollResult = searches.scroll("*", range, 5, 0, Collections.singletonList("source"), null, 2);
+        final ChunkedResult scrollResult = searches.scroll("*", range, 5, 0, Collections.singletonList("source"), null, Set.of(), 2);
```
Comment (luk-kaminski) [inline graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java:576]: With new method param for `streams`, couldn't you add at least one test that actually tests `scroll()` with `streams` param different than `Set.of()` ?

File: graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java [hunk 2]
```diff
@@ -90,6 +92,7 @@ public SearchResponse searchAbsolute(
             @ApiParam(name = "limit", value = "Maximum number of messages to return.") @QueryParam("limit") int limit,
             @ApiParam(name = "offset", value = "Offset") @QueryParam("offset") int offset,
             @ApiParam(name = "filter", value = "Filter") @QueryParam("filter") String filter,
+            @ApiParam(name = "streams", value = "Comma separated list of streams to search in") @QueryParam("streams")  String streams,
```
Comment (luk-kaminski) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java:95]: I may be a little bit to picky, but I would replace `Comma separated list of streams to search in` with `Comma separated list of stream IDs to search in`, to explicitly mention we are talking about stream IDs here...

**Review by luk-kaminski — APPROVED** [review]
LGTM, thx!
