### PR TITLE
Checking user privileges before performing Input State operations.

### LINKED ISSUE #4439: Non-admin user can stop/start an input
Non-admin user (i.e. any user) can stop or start an input by a REST API.

## Expected Behavior

Non-admin users is forbidden to start or stop input.

## Current Behavior

Non-admin user cannot see "Start Input" or "Stop Input" in System/Inputs in a web-interface.
But the user can stop or start input by using a REST API:

    # start
    curl -X PUT -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"

    # stop
    curl -X DELETE -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"

## Possible Solution

In current implementation, [`ClusterInputStatesResource`](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterInputStatesResource.java) does not check whether user have a permission to start or stop an input.  It should check permission `inputs:terminate` for current user.

## Steps to Reproduce (for bugs)

1. Create a non-admin user.
2. Stop input by non-admin user's credential
   ```
   curl -X DELETE -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"
   ```
3. Check input status by admin user.

## Context

I expect that can be a vulnerability.

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.3
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04
* Browser version:

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context
Before this change, any user was able to start/stop inputs without the
possession of the required privileges. The `InputStatesResource` class
did not perform any permission checks for operations.

After this change, a user who starts/stops an input requires the newly
introduced `inputs:changestate` permission (consistent with permission
handling of indices/processing/streams) in order to perform these
state changes.

Fixes #4439.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java [hunk 1]
```diff
@@ -67,6 +67,7 @@
     public static final String INDICES_DELETE = "indices:delete";
     public static final String INDICES_FAILURES = "indices:failures";
     public static final String INDICES_READ = "indices:read";
+    public static final String INPUTS_CHANGESTATE = "inputs:changestate";
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java]: Please add the new `INPUTS_CHANGESTATE` permission to the `PERMISSIONS` Set below.

Comment (dennisoelkers) [reply graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java]: ✅
