### PR TITLE
Fix sidebar highlighting rules layout for field values with a long name

### LINKED ISSUE #7738: Unable to remove highlighting when value exceeds div
#  Expected Behavior
You can remove any highlighted value using the trashcan icon.

## Current Behavior
If the highlighted value is too long the trashcan icon will fall outside the 250px width of the sidebar div:
image

## Your Environment
I think only these two are relevant, if more info is needed let me know.

* Graylog Version: 3.2.4
* Browser version: Chrome 80.0.3987.149 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by linuspahl**
As described in https://github.com/Graylog2/graylog2-server/issues/7738 the highlighting rules styling breaks if the related field value has a long name.

This PR fixes the problem by using a grid for each highlighting rule.
image

The PR also implements styled components instead of css modules, adjusts the related test. 

Fixes #7738

## How Has This Been Tested?
The changes have been tested with the latest browsers and IE11.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx [hunk 1]
```diff
@@ -1,14 +1,52 @@
...
+  > *:nth-child(2) {
+    grid-column: 2;
+    -ms-grid-column: 2;
+  }
+
+  > *:nth-child(3) {
+    grid-column: 3;
+    -ms-grid-column: 3;
+  }
+`;
```
Comment (linuspahl) [inline graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx:35]: The above `nth-child` styling is only required to support IE11. I used `:nth-child` instead of defining the styling for each child because it allows a more flexible usage of the component.

File: graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx [hunk 2]
```diff
@@ -30,19 +68,20 @@ const onDelete = (e, rule) => {
...
                           colors={DEFAULT_CUSTOM_HIGHLIGHT_RANGE.map((c) => [c])}
-                          triggerNode={<div className={styles.colorElement} style={{ backgroundColor: color }} />}
+                          triggerNode={<ColorPreview color={color} />}
                           onChange={(newColor, _, hidePopover) => updateColor(rule, newColor, hidePopover)} />
-      {' '}
-      for <strong>{field}</strong> = <i>&quot;{value}&quot;</i>.
-      <span role="presentation" title="Remove this Highlighting Rule" onClick={(e) => onDelete(e, rule)}>
+      <div>
+        for <strong>{field}</strong> = <i>&quot;{value}&quot;</i>.
+      </div>
```
Comment (linuspahl) [inline graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx:80]: I had to use a `<div>` instead of a `<span>` here, otherwise the grid will not be displayed correctly with IE11.

**Comment by linuspahl** [comment]
@dennisoelkers Good catch, I've updated the styling to prevent text overflow.
