### PR TITLE
Avoid using throw by displaying an Alert

### LINKED ISSUE #8756: Be more fault tolerant when dealing with errors in the new users and role pages.
On some places we throw an error (`thorw new Error()`) when we do not find an item. But we can be more tolerant with that so the user can fix that issue.
Also when dealing with errors while fetching data. If e.g. the request fails witch fetches all users for the UsersOverview, we receive `undefined` as a result for the action. In this case we will defined `undefined` for the UsersOverview component state, which results in frontend errors.

### PR DESCRIPTION
**Pull request by kmerz**
## Motivation
Prior to this change, when we had an runtime error we rendered the error
page to the user even though he might have been able to workarround an
issue.

## Description
This change implements a ErrorAlert component which is closable and
which will display an runtime error or warning. It replaces the
warnings already implemented and does also replace the `throw` errors
for users and roles components.

Fixes #8756

### CODE REVIEW

File: graylog2-web-interface/src/components/permissions/RolesSelector.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const _options = (roles, assignedRolesIds, identifier) => roles
   .toArray()
   .map((r) => ({ label: r.name, value: r.name, role: r }));
 
-const _assignRole = (selectedRoleName, roles, onSubmit, setSelectedRoleName, setIsSubmitting) => {
+const _assignRole = (selectedRoleName, roles, onSubmit, setSelectedRoleName, setIsSubmitting, setError) => {
```
Comment (linuspahl) [inline graylog2-web-interface/src/components/permissions/RolesSelector.jsx:47]: Lets reset the error somewhere, otherwise it will not get removed on a successful request.

File: graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx [hunk 2]
```diff
@@ -88,7 +89,9 @@ const UsersSelector = ({ role, onSubmit }: Props) => {
     })));
 
     if (!userOverview) {
-      throw new Error(`Unable to find user with name ${user} in ${users.map((u) => u.username).join(', ')}`);
+      setError(`This is an exceptional error! Unable to find user with name ${user} in ${users.map((u) => u.username).join(', ')}`);
```
Comment (linuspahl) [inline graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx:92]: We should somewhere reset the error in this case as well.

**Review by linuspahl — CHANGES_REQUESTED** [review]
Just added a suggestion.

**Review by linuspahl — APPROVED** [review]
Looks good to me!
