### PR TITLE
Fix search form width bug

### LINKED ISSUE #13752: SearchFrom UI width bug in Alerts page
Styling problem with the SearchFrom component in /alerts

image

### PR DESCRIPTION
**Pull request by gally47**
## Description
Before one shared prop **queryWidth** was used for both the input width and its container width which caused a bug in /alert page's search form. Now this PR fixes that by adding a different prop for the container's width: **queryContainerWidth**.

## Motivation and Context

fixes #13752

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx [hunk 1]
```diff
@@ -214,7 +214,11 @@ const CollectorConfigurationModal = ({
         </ModalTitle>
       </Modal.Header>
       <Modal.Body>
-        <SearchForm query={searchQuery} onQueryChange={(q) => setSearchQuery(q)} topMargin={0} queryWidth="100%" />
+        <SearchForm query={searchQuery}
```
Comment (ousmaneo) [inline graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx:217]: I think here we should use styled-component instead of introducing new props to the `SeachForm` component: 
- We can create a StyledSearchForm as below
```
const StyledSearchForm = styled(SearchForm)`
  .form-group, .query {
    width: 100% !important;
  }
`;
```
- then use it here:
```suggestion
        <StyledSearchForm query={searchQuery}
```

Comment (ousmaneo) [reply graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx:217]: Then we can remove the passed props below here and also from the `SearchForm` component.

**Review by ousmaneo — COMMENTED** [review]
Hi thank you for the PR, I made some suggestions inline.
Can you please link the original issue in the description, we can create it if it does not exist already.

**Review by ousmaneo — APPROVED** [review]
LGTM!
