### PR TITLE
Scroll-based chunking replaced with search-after-pagination in MoreSe…

### LINKED ISSUE #12996: Event definitions using many streams can cause HTTP 413 error on Elasticsearch
## Expected Behavior

Event definitions involving many / all streams should work.

## Current Behavior

We noticed the following error when using events involving many streams:

```
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: method [POST], host [https://<REMOVED>], URI [/gl_windows_security_49,gl_windows_common_4,gl_windows_common_3,gl_okta_7,gl_okta_6,gl_okta_5,gl_okta_4,gl_okta_9,gl_okta_8,gl_okta_3,gl_okta_2,gl_okta_1,gl_okta_0,gl_cisco_36,gl_cisco_35,gl_cisco_34,gl_cisco_33,gl_cisco_39,gl_cisco_38,gl_cisco_37,gl_cisco_43,gl_cisco_42,gl_cisco_41,gl_cisco_40,gl_cisco_47,gl_cisco_46,gl_cisco_45,gl_cisco_44,gl_cisco_49,gl_cisco_48,gl_cisco_50,gl_cisco_19,gl_cisco_14,gl_cisco_13,gl_cisco_12,gl_cisco_11,gl_cisco_18,gl_cisco_17,gl_cisco_16,gl_cisco_15,gl_cisco_21,gl_sysmon_280,gl_cisco_20,gl_sysmon_281,gl_sysmon_282,gl_sysmon_283,gl_sysmon_284,gl_sysmon_285,gl_sysmon_286,gl_sysmon_287,gl_sysmon_288,gl_sysmon_289,gl_windows_security_13,gl_windows_security_10,gl_windows_security_11,gl_cisco_25,gl_cisco_24,gl_cisco_23,gl_cisco_22,gl_cisco_29,gl_cisco_28,gl_cisco_27,gl_cisco_26,gl_cisco_32,gl_cisco_31,gl_sysmon_270,gl_cisco_30,gl_sysmon_271,gl_sysmon_272,gl_sysmon_273,gl_sysmon_274,gl_sysmon_275,gl_sysmon_276,gl_sysmon_277,gl_sysmon_278,gl_sysmon_279,gl-system-events_315,gl-system-events_314,gl-system-events_313,gl-system-events_312,gl-system-events_311,gl-system-events_310,gl-system-events_319,gl-system-events_318,gl-system-events_317,gl-system-events_316,gl-system-events_304,gl-system-events_303,gl-system-events_302,gl-system-events_301,gl_sysmon_290,gl-system-events_300,gl_cisco_10,gl_sysmon_291,gl_sysmon_292,gl_sysmon_293,gl_sysmon_294,gl_sysmon_295,gl_sysmon_296,gl_sysmon_297,gl-system-events_309,gl_sysmon_298,gl-system-events_308,gl_sysmon_299,gl-system-events_307,gl-system-events_306,gl-system-events_305,gl_linux_auditbeat_47,gl_windowsevent_296,gl_linux_auditbeat_48,gl_windowsevent_295,gl_linux_auditbeat_45,gl_windowsevent_298,gl_linux_auditbeat_46,gl_windowsevent_297,gl_linux_auditbeat_43,gl_linux_auditbeat_44,gl_windowsevent_299,gl_linux_auditbeat_41,gl_linux_auditbeat_42,gl-system-events_340,gl_windowssecurity_308,gl_windowssecurity_307,gl-events_298,gl_windowssecurity_309,gl_windowssecurity_304,gl_windowssecurity_303,gl_linux_auditbeat_49,gl_windowssecurity_306,gl_windowssecurity_305,gl-system-events_337,gl_windowssecurity_311,gl-system-events_336,gl_windowssecurity_310,gl-system-events_335,gl_windowssecurity_313,gl-system-events_334,gl_windowssecurity_312,gl-events_291,gl-system-events_333,gl-system-events_332,gl-system-events_331,gl-system-events_330,gl_linux_auditbeat_40,gl-system-events_339,gl-system-events_338,gl_linux_auditbeat_36,gl_windowsevent_285,gl_linux_auditbeat_37,gl_windowsevent_284,gl_linux_auditbeat_34,gl_windowsevent_287,gl_linux_auditbeat_35,gl_windowsevent_286,gl_linux_auditbeat_32,gl_windowsevent_289,gl_linux_auditbeat_33,gl_windowsevent_288,gl_linux_auditbeat_30,gl_linux_auditbeat_31,gl_linux_auditbeat_38,gl_linux_auditbeat_39,gl-system-events_326,gl_windowssecurity_300,gl-system-events_325,gl-system-events_324,gl_windowssecurity_302,gl-system-events_323,gl_windowssecurity_301,gl-system-events_322,gl-system-events_321,gl-system-events_320,gl_windowsevent_290,gl_windowsevent_292,gl-system-events_329,gl_windowsevent_291,gl-system-events_328,gl_windowsevent_294,gl-system-events_327,gl_windowsevent_293,gl_linux_auditbeat_25,gl_linux_auditbeat_26,gl_linux_auditbeat_23,gl_linux_auditbeat_24,gl_linux_auditbeat_21,gl_linux_auditbeat_22,gl_linux_auditbeat_20,gl_windowssecurity_329,gl_linux_auditbeat_29,gl_windowssecurity_326,gl_windowssecurity_325,gl_linux_auditbeat_27,gl_windowssecurity_328,gl_linux_auditbeat_28,gl_windowssecurity_327,gl_windowssecurity_333,gl_windowssecurity_332,gl_windowssecurity_335,gl_windowssecurity_334,gl_sysmon_260,gl_windowssecurity_331,gl_sysmon_261,gl_windowssecurity_330,gl_sysmon_262,gl_sysmon_263,gl_sysmon_264,gl_sysmon_265,gl_sysmon_266,gl_sysmon_267,gl_sysmon_268,gl_sysmon_269,gl_linux_auditbeat_14,gl_sysmon_259,gl_linux_auditbeat_15,gl_linux_auditbeat_12,gl_linux_auditbeat_13,gl_linux_auditbeat_10,gl_linux_auditbeat_11,gl-system-events_351,gl_windowssecurity_319,gl-system-events_350,gl_windowssecurity_318,gl_linux_auditbeat_18,gl_windowssecurity_315,gl_linux_auditbeat_19,gl_windowssecurity_314,gl_linux_auditbeat_16,gl_windowssecurity_317,gl_linux_auditbeat_17,gl_windowssecurity_316,gl-system-events_348,gl_windowssecurity_322,gl-system-events_347,gl_windowssecurity_321,gl-system-events_346,gl_windowssecurity_324,gl-system-events_345,gl_windowssecurity_323,gl-system-events_344,gl-system-events_343,gl-system-events_342,gl_windowssecurity_320,gl-system-events_341,gl_sysmon_257,gl-system-events_349,gl_sysmon_258,gl_windowsevent_258,gl_windowsevent_257,gl_windowsevent_259,gl_o365_261,gl_o365_260,gl_o365_263,gl_o365_262,gl_o365_265,gl_o365_264,gl_o365_267,gl_o365_266,gl_o365_269,gl_o365_268,gl_windowsevent_261,gl_windowsevent_260,gl-events_263,gl_o365_258,gl_o365_257,gl_o365_259,gl_windowsevent_274,gl_windowsevent_273,gl_windowsevent_276,gl_windowsevent_275,gl_windowsevent_278,gl_windowsevent_277,gl_windowsevent_279,gl_o365_281,gl_o365_280,gl_o365_283,gl_o365_282,gl-events_277,gl_o365_285,gl_o365_284,gl_o365_287,gl_o365_286,gl_o365_289,gl_o365_288,gl_windowsevent_281,gl_windowsevent_280,gl_windowsevent_283,gl_windowsevent_282,gl_windows_sysmon_7,gl_windowsevent_263,gl_windows_sysmon_6,gl_windowsevent_262,gl_windows_sysmon_9,gl_windowsevent_265,gl_windows_sysmon_8,gl_windowsevent_264,gl_windows_sysmon_3,gl_windowsevent_267,gl_windows_sysmon_2,gl_windowsevent_266,gl_windows_sysmon_5,gl_windowsevent_269,gl_windows_sysmon_4,gl_windowsevent_268,gl_o365_270,gl_o365_272,gl_windows_sysmon_1,gl_o365_271,gl_windows_sysmon_0,gl_o365_274,gl_o365_273,gl_o365_276,gl_o365_275,gl_o365_278,gl_o365_277,gl_o365_279,gl-events_283,gl_windowsevent_270,gl_windowsevent_272,gl_windowsevent_271,gl_windowsevent_331,gl_windowsevent_330,gl_windowsevent_333,gl_windowsevent_332,graylog_320,gl_windowsevent_335,gl_windowsevent_334,gl_fortinet_8,gl_windowsevent_337,gl_fortinet_9,gl_windowsevent_336,gl_fortinet_6,gl_windowsevent_339,gl-events_331,gl_fortinet_7,gl_windowsevent_338,gl-events_332,gl-events_333,gl-events_334,gl_cbdefense_16,gl_fortinet_0,gl_windowssecurity_278,gl_cbdefense_15,gl_fortinet_1,gl_windowssecurity_277,gl_cbdefense_18,gl_cbdefense_17,gl_windowssecurity_279,gl_cbdefense_12,gl_fortinet_4,gl_windowssecurity_274,gl_cbdefense_11,gl_fortinet_5,gl_windowssecurity_273,gl_cbdefense_14,gl_fortinet_2,gl_windowssecurity_276,gl_cbdefense_13,gl_fortinet_3,gl_windowssecurity_275,gl_windowssecurity_270,gl_cbdefense_10,gl_windowssecurity_272,gl_windowssecurity_271,gl-events_347,graylog_312,graylog_313,gl-events_349,gl_windowsevent_320,graylog_310,gl_windowsevent_322,gl_windowsevent_321,gl_o365_290,gl_windowsevent_324,gl_windowsevent_323,gl_o365_292,gl_windowsevent_326,gl-events_340,gl_o365_291,gl_windowsevent_325,gl_o365_294,gl_windowsevent_328,gl_o365_293,gl_windowsevent_327,gl_o365_296,graylog_316,gl_o365_295,gl_windowsevent_329,gl_windowssecurity_259,graylog_317,gl_o365_298,graylog_314,gl_o365_297,graylog_315,gl_windowssecurity_267,gl_o365_299,gl_windowssecurity_266,gl_windowssecurity_269,gl_windowssecurity_268,gl_windowssecurity_263,gl_windowssecurity_262,gl_windowssecurity_265,gl_windowssecurity_264,gl_windowssecurity_261,gl_windowssecurity_260,gl-events_351,graylog_307,graylog_308,graylog_305,graylog_306,graylog_304,gl_cbdefense_38,gl_cbdefense_37,gl_windowssecurity_299,gl_cbdefense_39,gl_cbdefense_34,gl_windowssecurity_296,gl_cbdefense_33,gl_windowssecurity_295,gl_cbdefense_36,gl_windowssecurity_298,gl_cbdefense_35,gl_windowssecurity_297,gl_cbdefense_30,gl_windowssecurity_292,gl_windowssecurity_291,gl_cbdefense_32,gl_windowssecurity_294,gl_cbdefense_31,gl_windowssecurity_293,gl_windowssecurity_290,gl_windowsevent_340,gl_windowsevent_342,gl_windowsevent_341,gl_windowsevent_344,gl_windowsevent_343,gl_windowsevent_346,gl_windowsevent_345,gl_symantec_0,gl_symantec_2,gl_symantec_1,gl_symantec_4,gl_cbdefense_19,gl_symantec_3,gl_symantec_6,gl_symantec_5,gl_cbdefense_27,gl_symantec_8,gl_windowssecurity_289,gl_cbdefense_26,gl_symantec_7,gl_windowssecurity_288,gl_cbdefense_29,gl_cbdefense_28,gl_symantec_9,gl_cbdefense_23,gl_windowssecurity_285,gl_cbdefense_22,gl_windowssecurity_284,gl_cbdefense_25,gl_windowssecurity_287,gl_cbdefense_24,gl_windowssecurity_286,gl_windowssecurity_281,gl_windowssecurity_280,gl_cbdefense_21,gl_windowssecurity_283,gl_cbdefense_20,gl_windowssecurity_282,gl-events_309,graylog_351,gl-events_302,gl_cbdefense_49,gl_windows_security_3,gl_cbdefense_48,gl_windows_security_4,gl_windows_security_2,gl_cbdefense_45,gl_cbdefense_44,gl_windows_security_8,gl_cbdefense_47,gl_cbdefense_46,gl_windows_security_6,gl_cbdefense_41,gl_cbdefense_40,gl_cbdefense_43,gl_cbdefense_42,gl-events_318,gl_windowsevent_311,gl-events_319,gl_windowsevent_310,gl_windowsevent_313,gl_windowsevent_312,gl_windowsevent_315,gl_windowsevent_314,gl_windowsevent_317,gl_windowsevent_316,gl-events_310,gl_windowsevent_319,gl_windowsevent_318,gl-events_312,gl-events_313,gl_linux_auditbeat_8,gl_linux_auditbeat_7,gl_windowssecurity_258,gl_linux_auditbeat_9,gl_windowssecurity_257,gl_linux_auditbeat_4,gl_linux_auditbeat_3,gl_linux_auditbeat_6,gl_linux_auditbeat_5,gl-events_325,graylog_334,gl-events_326,gl-events_327,gl-events_329,gl_windowsevent_300,gl_windowsevent_302,gl_windowsevent_301,gl_linux_auditbeat_0,gl_windowsevent_304,gl_windowsevent_303,gl_linux_auditbeat_2,gl_windowsevent_306,gl-events_320,gl_linux_auditbeat_1,gl_windowsevent_305,gl_windowsevent_308,gl_windowsevent_307,graylog_336,gl_windowsevent_309,gl_paloalto_3,gl_paloalto_4,gl_paloalto_5,gl_paloalto_6,gl_paloalto_7,gl_paloalto_8,gl_paloalto_9,gl_paloalto_0,gl_paloalto_1,gl_paloalto_2,gl-failures_204,gl-failures_205,gl-failures_206,gl-failures_207,gl-failures_208,gl-failures_209,gl-failures_200,gl-failures_201,gl-failures_202,gl-failures_203,gl-failures_210,gl-failures_211,gl-failures_212,gl-failures_213,gl_windows_common_50,gl_cbdefense_8,gl_cbdefense_9,gl_cbdefense_0,gl_cbdefense_1,gl_cbdefense_2,gl_cbdefense_3,gl_cbdefense_4,gl_cbdefense_5,gl_cbdefense_6,gl_cbdefense_7,gl_okta_49,gl_okta_48,gl_okta_45,gl_okta_44,gl_okta_47,gl_okta_46,gl_okta_41,gl_okta_40,gl_okta_43,gl_okta_42,gl_okta_38,gl_okta_37,gl_okta_39,gl_okta_34,gl_okta_33,gl_okta_36,gl_okta_35,gl_okta_30,gl_okta_32,gl_okta_31,gl_symantec_41,gl_symantec_42,gl_symantec_43,gl_symantec_44,gl_okta_27,gl_okta_26,gl_okta_29,gl_okta_28,gl_symantec_40,gl_symantec_49,gl_symantec_45,gl_symantec_46,gl_symantec_47,gl_symantec_48,gl_okta_23,gl_okta_22,gl_okta_25,gl_okta_24,gl_okta_21,gl_okta_20,gl_symantec_30,gl_okta_19,gl_symantec_31,gl_symantec_32,gl_symantec_33,gl_okta_16,gl_okta_15,gl_okta_18,gl_okta_17,gl_symantec_38,gl_symantec_39,gl_symantec_34,gl_symantec_35,gl_symantec_36,gl_symantec_37,gl_paloalto_49,gl_okta_12,gl_okta_11,gl_okta_14,gl_okta_13,gl_okta_10,gl_o365_300,gl_symantec_20,gl_o365_302,gl_symantec_21,gl_o365_301,gl_symantec_22,gl_o365_304,gl_o365_303,gl_o365_306,gl_o365_305,gl_paloalto_40,gl_o365_308,gl_paloalto_41,gl_symantec_27,gl_o365_307,gl_paloalto_42,gl_symantec_28,gl_paloalto_43,gl_symantec_29,gl_o365_309,gl_paloalto_44,gl_paloalto_45,gl_symantec_23,gl_paloalto_46,gl_symantec_24,gl_paloalto_47,gl_symantec_25,gl_paloalto_48,gl_symantec_26,gl_paloalto_38,gl_paloalto_39,gl_symantec_10,gl_symantec_11,gl_paloalto_30,gl_symantec_16,gl_paloalto_31,gl_symantec_17,gl_paloalto_32,gl_symantec_18,gl_paloalto_33,gl_symantec_19,gl_paloalto_34,gl_symantec_12,gl_paloalto_35,gl_symantec_13,gl_paloalto_36,gl_symantec_14,gl_paloalto_37,gl_symantec_15,gl_paloalto_27,gl_paloalto_28,gl_paloalto_29,gl_o365_320,gl_o365_322,gl_o365_321,gl_o365_324,gl_o365_323,gl_o365_326,gl_o365_325,gl_o365_328,gl_o365_327,gl_o365_329,gl_paloalto_20,gl_paloalto_21,gl_paloalto_22,gl_paloalto_23,gl_paloalto_24,gl_paloalto_25,gl_paloalto_26,gl_paloalto_16,gl_paloalto_17,gl_paloalto_18,gl_paloalto_19,gl_o365_311,gl_o365_310,gl_o365_313,gl_o365_312,gl_o365_315,gl_o365_314,gl_o365_317,gl_o365_316,gl_o365_319,gl_o365_318,gl_paloalto_10,gl_paloalto_11,gl_paloalto_12,gl_paloalto_13,gl_paloalto_14,gl_paloalto_15,gl_o365_340,gl_o365_342,gl_o365_341,gl_o365_344,gl_windows_sysmon_49,gl_o365_343,gl_windows_sysmon_48,gl_o365_346,gl_windows_sysmon_47,gl_o365_345,gl_windows_sysmon_46,gl_windows_sysmon_45,gl_windows_sysmon_44,gl_windows_sysmon_43,gl_windows_sysmon_42,gl_windows_sysmon_41,gl_windows_sysmon_40,gl_o365_331,gl_o365_330,gl_o365_333,gl_o365_332,gl_o365_335,gl_o365_334,gl_o365_337,gl_o365_336,gl_o365_339,gl_o365_338,gl_sysmon_325,gl_sysmon_326,gl_sysmon_327,gl_sysmon_328,gl_sysmon_329,gl-system-events_263,gl-system-events_262,gl_sysmon_320,gl_sysmon_321,gl_sysmon_322,gl_sysmon_323,gl_sysmon_324,gl_sysmon_314,gl_sysmon_315,gl_sysmon_316,gl_sysmon_317,gl_sysmon_318,gl_sysmon_319,gl_sysmon_310,gl_sysmon_311,gl_sysmon_312,gl_sysmon_313,gl-system-events_285,gl-system-events_284,gl-system-events_283,gl-system-events_282,gl-system-events_281,gl-system-events_280,gl-system-events_279,gl-system-events_278,gl-system-events_277,gl-system-events_276,gl-system-events_275,gl_sysmon_340,gl_sysmon_341,gl_sysmon_342,gl_sysmon_343,gl_sysmon_344,gl_sysmon_345,gl_sysmon_346,gl_sysmon_336,gl_sysmon_337,gl_sysmon_338,gl_sysmon_339,gl-system-events_274,gl-system-events_273,gl-system-events_272,gl-system-events_271,gl-system-events_270,gl-system-events_269,gl-system-events_268,gl-system-events_267,gl-system-events_266,gl-system-events_265,gl-system-events_264,gl_sysmon_330,gl_sysmon_331,gl_sysmon_332,gl_sysmon_333,gl_sysmon_334,gl_sysmon_335,gl-system-events_299,gl-system-events_298,gl-system-events_297,gl-failures_184,gl-system-events_296,gl-system-events_295,gl-system-events_294,gl-system-events_293,gl-system-events_292,gl-system-events_291,gl-system-events_290,gl-system-events_289,gl-system-events_288,gl-system-events_287,gl-system-events_286,gl_sysmon_303,gl_sysmon_304,gl-failures_190,gl_sysmon_305,gl-failures_191,gl_sysmon_306,gl-failures_192,gl_sysmon_307,gl-failures_193,gl_sysmon_308,gl-failures_194,gl_sysmon_309,gl-failures_195,gl-failures_185,gl-failures_186,gl-failures_187,gl-failures_188,gl-failures_189,gl_sysmon_300,gl_sysmon_301,gl_sysmon_302,gl-failures_196,gl-failures_197,gl-failures_198,gl-failures_199,gl_windowssecurity_337,gl_windows_sysmon_19,gl_windowssecurity_336,gl_windows_sysmon_18,gl_windowssecurity_339,gl_windows_sysmon_17,gl_windowssecurity_338,gl_windows_sysmon_16,gl_windowssecurity_344,gl_windows_sysmon_15,gl_windowssecurity_343,gl_windows_sysmon_14,gl_windowssecurity_346,gl_windows_sysmon_13,gl_windowssecurity_345,gl_windows_sysmon_12,gl_windowssecurity_340,gl_windows_sysmon_11,gl_windows_sysmon_10,gl_windowssecurity_342,gl_windowssecurity_341,gl_windows_sysmon_29,gl_windows_sysmon_28,gl_windows_sysmon_27,gl_windows_sysmon_26,gl_windows_sysmon_25,gl_windows_sysmon_24,gl_windows_sysmon_23,gl_windows_sysmon_22,gl_windows_sysmon_21,gl_windows_sysmon_20,gl_windows_sysmon_39,gl_windows_sysmon_38,gl_windows_sysmon_37,gl_windows_sysmon_36,gl_windows_sysmon_35,gl_windows_sysmon_34,gl_windows_sysmon_33,gl_windows_sysmon_32,gl_windows_sysmon_31,gl_windows_sysmon_30,gl_fortinet_41,gl_fortinet_40,gl_fortinet_43,gl_fortinet_42,gl_fortinet_45,gl_fortinet_44,gl_fortinet_47,gl_fortinet_46,gl_fortinet_49,gl_fortinet_48,gl_fortinet_21,gl_fortinet_20,gl_fortinet_23,gl_fortinet_22,gl_fortinet_25,gl_fortinet_24,gl_fortinet_27,gl_fortinet_26,gl_fortinet_29,gl_fortinet_28,gl_cisco_3,gl_cisco_2,gl_cisco_1,gl_cisco_0,gl_cisco_7,gl_cisco_6,gl_cisco_5,gl_cisco_4,gl_cisco_9,gl_cisco_8,gl_fortinet_30,gl_fortinet_32,gl_fortinet_31,gl_fortinet_34,gl_fortinet_33,gl_fortinet_36,gl_fortinet_35,gl_fortinet_38,gl_fortinet_37,gl_fortinet_39,graylog_295,gl_fortinet_10,gl_fortinet_12,gl_fortinet_11,gl_fortinet_14,gl_fortinet_13,graylog_294,gl_fortinet_16,gl_fortinet_15,gl_fortinet_18,gl_fortinet_17,gl_fortinet_19/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 413 FULL head]

	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$singleSearch$1(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:109) ~[?:?]
	... 19 more
```

## Possible Solution

It looks to me like this could be solved by moving the stream names from the URI to the request body.

## Context

@yfoelling and @craig-thomas noticed this in Graylog Cloud.

### LINKED ISSUE #13675: Events fail to execute if there are too many indices causing the elasticsearch/opensearch URI to be longer than 4096 bytes
The Graylog Event Processor will throw ERRORs if the graylog cluster has too many indices.

```
Caught an unhandled exception while executing event processor
[...]
"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."
```

## Expected Behavior

Graylog events continue to work regardless of how many indices are present

## Current Behavior

If there are too many indices, the URI that graylog sends to Elasticsearch/Opensearch is longer than 4096 bytes and ES/OS throws error 400.

`"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."`

## Steps to Reproduce (for bugs)

1. Create indicies so that the URI sent to ES/OS will be longer than 4096

## Context

This can cause events to not execute. It also "fails silently" meaning there isn't any indication that something is wrong. I randomly saw a message in my graylog cluster and i just happen to be collecting the graylog-server `server.log` via filebeat.

## Your Environment

* Graylog Version: Graylog 4.3.8+8c4705e
* Java Version: 11.0.16
* Elasticsearch Version: Opensearch 1.3.4
* MongoDB Version: 4.4.15
* Operating System: Ubuntu Server 20.04 LTS
* Browser version: 106.0.5249.103

## Additional Log Data

```
2022-10-12T14:52:55.430-05:00 ERROR [EventProcessorEngine] Caught an unhandled exception while executing event processor <aggregation-v1/Illuminate:Events:4;Windows:Detect weak kerberos ticket requests/629e225798300f79487f0cb8> - Make sure to modify the event processor to throw only EventProcessorExecutionException so we get more context!
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to perform scroll search
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:151) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:111) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.singleSearch(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.Scroll.scroll(Scroll.java:51) ~[?:?]
	at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.scrollEvents(MoreSearchAdapterES7.java:139) ~[?:?]
	at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:230) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:125) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:172) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:150) ~[graylog.jar:?]
	at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:150) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
	at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=too_long_http_line_exception, reason=An HTTP line is larger than 4096 bytes.]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$singleSearch$1(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:109) ~[?:?]
	... 19 more
	Suppressed: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:9200], URI [/custom_gim_haproxy_4,custom_gim_haproxy_5,custom_gim_haproxy_9,msdns_1084,msdns_1071,msdns_1070,msdns_1073,msdns_1072,msdns_1075,msdns_1074,msdns_1076,gl_paloalto_60,gl_paloalto_61,gl_paloalto_62,gl-system-events_2,gl_paloalto_63,gl-system-events_3,gl_paloalto_64,gl-system-events_0,gl_paloalto_65,gl-system-events_1,gl_paloalto_66,gl_paloalto_67,gl_paloalto_68,gl-system-events_4,gl_paloalto_69,gl-system-events_5,gl_anomaly_18,msdns_1060,gl_anomaly_17,msdns_1062,gl_anomaly_19,msdns_1061,gl_anomaly_14,gl_anomaly_13,gl_anomaly_15,gl_anomaly_10,msdns_1068,msdns_1067,gl_anomaly_12,gl_anomaly_11,msdns_1069,msdns_1064,msdns_1063,msdns_1066,msdns_1065,gl_paloalto_50,gl_paloalto_51,gl_linux_auditbeat_94,gl_paloalto_52,gl_paloalto_53,gl_paloalto_54,gl_paloalto_55,gl_paloalto_56,gl_linux_auditbeat_90,gl_paloalto_57,gl_paloalto_58,gl_paloalto_59,gl_anomaly_29,gl_paloalto_49,gl-failures_70,gl_anomaly_28,gl_anomaly_25,gl_anomaly_24,gl_anomaly_27,gl_anomaly_26,gl-failures_77,gl_anomaly_21,gl_anomaly_20,gl-failures_75,gl_anomaly_23,gl_anomaly_22,gl-failures_73,gl-failures_74,gl-failures_71,gl-failures_72,gl-failures_79,gl_paloalto_42,gl_paloalto_43,gl_paloalto_44,gl_paloalto_45,gl_paloalto_46,gl_paloalto_47,gl-failures_80,gl_paloalto_38,gl-failures_81,gl_anomaly_39,gl_paloalto_39,gl_anomaly_36,gl_anomaly_35,gl_anomaly_38,gl_anomaly_37,gl_o365_0,gl_anomaly_32,gl-failures_89,gl-failures_86,gl_anomaly_34,gl_anomaly_33,gl-failures_84,gl-failures_85,gl-failures_82,gl_anomaly_30,gl-failures_83,gl_paloalto_30,gl_paloalto_31,gl_paloalto_32,gl_paloalto_33,gl_paloalto_34,gl_paloalto_35,gl_paloalto_36,gl_paloalto_37,gl_paloalto_27,gl_paloalto_28,gl_paloalto_29,gl_anomaly_47,gl_anomaly_46,gl_anomaly_49,gl_anomaly_48,gl_anomaly_43,gl_anomaly_42,gl_anomaly_45,gl_anomaly_44,gl_anomaly_41,gl_anomaly_40,opsrch_87,gl_paloalto_20,gl_paloalto_21,gl_paloalto_22,gl_paloalto_23,opsrch_82,gl_paloalto_24,opsrch_83,gl_paloalto_25,gl_paloalto_26,graylog_2,gl_paloalto_16,gl_paloalto_17,gl_paloalto_18,gl_paloalto_19,gl_anomaly_58,gl_anomaly_57,gl_anomaly_59,gl_anomaly_54,gl-failures_67,gl_anomaly_53,gl_anomaly_56,gl_anomaly_55,gl_anomaly_50,gl_anomaly_52,gl_anomaly_51,gl_paloalto_3,gl_paloalto_4,gl_paloalto_5,gl_paloalto_6,gl_paloalto_7,gltrfc_5,gl_paloalto_8,gltrfc_6,gl_paloalto_9,gltrfc_3,gltrfc_4,gltrfc_9,gl_paloalto_10,gltrfc_7,gltrfc_8,gl_paloalto_12,gl_windows_common_96,gl_paloalto_13,gl_paloalto_2,glserver_89,gl_anomaly_69,gl_anomaly_68,custom_gim_pfsense_37,custom_gim_pfsense_38,gl_anomaly_65,gl_anomaly_67,gl_anomaly_66,gl_anomaly_61,gl_anomaly_60,gl_anomaly_63,glserver_85,gl_anomaly_79,gl_anomaly_76,gl_anomaly_75,gl_anomaly_78,gl_anomaly_77,gl_anomaly_72,gl_anomaly_71,gl_anomaly_74,custom_gim_pfsense_42,gl_anomaly_73,pf_45,gl_anomaly_70,gl_windows_sysmon_58,gl_windows_sysmon_55,msiis_62,msiis_60,msiis_61,msiis_59,gl-failures_92,gl_linux_metricbeat_82,msiis_57,gl-failures_90,msiis_58,msiis_55,msiis_56,msiis_53,msiis_54,gl_anomaly_87,gl_anomaly_86,gl_anomaly_89,packetbeat_84,gl_anomaly_88,gl_anomaly_83,packetbeat_82,gl-failures_96,gl_anomaly_82,packetbeat_81,gl-failures_93,gl_anomaly_85,packetbeat_80,gl-failures_94,gl_anomaly_84,gl_anomaly_81,gl_anomaly_80,msiis_51,msiis_52,msiis_50,gl_linux_metricbeat_86,gl_anomaly_9,msiis_48,gl_anomaly_8,msiis_49,msiis_46,msiis_47,msiis_44,msiis_45,msiis_43,gl_anomaly_94,gl_anomaly_93,gl_anomaly_95,gl_anomaly_90,gl_anomaly_92,gl_anomaly_91,gimness_ha_27,gimness_ha_26,msdns_1051,gl_linux_auditbeat_89,msdns_1050,gltrfc_18,msdns_1057,gltrfc_19,msdns_1056,gltrfc_16,msdns_1059,gltrfc_17,msdns_1058,gltrfc_14,msdns_1053,gltrfc_15,msdns_1052,gltrfc_12,msdns_1055,gltrfc_13,msdns_1054,gltrfc_21,gltrfc_22,gltrfc_20,gl_windows_sysmon_89,gl_windows_sysmon_88,msdns_1049,gl_windows_sysmon_87,gl_windows_sysmon_86,zk_444,zk_443,zk_442,zk_441,gimness_ha_31,zk_440,msdns_1040,glmongod_83,gl_windows_security_96,msdns_1046,msdns_1045,msdns_1048,glmongod_88,msdns_1047,msdns_1042,msdns_1041,msdns_1044,msdns_1043,gl_windows_security_91,gltrfc_10,gltrfc_11,zk_439,msdns_1039,zk_438,msdns_1038,zk_437,zk_436,zk_435,zk_434,zk_433,zk_432,zk_431,gl_windows_sysmon_91,gl_windows_sysmon_90,msdns_1035,msdns_1037,msdns_1036,gl-events_6,gl-events_1,gl-events_0/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.0 400 Bad Request]
{"error":{"root_cause":[{"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."}],"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."},"status":400}
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$singleSearch$1(ElasticsearchClient.java:77) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:109) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.singleSearch(ElasticsearchClient.java:77) ~[?:?]
		at org.graylog.storage.elasticsearch7.Scroll.scroll(Scroll.java:51) ~[?:?]
		at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.scrollEvents(MoreSearchAdapterES7.java:139) ~[?:?]
		at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
		at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:230) ~[graylog.jar:?]
		at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:125) ~[graylog.jar:?]
		at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
		at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:172) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:150) ~[graylog.jar:?]
		at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:150) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
		at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
		at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
		at java.lang.Thread.run(Thread.java:829) [?:?]
```

```
2022-10-12T14:52:55.431-05:00 ERROR [EventProcessorExecutionJob] Event processor <aggregation-v1/629e225798300f79487f0cb8> failed to execute: Couldn't create events for: EventDefinitionDto{id=629e225798300f79487f0cb8, title=Illuminate:Events:4;Windows:Detect weak kerberos ticket requests, description=Detect possible recon/kerberoasting activity. See MITRE ATT&CK technique T1202 https://attack.mitre.org/techniques/T1208/
This is a revised version of the event "Graylog Illuminate:Events:2;Windows:Detect weak kerberos ticket requests", updated to work with Illuminate 2.0.0 or later. Please replace "Graylog Illuminate:Events:2;Windows:Detect weak kerberos ticket requests" with this event once any modifications to that rule (scheduling, notifications, etc.) have been copied to this rule., priority=3, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=event_code:(4768 OR 4769 OR 4770) AND NOT windows_kerberos_ticket_encryption_type:(0x11 OR 0x12 OR "AES256-CTS-HMAC-SHA1-96" OR "AES128-CTS-HMAC-SHA1-96" OR "0xffffffff" OR "0xFFFFFFFF"), queryParameters=[], streams=[], groupBy=[], series=[], conditions=Optional[AggregationConditions{expression=Optional.empty}], searchWithinMs=660000, executeEveryMs=600000}, fieldSpec={event_source=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.event_source}, requireValues=false}]}, user_name=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.user_name}, requireValues=false}]}, windows_kerberos_ticket_encryption_type=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.windows_kerberos_ticket_encryption_type}, requireValues=false}]}}, keySpec=[event_source, user_name], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]} (retry in 5000 ms)
org.graylog.events.processor.EventProcessorException: Couldn't create events for: EventDefinitionDto{id=629e225798300f79487f0cb8, title=Illuminate:Events:4;Windows:Detect weak kerberos ticket requests, description=Detect possible recon/kerberoasting activity. See MITRE ATT&CK technique T1202 https://attack.mitre.org/techniques/T1208/
This is a revised version of the event "Graylog Illuminate:Events:2;Windows:Detect weak kerberos ticket requests", updated to work with Illuminate 2.0.0 or later. Please replace "Graylog Illuminate:Events:2;Windows:Detect weak kerberos ticket requests" with this event once any modifications to that rule (scheduling, notifications, etc.) have been copied to this rule., priority=3, alert=false, config=AggregationEventProcessorConfig{type=aggregation-v1, query=event_code:(4768 OR 4769 OR 4770) AND NOT windows_kerberos_ticket_encryption_type:(0x11 OR 0x12 OR "AES256-CTS-HMAC-SHA1-96" OR "AES128-CTS-HMAC-SHA1-96" OR "0xffffffff" OR "0xFFFFFFFF"), queryParameters=[], streams=[], groupBy=[], series=[], conditions=Optional[AggregationConditions{expression=Optional.empty}], searchWithinMs=660000, executeEveryMs=600000}, fieldSpec={event_source=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.event_source}, requireValues=false}]}, user_name=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.user_name}, requireValues=false}]}, windows_kerberos_ticket_encryption_type=EventFieldSpec{dataType=STRING, providers=[Config{type=template-v1, template=${source.windows_kerberos_ticket_encryption_type}, requireValues=false}]}}, keySpec=[event_source, user_name], notificationSettings=EventNotificationSettings{gracePeriodMs=0, backlogSize=0}, notifications=[], storage=[Config{type=persist-to-streams-v1, streams=[000000000000000000000002]}]}
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:106) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:172) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:150) ~[graylog.jar:?]
	at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:150) ~[graylog.jar:?]
	at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
	at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to perform scroll search
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:151) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:111) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.singleSearch(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.Scroll.scroll(Scroll.java:51) ~[?:?]
	at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.scrollEvents(MoreSearchAdapterES7.java:139) ~[?:?]
	at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:230) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:125) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
	... 12 more
Caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=too_long_http_line_exception, reason=An HTTP line is larger than 4096 bytes.]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
	at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$singleSearch$1(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:109) ~[?:?]
	at org.graylog.storage.elasticsearch7.ElasticsearchClient.singleSearch(ElasticsearchClient.java:77) ~[?:?]
	at org.graylog.storage.elasticsearch7.Scroll.scroll(Scroll.java:51) ~[?:?]
	at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.scrollEvents(MoreSearchAdapterES7.java:139) ~[?:?]
	at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:230) ~[graylog.jar:?]
	at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:125) ~[graylog.jar:?]
	at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
	... 12 more
	Suppressed: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:9200], URI [/custom_gim_haproxy_4,custom_gim_haproxy_5,custom_gim_haproxy_9,msdns_1084,msdns_1071,msdns_1070,msdns_1073,msdns_1072,msdns_1075,msdns_1074,msdns_1076,gl_paloalto_60,gl_paloalto_61,gl_paloalto_62,gl-system-events_2,gl_paloalto_63,gl-system-events_3,gl_paloalto_64,gl-system-events_0,gl_paloalto_65,gl-system-events_1,gl_paloalto_66,gl_paloalto_67,gl_paloalto_68,gl-system-events_4,gl_paloalto_69,gl-system-events_5,gl_anomaly_18,msdns_1060,gl_anomaly_17,msdns_1062,gl_anomaly_19,msdns_1061,gl_anomaly_14,gl_anomaly_13,gl_anomaly_15,gl_anomaly_10,msdns_1068,msdns_1067,gl_anomaly_12,gl_anomaly_11,msdns_1069,msdns_1064,msdns_1063,msdns_1066,msdns_1065,gl_paloalto_50,gl_paloalto_51,gl_linux_auditbeat_94,gl_paloalto_52,gl_paloalto_53,gl_paloalto_54,gl_paloalto_55,gl_paloalto_56,gl_linux_auditbeat_90,gl_paloalto_57,gl_paloalto_58,gl_paloalto_59,gl_anomaly_29,gl_paloalto_49,gl-failures_70,gl_anomaly_28,gl_anomaly_25,gl_anomaly_24,gl_anomaly_27,gl_anomaly_26,gl-failures_77,gl_anomaly_21,gl_anomaly_20,gl-failures_75,gl_anomaly_23,gl_anomaly_22,gl-failures_73,gl-failures_74,gl-failures_71,gl-failures_72,gl-failures_79,gl_paloalto_42,gl_paloalto_43,gl_paloalto_44,gl_paloalto_45,gl_paloalto_46,gl_paloalto_47,gl-failures_80,gl_paloalto_38,gl-failures_81,gl_anomaly_39,gl_paloalto_39,gl_anomaly_36,gl_anomaly_35,gl_anomaly_38,gl_anomaly_37,gl_o365_0,gl_anomaly_32,gl-failures_89,gl-failures_86,gl_anomaly_34,gl_anomaly_33,gl-failures_84,gl-failures_85,gl-failures_82,gl_anomaly_30,gl-failures_83,gl_paloalto_30,gl_paloalto_31,gl_paloalto_32,gl_paloalto_33,gl_paloalto_34,gl_paloalto_35,gl_paloalto_36,gl_paloalto_37,gl_paloalto_27,gl_paloalto_28,gl_paloalto_29,gl_anomaly_47,gl_anomaly_46,gl_anomaly_49,gl_anomaly_48,gl_anomaly_43,gl_anomaly_42,gl_anomaly_45,gl_anomaly_44,gl_anomaly_41,gl_anomaly_40,opsrch_87,gl_paloalto_20,gl_paloalto_21,gl_paloalto_22,gl_paloalto_23,opsrch_82,gl_paloalto_24,opsrch_83,gl_paloalto_25,gl_paloalto_26,graylog_2,gl_paloalto_16,gl_paloalto_17,gl_paloalto_18,gl_paloalto_19,gl_anomaly_58,gl_anomaly_57,gl_anomaly_59,gl_anomaly_54,gl-failures_67,gl_anomaly_53,gl_anomaly_56,gl_anomaly_55,gl_anomaly_50,gl_anomaly_52,gl_anomaly_51,gl_paloalto_3,gl_paloalto_4,gl_paloalto_5,gl_paloalto_6,gl_paloalto_7,gltrfc_5,gl_paloalto_8,gltrfc_6,gl_paloalto_9,gltrfc_3,gltrfc_4,gltrfc_9,gl_paloalto_10,gltrfc_7,gltrfc_8,gl_paloalto_12,gl_windows_common_96,gl_paloalto_13,gl_paloalto_2,glserver_89,gl_anomaly_69,gl_anomaly_68,custom_gim_pfsense_37,custom_gim_pfsense_38,gl_anomaly_65,gl_anomaly_67,gl_anomaly_66,gl_anomaly_61,gl_anomaly_60,gl_anomaly_63,glserver_85,gl_anomaly_79,gl_anomaly_76,gl_anomaly_75,gl_anomaly_78,gl_anomaly_77,gl_anomaly_72,gl_anomaly_71,gl_anomaly_74,custom_gim_pfsense_42,gl_anomaly_73,pf_45,gl_anomaly_70,gl_windows_sysmon_58,gl_windows_sysmon_55,msiis_62,msiis_60,msiis_61,msiis_59,gl-failures_92,gl_linux_metricbeat_82,msiis_57,gl-failures_90,msiis_58,msiis_55,msiis_56,msiis_53,msiis_54,gl_anomaly_87,gl_anomaly_86,gl_anomaly_89,packetbeat_84,gl_anomaly_88,gl_anomaly_83,packetbeat_82,gl-failures_96,gl_anomaly_82,packetbeat_81,gl-failures_93,gl_anomaly_85,packetbeat_80,gl-failures_94,gl_anomaly_84,gl_anomaly_81,gl_anomaly_80,msiis_51,msiis_52,msiis_50,gl_linux_metricbeat_86,gl_anomaly_9,msiis_48,gl_anomaly_8,msiis_49,msiis_46,msiis_47,msiis_44,msiis_45,msiis_43,gl_anomaly_94,gl_anomaly_93,gl_anomaly_95,gl_anomaly_90,gl_anomaly_92,gl_anomaly_91,gimness_ha_27,gimness_ha_26,msdns_1051,gl_linux_auditbeat_89,msdns_1050,gltrfc_18,msdns_1057,gltrfc_19,msdns_1056,gltrfc_16,msdns_1059,gltrfc_17,msdns_1058,gltrfc_14,msdns_1053,gltrfc_15,msdns_1052,gltrfc_12,msdns_1055,gltrfc_13,msdns_1054,gltrfc_21,gltrfc_22,gltrfc_20,gl_windows_sysmon_89,gl_windows_sysmon_88,msdns_1049,gl_windows_sysmon_87,gl_windows_sysmon_86,zk_444,zk_443,zk_442,zk_441,gimness_ha_31,zk_440,msdns_1040,glmongod_83,gl_windows_security_96,msdns_1046,msdns_1045,msdns_1048,glmongod_88,msdns_1047,msdns_1042,msdns_1041,msdns_1044,msdns_1043,gl_windows_security_91,gltrfc_10,gltrfc_11,zk_439,msdns_1039,zk_438,msdns_1038,zk_437,zk_436,zk_435,zk_434,zk_433,zk_432,zk_431,gl_windows_sysmon_91,gl_windows_sysmon_90,msdns_1035,msdns_1037,msdns_1036,gl-events_6,gl-events_1,gl-events_0/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.0 400 Bad Request]
{"error":{"root_cause":[{"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."}],"type":"too_long_http_line_exception","reason":"An HTTP line is larger than 4096 bytes."},"status":400}
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553) ~[?:?]
		at org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.lambda$singleSearch$1(ElasticsearchClient.java:77) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:109) ~[?:?]
		at org.graylog.storage.elasticsearch7.ElasticsearchClient.singleSearch(ElasticsearchClient.java:77) ~[?:?]
		at org.graylog.storage.elasticsearch7.Scroll.scroll(Scroll.java:51) ~[?:?]
		at org.graylog.storage.elasticsearch7.MoreSearchAdapterES7.scrollEvents(MoreSearchAdapterES7.java:139) ~[?:?]
		at org.graylog.events.search.MoreSearch.scrollQuery(MoreSearch.java:147) ~[graylog.jar:?]
		at org.graylog.events.processor.aggregation.AggregationEventProcessor.filterSearch(AggregationEventProcessor.java:230) ~[graylog.jar:?]
		at org.graylog.events.processor.aggregation.AggregationEventProcessor.createEvents(AggregationEventProcessor.java:125) ~[graylog.jar:?]
		at org.graylog.events.processor.EventProcessorEngine.execute(EventProcessorEngine.java:92) ~[graylog.jar:?]
		at org.graylog.events.processor.EventProcessorExecutionJob.execute(EventProcessorExecutionJob.java:115) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.executeJob(JobExecutionEngine.java:172) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.lambda$handleTrigger$2(JobExecutionEngine.java:150) ~[graylog.jar:?]
		at com.codahale.metrics.Timer.time(Timer.java:151) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.handleTrigger(JobExecutionEngine.java:150) ~[graylog.jar:?]
		at org.graylog.scheduler.JobExecutionEngine.lambda$execute$0(JobExecutionEngine.java:119) ~[graylog.jar:?]
		at org.graylog.scheduler.worker.JobWorkerPool.lambda$execute$0(JobWorkerPool.java:121) ~[graylog.jar:?]
		at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
		at java.lang.Thread.run(Thread.java:829) [?:?]
```

Example URI which is 4438 chars/bytes. I confirmed that deleting indices resolved these errors (i lowered the retention policy on several index sets from 90 (1/day) to 30.

`/custom_gim_haproxy_4,custom_gim_haproxy_5,custom_gim_haproxy_9,msdns_1084,msdns_1071,msdns_1070,msdns_1073,msdns_1072,msdns_1075,msdns_1074,msdns_1076,gl_paloalto_60,gl_paloalto_61,gl_paloalto_62,gl-system-events_2,gl_paloalto_63,gl-system-events_3,gl_paloalto_64,gl-system-events_0,gl_paloalto_65,gl-system-events_1,gl_paloalto_66,gl_paloalto_67,gl_paloalto_68,gl-system-events_4,gl_paloalto_69,gl-system-events_5,gl_anomaly_18,msdns_1060,gl_anomaly_17,msdns_1062,gl_anomaly_19,msdns_1061,gl_anomaly_14,gl_anomaly_13,gl_anomaly_15,gl_anomaly_10,msdns_1068,msdns_1067,gl_anomaly_12,gl_anomaly_11,msdns_1069,msdns_1064,msdns_1063,msdns_1066,msdns_1065,gl_paloalto_50,gl_paloalto_51,gl_linux_auditbeat_94,gl_paloalto_52,gl_paloalto_53,gl_paloalto_54,gl_paloalto_55,gl_paloalto_56,gl_linux_auditbeat_90,gl_paloalto_57,gl_paloalto_58,gl_paloalto_59,gl_anomaly_29,gl_paloalto_49,gl-failures_70,gl_anomaly_28,gl_anomaly_25,gl_anomaly_24,gl_anomaly_27,gl_anomaly_26,gl-failures_77,gl_anomaly_21,gl_anomaly_20,gl-failures_75,gl_anomaly_23,gl_anomaly_22,gl-failures_73,gl-failures_74,gl-failures_71,gl-failures_72,gl-failures_79,gl_paloalto_42,gl_paloalto_43,gl_paloalto_44,gl_paloalto_45,gl_paloalto_46,gl_paloalto_47,gl-failures_80,gl_paloalto_38,gl-failures_81,gl_anomaly_39,gl_paloalto_39,gl_anomaly_36,gl_anomaly_35,gl_anomaly_38,gl_anomaly_37,gl_o365_0,gl_anomaly_32,gl-failures_89,gl-failures_86,gl_anomaly_34,gl_anomaly_33,gl-failures_84,gl-failures_85,gl-failures_82,gl_anomaly_30,gl-failures_83,gl_paloalto_30,gl_paloalto_31,gl_paloalto_32,gl_paloalto_33,gl_paloalto_34,gl_paloalto_35,gl_paloalto_36,gl_paloalto_37,gl_paloalto_27,gl_paloalto_28,gl_paloalto_29,gl_anomaly_47,gl_anomaly_46,gl_anomaly_49,gl_anomaly_48,gl_anomaly_43,gl_anomaly_42,gl_anomaly_45,gl_anomaly_44,gl_anomaly_41,gl_anomaly_40,opsrch_87,gl_paloalto_20,gl_paloalto_21,gl_paloalto_22,gl_paloalto_23,opsrch_82,gl_paloalto_24,opsrch_83,gl_paloalto_25,gl_paloalto_26,graylog_2,gl_paloalto_16,gl_paloalto_17,gl_paloalto_18,gl_paloalto_19,gl_anomaly_58,gl_anomaly_57,gl_anomaly_59,gl_anomaly_54,gl-failures_67,gl_anomaly_53,gl_anomaly_56,gl_anomaly_55,gl_anomaly_50,gl_anomaly_52,gl_anomaly_51,gl_paloalto_3,gl_paloalto_4,gl_paloalto_5,gl_paloalto_6,gl_paloalto_7,gltrfc_5,gl_paloalto_8,gltrfc_6,gl_paloalto_9,gltrfc_3,gltrfc_4,gltrfc_9,gl_paloalto_10,gltrfc_7,gltrfc_8,gl_paloalto_12,gl_windows_common_96,gl_paloalto_13,gl_paloalto_2,glserver_89,gl_anomaly_69,gl_anomaly_68,custom_gim_pfsense_37,custom_gim_pfsense_38,gl_anomaly_65,gl_anomaly_67,gl_anomaly_66,gl_anomaly_61,gl_anomaly_60,gl_anomaly_63,glserver_85,gl_anomaly_79,gl_anomaly_76,gl_anomaly_75,gl_anomaly_78,gl_anomaly_77,gl_anomaly_72,gl_anomaly_71,gl_anomaly_74,custom_gim_pfsense_42,gl_anomaly_73,pf_45,gl_anomaly_70,gl_windows_sysmon_58,gl_windows_sysmon_55,msiis_62,msiis_60,msiis_61,msiis_59,gl-failures_92,gl_linux_metricbeat_82,msiis_57,gl-failures_90,msiis_58,msiis_55,msiis_56,msiis_53,msiis_54,gl_anomaly_87,gl_anomaly_86,gl_anomaly_89,packetbeat_84,gl_anomaly_88,gl_anomaly_83,packetbeat_82,gl-failures_96,gl_anomaly_82,packetbeat_81,gl-failures_93,gl_anomaly_85,packetbeat_80,gl-failures_94,gl_anomaly_84,gl_anomaly_81,gl_anomaly_80,msiis_51,msiis_52,msiis_50,gl_linux_metricbeat_86,gl_anomaly_9,msiis_48,gl_anomaly_8,msiis_49,msiis_46,msiis_47,msiis_44,msiis_45,msiis_43,gl_anomaly_94,gl_anomaly_93,gl_anomaly_95,gl_anomaly_90,gl_anomaly_92,gl_anomaly_91,gimness_ha_27,gimness_ha_26,msdns_1051,gl_linux_auditbeat_89,msdns_1050,gltrfc_18,msdns_1057,gltrfc_19,msdns_1056,gltrfc_16,msdns_1059,gltrfc_17,msdns_1058,gltrfc_14,msdns_1053,gltrfc_15,msdns_1052,gltrfc_12,msdns_1055,gltrfc_13,msdns_1054,gltrfc_21,gltrfc_22,gltrfc_20,gl_windows_sysmon_89,gl_windows_sysmon_88,msdns_1049,gl_windows_sysmon_87,gl_windows_sysmon_86,zk_444,zk_443,zk_442,zk_441,gimness_ha_31,zk_440,msdns_1040,glmongod_83,gl_windows_security_96,msdns_1046,msdns_1045,msdns_1048,glmongod_88,msdns_1047,msdns_1042,msdns_1041,msdns_1044,msdns_1043,gl_windows_security_91,gltrfc_10,gltrfc_11,zk_439,msdns_1039,zk_438,msdns_1038,zk_437,zk_436,zk_435,zk_434,zk_433,zk_432,zk_431,gl_windows_sysmon_91,gl_windows_sysmon_90,msdns_1035,msdns_1037,msdns_1036,gl-events_6,gl-events_1,gl-events_0/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true`

### PR DESCRIPTION
**Pull request by luk-kaminski**
…archAdapter.

## Description
MoreSearchAdapter used to use "scroll mechanism" to retrieve multi-chunk responses from the server.
The problem with this approach is that it is impossible to combine it with multiple indices' names (Error "An HTTP line is larger than 4096 bytes" will appear in this case).
Therefor it was necessary to replace "scroll mechanism" with "search after pagination", which, if built on top of multisearch, has no problems with multiple indices.

The code has been refactored, so that MoreSearchAdapter uses MultiChunkResultRetriever interface implementations, which include both search after pagination (set as default) and scroll(deprecated).

It is to be decided if scroll has to be removed from SearchesAdapters as well. So far no errors have been reported there.
Even if it is decided to do it there as well, it will be a subject of a separate PR, as this one has already grown to a huge change.

Fixes #12996.
Fixes #13675.

## Motivation and Context
It is necessary to fix #12996 and #13675 bugs. 

## How Has This Been Tested?
There have been a lack of tests in this area of the code.
New tests have been added. They test both old approach (scroll) and new approach (search-after), checking if they end up retrieving the same, correct results.

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4252

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationES7.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+        this.client = client;
+        this.searchRequestFactory = searchRequestFactory;
+    }
+
+    @Override
+    public ChunkedResult retrieveChunkedResult(final ChunkCommand chunkCommand) {
+        final SearchSourceBuilder searchQuery = searchRequestFactory.create(chunkCommand);
+        final SearchRequest request = buildSearchRequest(searchQuery, chunkCommand.indices());
+        final SearchResponse result = client.search(request, "Unable to perform search-after pagination search");
+        return new PaginationResultES7(client, request, result, searchQuery.toString(), chunkCommand.fields(), chunkCommand.limit().orElse(-1));
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationES7.java:45]: The query typed as String makes me think about alternatives. Could we type it somehow? I've seen that it's used mainly to compute an MD5 hash. But there is one usage where it's again used as query. What about at least wrapping it with a class, so we better communicate what we expect and how to use it?

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+                               @Assisted int limit) {
+        super(client, initialResult, query, fields, limit);
+        this.initialSearchRequest = initialSearchRequest;
+    }
+
+    @Override
+    protected SearchResponse nextSearchResult() throws IOException {
+        final SearchSourceBuilder initialQuery = initialSearchRequest.source();
+        final SearchHit[] hits = lastSearchResponse.getHits().getHits();
+        initialQuery.searchAfter(hits[hits.length - 1].getSortValues());
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java:47]: Can't we get out of range here?

File: graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/events/search/MoreSearchAdapterES7UsingPaginationIT.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    @Rule
+    public final ElasticsearchInstanceES7 elasticsearch = ElasticsearchInstanceES7.create();
+
+    @Override
+    protected SearchServerInstance searchServer() {
+        return elasticsearch;
+    }
+
+    @Override
+    protected MoreSearchAdapter createMoreSearchAdapter() {
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/events/search/MoreSearchAdapterES7UsingPaginationIT.java:41]: Move to Adapters helper maybe?

File: graylog2-server/src/main/java/org/graylog2/indexer/results/ChunkedQueryResult.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+                              int limit) {
+        super(query, null);
+        this.tookMs = getTookMillisFromResponse(initialResult);
+        this.client = client;
+        this.totalHits = countTotalHits(initialResult);
+        this.limit = limit;
+        this.initialResult = initialResult;
+        this.fields = fields;
+
+        final Md5Hash md5Hash = new Md5Hash(getOriginalQuery());
```
Comment (todvora) [inline graylog2-server/src/main/java/org/graylog2/indexer/results/ChunkedQueryResult.java:55]: Could it happen that we have two parallelly running jobs with the same query, mixing their paging results?

**Review by todvora — COMMENTED** [review]
Could you please help me to understand some details of the implementation? I have added some questions and suggestions. Thanks!

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java (hunk 2 above)
Comment (luk-kaminski) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java:50]: Because of `if (resultMessages.size() == 0) ` check in line 73 of ChunkedQueryResult class it does not cause any problems, but I have introduced additional check anyway, to be on the safe side.

Thanks once again!

File: graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/events/search/MoreSearchAdapterES7UsingScrollIT.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+    @Rule
+    public final ElasticsearchInstanceES7 elasticsearch = ElasticsearchInstanceES7.create();
+
+    @Override
+    protected SearchServerInstance searchServer() {
+        return elasticsearch;
+    }
+
+    @Override
+    protected MoreSearchAdapter createMoreSearchAdapter() {
```
[the remark this answers is not in the document]
Comment (todvora) [reply graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/events/search/MoreSearchAdapterES7UsingScrollIT.java:42]: You are right, let's keep it as it is :+1:

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java (hunk 2 above)
Comment (todvora) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java:50]: Awesome, thanks!

**Review by todvora — APPROVED** [review]
looks good to me, we have discussed all my questions and I think we can go ahead and merge the change now. Thanks @luk-kaminski !

**Review by dennisoelkers — APPROVED** [review]
