### PR TITLE
Copy widget title when copying widget to dashboard

### LINKED ISSUE #10003: Widgets copied to dashboard lose title
## Expected Behavior

A widget with a custom title keeps this title when it is copied to a dashboard.

## Current Behavior

The widget loses its title when copied to a dashboard.

## Steps to Reproduce (for bugs)

1. Go to search
2. Copy message histogram widget to dashboard
3. Check title of copied widget on dashboard

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by kmerz**
## Motivation
Prior to this change, the function which copys the widget from the
search to the dashboard was missing to copy the title if a title exists.

## Description
This change will add a function which will add a possible new title of
the new widget to the dashboard.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Fixes #10003

### CODE REVIEW

File: graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts [hunk 1]
```diff
@@ -21,24 +21,47 @@ import View from 'views/logic/views/View';
...
+  return GenerateNextPosition(Map(widgetPositionsMap), widgets.toArray());
+};
+
+const _newTitlesMap = (titlesMap, widget, title) => {
+  if (!title) {
+    return titlesMap;
+  }
+
+  const widgetTitles = titlesMap.get(TitleTypes.Widget);
+  const newWidgetTitles = widgetTitles.set(widget.id, title);
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts:46]: `widgetTitles` can be `undefined`. It should be initialized with an empty `Immutable.Map` if it is not present.

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
It looks good in general. When testing it on the default search, copying the `Message Count` widget to a dashboard, I get an exception. I have added an line comment for that.

**Review by dennisoelkers — APPROVED** [review]
Looks good, works well!
