### PR TITLE
Automatically unsubscribing from DecoratorsStore in SearchPage.

### LINKED ISSUE #3355: When decorator was added in search, seach returns no results
## Expected Behavior
When adding a decorator, the search results should update and show the search result set with the decorator applied.

## Current Behavior
When adding a decorator, the "Nothing found" element is shown.

## Steps to Reproduce (for bugs)

1. Go to "Search"
2. Add arbitrary decorator

## Your Environment

* Graylog Version: Graylog 2.2.0-rc.1-SNAPSHOT
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Before this change, every mount of the SearchPage component included
subscribing to several DecoratorsActions. During an unmount of the
component, no unsubscribing from the actions took place, leaving
dangling calls to a function of an unmounted component behind.

This PR changes the way these actions are subscribed to and uses Reflux
mechanisms to handle unsubscribing automatically.

Fixes #3355.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-web-interface/src/pages/SearchPage.jsx [hunk 1]
```diff
@@ -30,6 +30,7 @@ const SearchPage = React.createClass({
     Reflux.connect(CurrentUserStore),
     Reflux.listenTo(InputsStore, '_formatInputs'),
     Reflux.listenTo(RefreshStore, '_setupTimer', '_setupTimer'),
+    Reflux.listenTo(DecoratorsStore, '_refreshDataFromDecoratorStore', '_refreshDataFromDecoratorStore')
```
Comment (joschi) [inline graylog2-web-interface/src/pages/SearchPage.jsx]: Why are we using strings here instead of a function handle?

```javascript
Reflux.listenTo(DecoratorsStore, this._refreshDataFromDecoratorStore, this._refreshDataFromDecoratorStore);
```

Comment (dennisoelkers) [inline graylog2-web-interface/src/pages/SearchPage.jsx]: This is the [standard way of 0.2.x reflux](https://github.com/reflux/refluxjs/tree/v0.2.13#using-refluxlistento), unfortunately.

Comment (joschi) [inline graylog2-web-interface/src/pages/SearchPage.jsx]: Strange, the other examples on that page also use normal function references instead of strings.

But for the sake of conformity with the rest of our codebase, using single-quoted strings is fine.
