### PR TITLE
Fix reloading after notification changes

### LINKED ISSUE #3195: 2.2 UX/UI Improvement: Alerts - delete Notification from condition does no refresh
## Expected Behavior
If you look at the details of an alert condition you can **edit** or **delete** the notifications. After Edit or delete the page should be reloaded to reflect the new information.

## Current Behavior
Short notification appears at the bottom of the page and the page/information is not reloaded. You need to reload the page your self. 

When you edit the condition details the page is refreshed with the new settings for the condition but the notification stay in the old values/status.

## Steps to Reproduce (for bugs)
1. create condition for a stream
2. create notification for a stream
3. look at condition details page
4. change / delete Notifications

## Your Environment

* Graylog Version: Graylog 2.2.0-beta.2+7cda131 (OVA)
* Browser: Safari Version 10.0.1 (12602.2.14.0.7)

### PR DESCRIPTION
**Pull request by edmundoa**
Move decision of which data to load up the component hierarchy, fixing UI inconsistencies after editing or deleting alert notifications from the alert conditions page.

Fixes #3195 and #3235

### CODE REVIEW

File: graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx [hunk 1]
```diff
@@ -35,13 +37,21 @@ const AlertNotification = React.createClass({
 
   _onSubmit(data) {
     AlarmCallbacksActions.update(this.props.alertNotification.stream_id, this.props.alertNotification.id, data)
-      .then(() => AlertNotificationsActions.listAll());
+      .then(() => {
+        if (typeof this.props.onNotificationUpdate === 'function') {
```
Comment (bernd) [inline graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx]: Wouldn't a simple check for undefined/null be enough here since we specify the propTypes?

**Comment by bernd** [comment]
Please rebase against master to fix merge conflict. Thanks!

File: graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx (hunk 1 above)
Comment (edmundoa) [inline graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx]: We are very inconsistent with that, but I think it is safer to ensure it is a function when using it. The prop type check may not always be there (for instance if we ever enable the production mode in react), and it only logs a warning, so it will not prevent the function to be called, and the application would be broken in that case.

**Comment by edmundoa** [comment]
Rebased against master, thank you for reviewing!
