### PR TITLE
Fix styling differences for react select.

### LINKED ISSUE #6036: Event definition stream picker underneath other UI elements
## Expected Behavior
The dropdown in the video should render on top of the other UI elements.

## Current Behavior
The z-index seems wrong for the dropdown.

## Steps to Reproduce (for bugs)

 * Create a new event definition with a Filter/Aggregation processor.
 * Select stream dropdown.

alert-ui

## Context

Nada.

## Your Environment

* Graylog Version: 3.1.0 alert-definitions-ui on 100f35c78c61c981e7a85641d4eac926426817a0

### LINKED ISSUE #6040: Saved searches drop-down styling issue
## Description

The drop-down field for saved searches looks different in 3.1.0-SNAPSHOT than it looked like in 3.0.0. The field is bigger and thus isn't aligned with the surrounding elements anymore.

## Expected Behavior

image

## Current Behavior

image

## Context

The drop-down fields in other places also look different now. When creating a new lookup table the old drop-downs hat a height of 36px, now it's 38px. Looks like we have to globally change the styling after the react-select update to make it look similar to the version in Graylog 3.0 again.

## Your Environment

* Graylog Version: 3.1.0-SNAPSHOT (rev 511bebeb7)

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

During the migration from `react-select` v1 to v2 some styling differences were eliminated, but a lot were not. E.g.:

  * The dropdown caret looking different and taking up more space
  * Now having a separator between the dropdown indicator and the rest
  * Custom css fixes in `Select.css` were not taking effect anymore, due to the different classnames and generally a different way to customize styling, leading to:
    * z-index is not increased anymore
    * The `size` property for the component is not considered

This PR aims to remove these differences and make the component look and behave the same as before.

Fixes #6036.
Fixes #6040.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/Select.jsx [hunk 1]
```diff
@@ -208,17 +243,23 @@ class Select extends React.Component<Props, State> {
...
-      </div>
+      <SelectComponent {...rest}
+                       onChange={onReactSelectChange || this._onChange}
+                       isMulti={isMulti}
+                       isDisabled={isDisabled}
+                       getOptionLabel={option => option[displayKey]}
+                       getOptionValue={option => option[valueKey]}
+                       components={{
+                         ..._components,
+                         IndicatorsContainer: isMenuOpen ? IndicatorsContainerOpen : IndicatorsContainerClosed,
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/common/Select.jsx]: This may be able to be simpler and require less state management.
```
        DropdownIndicator: (base, state) => ({
            ...base,
            transform: state.selectProps.menuIsOpen && 'rotate(180deg)'
        })
```

File: graylog2-web-interface/src/components/common/Select.jsx [hunk 2]
```diff
@@ -173,6 +204,10 @@ class Select extends React.Component<Props, State> {
     onChange(value);
   };
 
+  _onMenuOpen = () => this.setState({ isMenuOpen: true });
+
+  _onMenuClose = () => this.setState({ isMenuOpen: false });
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/common/Select.jsx]: If we style the `DropdownIndicator` instead, we can just remove all this stuff.

File: graylog2-web-interface/src/components/common/Select.jsx [hunk 3]
```diff
@@ -4,16 +4,26 @@ import lodash from 'lodash';
...
-  return (
-    <Components.MultiValueRemove {...props}>
-      ×
-    </Components.MultiValueRemove>
-  );
-};
+
+const MultiValueRemove = props => (
+  <Components.MultiValueRemove {...props}>
+    ×
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/common/Select.jsx]: Should we use the HTML encoded `&times;`?

File: graylog2-web-interface/src/components/common/Select.jsx (hunk 1 above)
Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/Select.jsx]: I was looking for something like that, but the `state` object is empty in both the `IndicatorsContainer` and the `DropdownIndicator` component :/

Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/Select.jsx]: Thanks! I was looking for something like that, but looked in the component, which does not receive the state. It is way better now!

File: graylog2-web-interface/src/components/common/Select.jsx (hunk 2 above)
Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/Select.jsx]: ✅

File: graylog2-web-interface/src/components/common/Select.jsx (hunk 3 above)
Comment (dennisoelkers) [reply graylog2-web-interface/src/components/common/Select.jsx]: ✅

**Comment by kyleknighted** [comment]
LGTM good to merge once we get the CI 💚
