### PR TITLE
Remove field that was added by error to group_by for event replay

### LINKED ISSUE #19862: Aggregation widget on 'Replay search' page incorrectly fields to group by even though the field is not specified in group by
Best to describe with pictures:

The follow Event Definition aggregation criteria:
image

Generates the following aggregation widget when using 'Replay Search':
image

This is incorrect however, and should be displayed as:
image
image

To be clear, the event is working correctly and as expected, but the 'replay search' is incorrect.

## Expected Behavior

Replay search correctly match event definition.

## Current Behavior

Aggregation widget on 'Replay search' page incorrectly fields to group by even though the field is not specified in group by

## Steps to Reproduce (for bugs)

1. Create an event definition that is similar to the one shown here. It is important that a field be specified in 'Group by Fields' in the event definition

I have reproduced this both in Graylog 5.2 and 6.0 (did not test older versions)

## Context

Reported by a customer.

## Your Environment

* Graylog Version: 6.0.4
* Java Version: Bundled
* OpenSearch Version: 2.15.0
* MongoDB Version: 6.0.16
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 126.0.6478.127 (Official Build) (arm64)

Plese let me know if there are any questions.

### PR DESCRIPTION
**Pull request by janheise**
## Description

When running the event-replay function, fields were added to the group_by that were not supposed to be added there and resulted in a aggregation widget that did not show the correct results.

fixes #19862 

## How Has This Been Tested?

manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by maxiadlovskii — COMMENTED** [review]
It doesn't fix an issue when we have 2 or more conditions. There is a summary widget it has to be fixed as well

File: graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts [hunk 1]
```diff
@@ -82,8 +82,8 @@ const createViewPosition = ({ index, SUMMARY_ROW_DELTA }) => {
   return new WidgetPosition(col, row, AGGREGATION_WIDGET_HEIGHT, 6);
 };
 
-const createViewWidget = ({ field, groupBy, fnSeries, expr }) => {
-  const uniqPivotFields = uniq([field, ...groupBy].filter((v) => !!v));
+const createViewWidget = ({ groupBy, fnSeries, expr }: { groupBy: Array<string>; fnSeries; expr }) => {
```
Comment (maxiadlovskii) [inline graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts:85]: Could you please also add types for fnSeries; expr ?

File: graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts [hunk 2]
```diff
@@ -94,10 +94,9 @@ const createViewWidget = ({ field, groupBy, fnSeries, expr }) => {
 
 const getSummaryAggregation = ({ aggregations, groupBy }) => {
   const { summaryFnSeries, summaryRowPivots, summaryTitle } = aggregations.reduce(
-    (res, { field, value, expr, fnSeries }) => {
+    (res, { value, expr, fnSeries }) => {
       const concatTitle = `${fnSeries} ${expr} ${value}`;
       res.summaryFnSeries.push(fnSeries);
-      if (field) res.summaryRowPivots.push(field);
```
Comment (maxiadlovskii) [inline graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts:100]: we can remove summaryRowPivots from reduce. 
then we can also remove it from `rowPivots: [pivotForField(uniq([...summaryRowPivots, ...groupBy]), new FieldType('value', [], []))],`

**Review by maxiadlovskii — APPROVED** [review]
