### PR TITLE
Fix various Formatting and styling issue

### LINKED ISSUE #9447: Text formatting and styling issues
## Description

I collected a few styling and formatting issues that I noticed in the product.

### Lookup Data Adapter Details

image

### System / Indices

image

### Node Overview

image

### Node Metrics

image

### Input Metrics

image

### Index Set Configuration

image

### Pipeline Editor with dark theme

I personally find the dark blue color in the syntax highlighting a bit hard to read on the dark background:

image

## Your Environment

* Graylog Version: 4.0.0-rc.1

### PR DESCRIPTION
**Pull request by ousmaneo**
These changes fix various formatting and styling issues. 

Fix #9447

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/theme/GlobalThemeStyles.jsx [hunk 1]
```diff
@@ -254,28 +254,8 @@ const GlobalThemeStyles = createGlobalStyle(({ theme }) => css`
     margin-bottom: 15px !important;
   }
 
-  dl.metric-def dt {
-    float: left;
-  }
-
```
Comment (kyleknighted) [inline graylog2-web-interface/src/theme/GlobalThemeStyles.jsx:260]: 🥰

File: graylog2-web-interface/src/theme/GlobalThemeStyles.jsx [hunk 2]
```diff
@@ -254,28 +254,8 @@ const GlobalThemeStyles = createGlobalStyle(({ theme }) => css`
...
-  dl.metric-gauge dd {
-    margin-left: 80px;
-  }
-
-  dl.metric-counter dd {
-    margin-left: 80px;
-  }
-
-  dl.metric-histogram dd {
-    margin-left: 125px;
```
Comment (kyleknighted) [inline graylog2-web-interface/src/theme/GlobalThemeStyles.jsx:278]: 😍

File: graylog2-web-interface/src/theme/GlobalThemeStyles.jsx [hunk 3]
```diff
@@ -345,14 +325,6 @@ const GlobalThemeStyles = createGlobalStyle(({ theme }) => css`
...
   }
 
-  .system-system dt {
-    float: left;
-  }
-
-  .system-system dd {
-    margin-left: 75px;
-  }
-
```
Comment (kyleknighted) [inline graylog2-web-interface/src/theme/GlobalThemeStyles.jsx:355]: Love seeing all this red in the global styles file

File: graylog2-web-interface/src/components/indices/StyledIndexSetDetailsRow.tsx [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+ *
+ * You should have received a copy of the Server Side Public License
+ * along with this program. If not, see
+ * <http://www.mongodb.com/licensing/server-side-public-license>.
+ */
+import styled from 'styled-components';
+
+import { Row } from 'components/graylog';
+
+const StyledIndexSetDetailsRow = styled(Row)`
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/indices/StyledIndexSetDetailsRow.tsx:21]: Something we should all discuss as a team, I don't mind having all the styles in their own specific file, but I want to make sure the whole team is onboard and we have a specific naming structure and some defined "conventions" (`IndexSetDetails.styles.tsx` maybe so related styles stay with their component)

Currently, styles have just been defined within the component file itself.

File: graylog2-web-interface/src/components/metrics/MetricDetails.jsx [hunk 5]
```diff
@@ -14,67 +14,106 @@
  * along with this program. If not, see
  * <http://www.mongodb.com/licensing/server-side-public-license>.
  */
+// @flow strict
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/metrics/MetricDetails.jsx:17]:
```suggestion
```

File: graylog2-web-interface/src/components/metrics/MetricDetails.jsx [hunk 6]
```diff
@@ -14,67 +14,106 @@
...
+   }
+ }
 
-    return (
-      <div className="metric">
-        <h3>{type}</h3>
+ render() {
+   const { nodeId, metric, metric: { full_name: metricName }, metrics } = this.props;
+   const currentMetric = metrics && metrics[nodeId] && metrics[nodeId][metricName]
+     ? metrics[nodeId][metricName] : metric;
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/metrics/MetricDetails.jsx:97]: I know this was there when you got here, but do you think there is a clearer way to write this conditional?

Maybe this would work?

```suggestion
   const currentMetric = metrics?.[nodeId]?.[metricName] ?? metric;
```

File: graylog2-web-interface/src/components/lookup-tables/ConfigSummaryDefinitionListWrapper.tsx [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+    dt {
+      float: left;
+      clear: left;
+    }
+
+    dd {
+      margin-left: 185px;
+      word-wrap: break-word;
+
+      &:not(:last-child) {
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/lookup-tables/ConfigSummaryDefinitionListWrapper.tsx:32]: Ampersand isn't necessary in this instance.

```suggestion
      :not(:last-child) {
```

**Review by kyleknighted — CHANGES_REQUESTED** [review]
A few notes on the code. Have not test driven yet, will leave any followup UI concerns as comments with screenshots. Thanks for tackling this!!

File: graylog2-web-interface/src/components/lookup-tables/ConfigSummaryDefinitionListWrapper.tsx (hunk 7 above)
Comment (ousmaneo) [reply graylog2-web-interface/src/components/lookup-tables/ConfigSummaryDefinitionListWrapper.tsx]: 👍

File: graylog2-web-interface/src/components/metrics/MetricDetails.jsx (hunk 6 above)
Comment (ousmaneo) [reply graylog2-web-interface/src/components/metrics/MetricDetails.jsx]: This works ! Thanks

File: graylog2-web-interface/src/theme/GlobalThemeStyles.jsx (hunk 3 above)
Comment (ousmaneo) [reply graylog2-web-interface/src/theme/GlobalThemeStyles.jsx:355]: Me too 😉

**Comment by kyleknighted** [comment]
On `/system/indices` could we jump to the stacked format a bit sooner?
image
image

**Comment by kyleknighted** [comment]
Maybe we need to generate different colors for when the line is highlighted, or dark mode needs a lighter color for the active line. 

image

**Comment by ousmaneo** [comment]
Yes, I'm not happy with this one too. I will try a lighter one or generate another one

**Review by kyleknighted — APPROVED** [review]
LGTM!
