### PR TITLE
Do not allow selecting same pipeline stage twice

### LINKED ISSUE #6806: Changing a pipeline stage to an existing one deletes that stage
In a pipeline rule, if you change the stage number to one which already exists then the rule you change vanishes.

## Expected Behavior
Manually changing the rule stage to an existing one should either 
1) Replace the stage number, shifting the previous stage down(and all subsequent stages down) 
or
2) Merge the stages together

## Current Behavior
The overlapping stage and all associated rules are dropped/vanished.

## Possible Solutions
Raise an error on "Already existing stage"
Allow overwrite with confirmation
Use visual representation to re-arrange stage orders
Merge existing stage rules and newly-assigned stage rules.
Prompt the user for preferred action

## Steps to Reproduce (for bugs)
1. Create pipeline stages 1, 2, 3. Assign rules to them.
2. Edit stage 3, change the stage priority to 2.
3. Stage 3 "vanishes"

## Context
I was starting to tweak and re-order some of my pipeline stages.

* Graylog Version: 3.1.2

### PR DESCRIPTION
**Pull request by edmundoa**
Check if selected stage number already exists in pipeline, displaying an error in that case and not allowing to submit the form. This will prevent users of accidentally overriding one of their existing stages.

Additionally improve the initial suggestion for new stages. Before we always displayed `0` when creating a stage, now we base that value in the existing stages for the pipeline.

Fixes #6806

Backport of #9911 for 4.0

### CODE REVIEW

File: graylog2-web-interface/src/components/pipelines/StageForm.jsx [hunk 1]
```diff
@@ -93,11 +90,6 @@ const StageForm = createReactClass({
 
   _saved() {
```
Comment (ousmaneo) [inline graylog2-web-interface/src/components/pipelines/StageForm.jsx:91]: For the saving if I override a stage number I'm still able to save. there is small part of the code is master that dealt with checking `isOverridingStage` that is missing here.

**Review by ousmaneo — CHANGES_REQUESTED** [review]
Hi thank you for the back port, It works apart from a small thing below.

File: graylog2-web-interface/src/components/pipelines/StageForm.jsx (hunk 1 above)
Comment (edmundoa) [reply graylog2-web-interface/src/components/pipelines/StageForm.jsx:91]: Good catch! I will fix it 👍

**Review by ousmaneo — APPROVED** [review]
Legit
