### PR TITLE
Fix/14234 14238 lut

### LINKED ISSUE #14234: Lookup Table/caches/data adapter pages show spinner when filter returns no matches
## Expected Behavior

When searching for a lookup table/cache/data adapter, an empty table should be shown when no lookup table matches the filter.

## Current Behavior

A spinner (`Loading caches`) is shown.

lookup-tables

A quick glance into the code indicated it is most probably related to #14113.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### LINKED ISSUE #14238: Unable to delete lookup table cache
## Expected Behavior

Deleting a lookup table cache should remove it.

## Current Behavior

A error notification is shown with a cache id of `undefined`.

image

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by zeeklop**
Fixes for:
1. Delete caches.
2. Show no results message on empty search result.
3. Keep page size when searching and / or resetting search

Fixes #14234.
Fixes #14238.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
Thanks for fixing this!

It looks way better now, but I am still experiencing issues with caching search filters/responses. When entering a filter on the caches page, switching to any of the other pages and back removes the filter from the search box, but still shows the results:

image

File: graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.tsx [hunk 1]
```diff
@@ -80,16 +80,16 @@ const CacheTableEntry = ({ cache }: Props) => {
     return `${NumberUtils.formatNumber(hitRate)}%`;
   };
 
-  const handleEdit = (cacheName: string) => () => {
-    history.push(Routes.SYSTEM.LOOKUPTABLES.CACHES.edit(cacheName));
+  const handleEdit = () => {
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.tsx:83]: Can you wrap this with a `useCallback`? This way the function is not regenerated on each render.

File: graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.tsx [hunk 2]
```diff
@@ -80,16 +80,16 @@ const CacheTableEntry = ({ cache }: Props) => {
...
+    history.push(Routes.SYSTEM.LOOKUPTABLES.CACHES.edit(cache.name));
   };
 
-  const handleDelete = (inCache: LookupTableCache) => {
+  const handleDelete = () => {
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.tsx:87]: Can you wrap this with a `useCallback`? This way the function is not regenerated on each render.

File: graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx [hunk 3]
```diff
@@ -83,70 +86,103 @@ type Props = {
...
-  }, [resetPage, currentPage, currentPageSize]);
+    localPagination.resetPage();
+    localPagination.setPagination({ page: 1, pageSize: localPagination.currentPageSize });
+    setLocalPagination({ ...localPagination, currentPage: 1, currentQuery: '' });
+  }, [localPagination]);
 
-  const emptyListComponent = pagination.query === ''
-    ? (<NoEntitiesExist>No Cache exist.</NoEntitiesExist>)
-    : (<NoSearchResult>No Cache found.</NoSearchResult>);
+  const getComponent = () => {
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx:121]: This inline function behaves and is used like a React component. I think we should extract this into a component that is defined outside of the body of the `CachesOverview` component to make use of React's reconciliation mechanism.

File: graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx [hunk 4]
```diff
@@ -83,70 +86,103 @@ type Props = {
...
+    switch (true) {
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/components/lookup-tables/CachesOverview.tsx:122]: I do understand what you want to do with this, but it is a very uncommon pattern. I think we should turn this into idiomatic `if`-blocks, like this:

```
if (loading) {
  return <Spinner ... />;
}
if (caches.length === 0 && !localPagination.currentQuery) {
...
```

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
Thanks for fixing this! Functionality-wise it behaves now as expected. I added some suggestions for improvement inline. Some of them (for the internal structure of the `CachesOverview` component can also be applied to the `DataAdaptersOverview` component.

**Review by dennisoelkers — APPROVED** [review]
Looks good now, thanks! :)
