### PR TITLE
Fixes for content packs

### LINKED ISSUE #5114: Content pack entity selection should support clicking on titles
## Expected Behavior

When using the content pack creation wizard a click on an entity title or the section header (e.g. Grok Patterns) should trigger the selection.

image

## Current Behavior

The user can only select entities by clicking the check box.

## Your Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT (rev 0dbe6f659)

### LINKED ISSUE #5115: Fix alignment in content pack install dialog
The "Entity List" header in the content pack installation dialog is not aligned with the headers above.

image

## Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT (rev 0dbe6f659)

### PR DESCRIPTION
**Pull request by kmerz**
## Description
Small fixes regarding content packs.

## Motivation and Context
* Allign Install form fields

  The install form has a list of entities
  which were unallgined to the form fields.
  Fixes #5115

* Fix closing of ContentPackEditParameter modal
    
   the modal did not close since it was a child of
   the open button. A click on the close button bubbled up
   to the open button which would than reopen the closed
   modal. 
   I moved out the modal as a child from the open button.

* Make click on ExpandleListItem select checkbox
   
   We do not have label and checkboxes, since we do not have
   ids for the ExpandleListItem. There for I add an click
   handler to the header which will click on the
   associated checkbox.  
   Fixes #5114 

## Screenshots (if appropriate):
graylog - content packs 2

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-web-interface/src/components/common/ExpandableListItem.jsx [hunk 1]
```diff
@@ -88,6 +88,7 @@ class ExpandableListItem extends React.Component {
   render() {
     const { expanded } = this.state;
     const { checked, expandable, selectable, header, subheader, children, ...otherProps } = this.props;
+    const headerToRender = selectable ? (<span role="button" tabIndex={0} onClick={() => { this._checkbox.click(); }}>{header}</span>) : header;
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/common/ExpandableListItem.jsx]: I think we should move the callback function out of the render method. This [creates an additional function on every render](https://reactjs.org/docs/faq-functions.html#bind-in-render), and we will have to render and re-render many `ExpandableListItem` components.

Comment (kmerz) [reply graylog2-web-interface/src/components/common/ExpandableListItem.jsx]: Good catch :+1:
