### PR TITLE
Hotfix for never-expiring session validity #12220

### LINKED ISSUE #12220: Can't log in with "sessions do not timeout" option
Can't log in if I configure the _sessions do not timeout_ option. When I re-activate the session timeouts again all is working as expected. 

image

## Expected Behavior
I should be able to log in and the session should be valid forever. 

## Current Behavior
Login is not possible

## Steps to Reproduce (for bugs)
1. Go to user administration
2. Check the session do not timeout checkbox 
3. Logout
4. Try to log-in again.

## Your Environment

* Graylog Version: Graylog 4.3.0-SNAPSHOT+01253df on server (Eclipse Adoptium 17.0.2 on Linux 5.11.0-1028-aws)

### PR DESCRIPTION
**Pull request by todvora**
With the implementation of the cookie auth in #11788 we encountered a bug #12220 that prevents log-in for never expiring sessions. 

Cookies generally don't allow unlimited TTL, they always require a `maxAge` value. The common workaround is to set this value to the very distant future. This PR does exactly that - for never-expiring session configuration it sets the cookie to be valid for 10 years from the moment of login. It's rather a workaround and we should think about removing the non-expiring functionality generally, as we can't implement it correctly.

## Motivation and Context
Fixes #12220 

## How Has This Been Tested?
**TODO** add an integration test!

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/DefaultSessionResponseFactory.java [hunk 1]
```diff
@@ -48,7 +49,11 @@ public SessionResponse forSession(Session session) {
     }
 
     protected Date getValidUntil(Session session) {
-        return new DateTime(session.getLastAccessTime(), DateTimeZone.UTC).plus(session.getTimeout()).toDate();
+        if(session.getTimeout() < 0) { // means "session never expires", which is not possible in cookie-based auth
```
Comment (Corlobin) [inline graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/DefaultSessionResponseFactory.java:52]: Maybe add a space between if and `(`
```suggestion
        if (session.getTimeout() < 0) { // means "session never expires", which is not possible in cookie-based auth
```

**Review by thll — APPROVED** [review]
Straight-forward and fixes the issue 👍

**Review by linuspahl — APPROVED** [review]
