### PR TITLE
Fix display of very small percentage values.

### LINKED ISSUE #21185: Very small percentage value incorrectly displayed as `NaN%` in aggregation
## Expected Behavior

Percentages should always be numeric, and extremely small percentages should be some formatting of zero.

## Current Behavior

When putting together an aggregation where a certain value was essentially `0%` (`2.744906525058769E-8`), it was displayed as `NaN%`.

Image

## Steps to Reproduce (for bugs)

1. Have an aggregation with percentages included, where one of the values is essentially zero
2. Note `NaN%` for the value with a very small percentage

## Context

Not a major issue, but this seems likely to show up whenever there are major outliers / edge cases.

## Your Environment

* Graylog Version: `6.1.4`
* Browser version: Firefox `133`

### PR DESCRIPTION
**Pull request by dennisoelkers**
**Note:** This needs a backport to `6.0` & `6.1`.

## Motivation and Context

This PR is fixing an issue where very small values are displayed as `NaN%` in aggregation widgets. This is related to a bug in the underlying library used for formatting numbers. Due to this library being abandoned, this PR is starting to implement an abstraction layer that utilizes the Intl API to format numbers.

Replacing all previous usages of `numeral` with it is too much for a bugfix PR that is supposed to be backported, but will be handled through follow-up PRs instead.

Fixes #21185.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/util/NumberFormatting.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  maximumFractionDigits: 2,
+} as const;
+
+const defaultPercentageOptions = {
+  ...defaultOptions,
+  style: 'percent',
+} as const;
+
+export const formatNumber = (num: number, options: Options = {}) => new Intl.NumberFormat(undefined, { ...defaultOptions, ...options }).format(num);
+export const formatPercentage = (num: number, options: Options = {}) => new Intl.NumberFormat(undefined, { ...defaultPercentageOptions, ...options }).format(num);
```
Comment (maxiadlovskii) [inline graylog2-web-interface/src/util/NumberFormatting.ts:33]: Doesn't it make sense to put `minimumFractionDigits: 2 `as a default option? Or do we have different use cases?

Comment (dennisoelkers) [reply graylog2-web-interface/src/util/NumberFormatting.ts:34]: :white_check_mark:

**Review by maxiadlovskii — APPROVED** [review]
