### PR TITLE
do not let LDAP referral exception bubble out, this prevented authent…

### LINKED ISSUE #1410: Active Directory User Lookup fails
I know we are using LDAP referrals at our site, ist by any chance not yet supported in the apache ldap client library ?

The test connection works fine, but I am unable to actually lookup any users. I double checked baseDN and search pattern, they're fine.

**Update**: Login was actually successfull, but the LDAP Settings page fails to test for users. This is not a dramatic bug, but very misleading.

```
2015-09-10T01:49:46.782+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.RuntimeException: ERR_02002_FAILURE_ON_UNDERLYING_CURSOR Failure on underlying Cursor.
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:86)
        at org.graylog2.security.ldap.LdapConnector.search(LdapConnector.java:127)
        at org.graylog2.rest.resources.system.ldap.LdapResource.testLdapConfiguration(LdapResource.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
        at org.graylog2.jersey.container.netty.NettyContainer.messageReceived(NettyContainer.java:356)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
        at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at org.jboss.netty.handler.execution.MemoryAwareThreadPoolExecutor$MemoryAwareRunnable.run(MemoryAwareThreadPoolExecutor.java:606)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.directory.api.ldap.model.cursor.CursorLdapReferralException
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:164)
        at org.apache.directory.ldap.client.api.EntryCursorImpl.get(EntryCursorImpl.java:50)
        at org.apache.directory.api.ldap.model.cursor.CursorIterator.next(CursorIterator.java:80)
        ... 34 more
```

Happens with graylog 1.2.0-4.rc.4

### PR DESCRIPTION
**Pull request by kroepke**
…icated users from logging if their groups could not be resolved

  - the user was fine, but group mapping is not possible in this scenario until we figure out how to support LDAP referrals
  - group mapping can be done manually, warning log message links to proper documentation page

 fixes #1410

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java [hunk 1]
```diff
@@ -298,15 +298,13 @@ public Response updateGroupMappingSettings(@ApiParam(name = "JSON body", require
...
-                                                                ldapSettings.getGroupIdAttribute()
+        try (LdapNetworkConnection connection = ldapConnector.connect(config)) {
+            return ldapConnector.listGroups(connection,
+                                            ldapSettings.getGroupSearchBase(),
+                                            ldapSettings.getGroupSearchPattern(),
+                                            ldapSettings.getGroupIdAttribute()
             );
-            return groups;
-        } catch (LdapException e) {
+        } catch (IOException | LdapException e) {
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java]: Would it make sense to catch `Exception` here?

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java [hunk 2]
```diff
@@ -298,15 +298,13 @@ public Response updateGroupMappingSettings(@ApiParam(name = "JSON body", require
...
             LOG.error("Unable to retrieve available LDAP groups", e);
             throw new InternalServerErrorException(e);
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java]: If the exception contained a message, the user would see it on the REST API and could act accordingly. This way only a generic HTTP Status 500 response is being generated (also see our `WebApplicationExceptionMapper`).

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java [hunk 3]
```diff
@@ -251,6 +253,12 @@ public LdapEntry search(LdapNetworkConnection connection,
                     }
                 }
             }
+        } catch (Exception e) {
+            LOG.warn(
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: I'm a little bit uneasy about just swallowing the exception. Could we at least create a system notification as well so that people who don't parse the Graylog logs every day will have an idea that something went wrong?

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java (hunk 1 above)
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java]: Possibly, but there are no other exceptions from those two lines, so that's probably not necessary

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java (hunk 2 above)
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java]: Good point!

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java (hunk 3 above)
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: I'm not so sure about the system notification, because this gets triggered every time someone logs in.
People will notice really quickly that something is wrong, because group mapping is not working for any user.

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java (hunk 1 above)
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java]: :white_check_mark:

File: graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java (hunk 3 above)
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: There can only be 1 active system notification of a type, so this wouldn't swamp the administrator with notifications.

Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java]: System notification omitted for now.
