### PR TITLE
Avoid noisy stack traces when Elasticsearch is not available

### LINKED ISSUE #3861: Noisy startup when elasticsearch is unavailable
With the new HTTP client the server startup is logging very noisily when elasticsearch isn't reachable:

<details>

```

2017-05-22 15:15:14,349 ERROR: org.graylog2.periodical.BatchedElasticSearchOutputFlushThread - Caught exception while trying to flush output: {}
org.graylog2.indexer.ElasticsearchException: Couldn't check connection status of Elasticsearch
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:59) ~[classes/:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:70) ~[classes/:?]
	at org.graylog2.indexer.cluster.Cluster.isConnected(Cluster.java:165) ~[classes/:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.forceFlushIfTimedout(BlockingBatchedESOutput.java:148) ~[classes/:?]
	at org.graylog2.periodical.BatchedElasticSearchOutputFlushThread.doRun(BatchedElasticSearchOutputFlushThread.java:82) [classes/:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: io.searchbox.client.config.exception.CouldNotConnectException: Could not connect to http://127.0.0.1:9200
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70) ~[jest-2.4.5.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:54) ~[classes/:?]
	... 12 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:9200 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar:4.5.3]
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:132) ~[jest-2.4.5.jar:?]
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67) ~[jest-2.4.5.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:54) ~[classes/:?]
	... 12 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_121]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar:4.5.3]
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:132) ~[jest-2.4.5.jar:?]
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67) ~[jest-2.4.5.jar:?]
	at org.graylog2.indexer.cluster.jest.JestUtils.execute(JestUtils.java:54) ~[classes/:?]
	... 12 more
```

</details>

For this type of error it should be enough to log single lines. Previous version have also eventually failed the graylog server start, but I'm not sure if we still want that behavior.

### PR DESCRIPTION
**Pull request by bernd**
Only log stack traces if debug logging is enabled.

Closes #3861 

Especially `Cluster#isConnectec()` should not log anything if Elasticsearch is not reachable.

A starting/running Graylog server without Elasticsearch logs only this instead of pages of stack traces now.

```
2017-06-23 14:32:47,783 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*, emails_*, yolo_*] (Could not connect to http://127.0.0.1:9200)
2017-06-23 14:32:47,783 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-06-23 14:33:17,788 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*, emails_*, yolo_*] (Could not connect to http://127.0.0.1:9200)
2017-06-23 14:33:17,788 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-06-23 14:33:17,942 WARN : org.graylog2.migrations.V20161130141500_DefaultStreamRecalcIndexRanges - Interrupted or timed out waiting for Elasticsearch cluster, checking again.
2017-06-23 14:33:27,804 ERROR: org.graylog2.alerts.AlertScanner - Skipping alert check <yolo/2fa6a415-ce0c-4a36-accc-dd9519eb06d9>: Unable to perform count query. (ElasticsearchException)
2017-06-23 14:33:47,786 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*, emails_*, yolo_*] (Could not connect to http://127.0.0.1:9200)
2017-06-23 14:33:47,787 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
2017-06-23 14:34:17,787 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*, emails_*, yolo_*] (Could not connect to http://127.0.0.1:9200)
2017-06-23 14:34:17,787 INFO : org.graylog2.periodical.IndexerClusterCheckerThread - Indexer not fully initialized yet. Skipping periodic cluster check.
```

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java [hunk 1]
```diff
@@ -155,9 +165,16 @@ public boolean isConnected() {
...
-        final JestResult result = JestUtils.execute(jestClient, request, () -> "Couldn't check connection status of Elasticsearch");
-        final int numberOfDataNodes = result.getJsonObject().path("number_of_data_nodes").asInt();
-        return numberOfDataNodes > 0;
+        try {
+            final JestResult result = JestUtils.execute(jestClient, request, () -> "Couldn't check connection status of Elasticsearch");
+            final int numberOfDataNodes = result.getJsonObject().path("number_of_data_nodes").asInt();
+            return numberOfDataNodes > 0;
+        } catch (ElasticsearchException e) {
+            if (LOG.isDebugEnabled()) {
+                LOG.error(e.getMessage(), e);
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java]: Wrong log level?

Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java]: This was intentional. The idea was to only show the error if debugging is enabled so it's easier to identify the log message is an error.

Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java]: ✅
