### PR TITLE
Provide default stage for new pipeline

### LINKED ISSUE #11141: Creating a new Pipeline is broken
## Expected Behavior
Should create a pipeline rule.

## Current Behavior
After clicking on `Save` in the pipeline creation form you get following stacktrace on the console:
```
SourceGenerator.js:22 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at SourceGenerator.js:22
    at Array.forEach (<anonymous>)
    at Object.generatePipeline (SourceGenerator.js:21)
    at Object._savePipeline (PipelineDetailsPage.jsx:111)
    at _onChange (NewPipeline.tsx:41)
    at _handleSubmit (PipelineForm.tsx:72)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
    at executeDispatch (react-dom.development.js:389)
    at executeDispatchesInOrder (react-dom.development.js:414)
    at executeDispatchesAndRelease (react-dom.development.js:3278)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:3287)
    at forEachAccumulated (react-dom.development.js:3259)
    at runEventsInBatch (react-dom.development.js:3304)
    at runExtractedPluginEventsInBatch (react-dom.development.js:3514)
    at handleTopLevel (react-dom.development.js:3558)
    at batchedEventUpdates$1 (react-dom.development.js:21871)
    at batchedEventUpdates (react-dom.development.js:795)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3568)
    at attemptToDispatchEvent (react-dom.development.js:4267)
    at dispatchEvent (react-dom.development.js:4189)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at discreteUpdates$1 (react-dom.development.js:21887)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
```

## Steps to Reproduce (for bugs)
1. Go the `/system/pipelines/new`
2. Fill out the form
3. click on `Save`
4. Check out the console

Refs: https://github.com/Graylog2/graylog2-server/pull/11092

## Your Environment
* Graylog Version: 4.2-dev (d2d2dbb5a2637f590809489270e53473dcc72041)

### PR DESCRIPTION
**Pull request by kmerz**
## Motivation
Prior to this change, the creation of pipelines was broken
since we did not check if a stage actually exists.

## Description
This change will check if a stage exists and otherwise will
fallback to 'all'.

Fixes #11141

## How Has This Been Tested?
- Created a new pipeline
- Edited the newly created pipeline

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: graylog2-web-interface/src/logic/pipelines/SourceGenerator.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ const SourceGenerator = {
     let source = `pipeline "${pipeline.title}"\n`;
 
     pipeline.stages.forEach((stage) => {
-      source += `stage ${stage.stage} match ${stage.match.toLowerCase()}\n`;
+      source += `stage ${stage.stage} match ${stage.match?.toLowerCase() || 'all'}\n`;
```
Comment (bernd) [inline graylog2-web-interface/src/logic/pipelines/SourceGenerator.js:22]: The previous default was `either` so I think we should use that instead of `all`:

```suggestion
      source += `stage ${stage.stage} match ${stage.match?.toLowerCase() || 'either'}\n`;
```

**Review by bernd — CHANGES_REQUESTED** [review]
Thank you for the fix! One small comment:

**Review by bernd — APPROVED** [review]
