### PR TITLE
Fix extractor and static fields creation in multi-node setups

### LINKED ISSUE #2580: Extractor creation cannot load input in multi-node setup
### Problem description

When creating an extractor for a non-global input in a multi node setup, the extractor creation will fail if the input is not running on the node the web interface is being served from.

The REST resource checks its local input states for a running input, which it does not have and then fails the request.

### Steps to reproduce the problem

1. Start at least two nodes (A and B)
2. Use the web interface from node A
3. Create an input on a node B
4. Send a message, search and create an extractor for a field
5. Configure arbitrary extractor
6. Save that extractor
7. Server returns 404 "no such input"

### Environment

* Graylog Version: 2.1.0-beta.2 SNAPSHOT
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: n/a

### PR DESCRIPTION
**Pull request by bernd**
The extractor and static fields resource was using the local input
registry to check if an input exists. This breaks in a multi-node setup
where the web interface runs on node A and the input on node B.

Fixes #2580

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java [hunk 1]
```diff
@@ -120,14 +116,7 @@ public Response create(@ApiParam(name = "inputId", required = true)
...
 
-        final MessageInput input = inputs.getRunningInput(inputId);
-        if (input == null) {
-            final String msg = "Input <" + inputId + "> not found.";
-            LOG.error(msg);
-            throw new javax.ws.rs.NotFoundException(msg);
-        }
-
-        final Input mongoInput = inputService.find(input.getPersistId());
+        final Input mongoInput = inputService.find(inputId);
```
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java]: I think we should test for `null` here. If we don't it's probably harmless, but the error wouldn't be nice.

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java [hunk 2]
```diff
@@ -173,13 +162,7 @@ public ExtractorSummary update(@ApiParam(name = "inputId", required = true)
...
         checkPermission(RestPermissions.INPUTS_EDIT, inputId);
 
-        final MessageInput input = persistedInputs.get(inputId);
-        if (input == null) {
-            LOG.error("Input <{}> not found.", inputId);
-            throw new javax.ws.rs.NotFoundException("Couldn't find input " + inputId);
-        }
-
-        final Input mongoInput = inputService.find(input.getPersistId());
+        final Input mongoInput = inputService.find(inputId);
```
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java]: Same `null` check here

**Comment by kroepke** [comment]
other than the `null` check comments, lgtm 👍

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java (hunk 1 above)
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java]: `InputService#find()` throws a `NotFoundException` when the input cannot be found.

See: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java#L148

File: graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java (hunk 2 above)
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java]: See above

**Comment by joschi** [comment]
LGTM. 👍
