### PR TITLE
AWS Kinesis/Cloudwatch input: Fix several issues

### LINKED ISSUE #22137: Kinesis/CloudWatch input setup error panel text readability in dark mode
## Expected Behavior

All text should be easy to read in dark mode.

## Current Behavior

The "more info" link in the Kinesis/CloudWatch input setup error panel is black on a dark red, which is a bit difficult to read.

I also noticed #21181 again.

Image

## Steps to Reproduce (for bugs)

1. Be on `6.1.8` with dark mode
2. Trigger an error when setting up a Kinesis/CloudWatch input
3. Note the difficult to read text

## Your Environment

* Graylog Version: `6.1.8`
* Browser version: Firefox `134`

### PR DESCRIPTION
**Pull request by Nithin-Kasam**
## Description

-> Fixed multiple issues in AWS cloud watch input.

## Motivation and Context

-> User will be able to create input even stream is empty.
-> Adds additional data to message fields.
-> Provides support for the sure to override source field.
-> Error info visibility is enhanced in Dark Mode.

Closes #22137 #22140 #22138 #22085

## How Has This Been Tested?

-> Created input and checked the additional message fields in dashboard.
-> Verified override source value in the message, if user provided in configuration then the value is used , otherwise  source value is taken from message payload JSON with key "owner".
-> MORE INFO color is updated based on theme.
-> Added additional test cases and modified existing test cases accordingly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by danotorrey** [comment]
@Nithin-Kasam Thanks for the PR. Sorry for the review delay. Since you are out of office for a few weeks, we will take care of reviewing and merging this.

**Comment by coffee-squirrel** [comment]
Just a couple thoughts:
* Perhaps determining the Kinesis data stream ARN could be done as part of input initialization/startup (or otherwise "done once"), rather than every time a chunk of messages gets processed.  The ARN should never change unless an admin does something _very_ unusual (e.g. changing the account associated with dynamically-retrieved AWS credentials)-- which I'm guessing KCL wouldn't like.
* I suspect `getStreamArn()` might not work as expected if an assumed IAM role (as specified in the Graylog input config) is needed.

**Comment by danotorrey** [comment]
Thanks for the feedback @coffee-squirrel. Sorry for the delay. Similar to your comment [here](https://github.com/Graylog2/graylog2-server/issues/22085#issuecomment-2789532781), would it work to just extract the `owner` and `logStream` fields from the CloudWatch Kinesis payload and save those with each message? Do those both contain the needed info? This seems like the most straight-forward option.

**Comment by danotorrey** [comment]
@coffee-squirrel Thanks a lot for the details and context. That info is really helpful. That all makes sense to me. Since we have those metadata fields already in the CloudWatch logs Kinesis payload, those should be carried along to the final message. 

Question: For the owner and stream ARN, are the values in the CloudWatch payload sufficient? I just wanted to confirm that those actually do have the full values you are needing.

**Comment by coffee-squirrel** [comment]
@danotorrey The `owner` value certainly is.  My plan is to use a lookup table to translate the AWS account numbers (i.e. `owner` values) to our internal account names, and likely use those values to enrich the `source` field values; we don't expect Graylog to be able to accomplish that directly, though.

Determining the full Kinesis data stream ARN (different than the CW Logs stream name in `aws_log_stream` and something this PR takes an initial attempt at), is something that'd need to be done in Graylog, as it's not part of the message.  Although there's extra effort involved, we think it's worthwhile to have the Kinesis data stream ARN vs name since (similar to `gl2_remote_ip`) it provides useful information about the immediate hop preceding the Graylog input.

Thanks for the help with this!

**Comment by danotorrey** [comment]
@coffee-squirrel Thanks for the info. I've talked this over with the team, and here's what we are planning to implement. Please let me know if you see any issues with this:

- Store all fields in the CloudWatch Kinesis metadata on the messages emitted from the input (including the important `owner` field). 
- Automatically look-up the Stream ARN in the flow of the input setup wizard. This will only be done if sufficient permissions are present (`kinesis:DescribeStream`). If not, the setup wizard will still allow the input to be created without the lookup. The stream ARN will then be displayed on the final confirmation page, and stored in the input configuration (and added as a field on emitted messages). For backwards-compatibility, the config field could be filled manually filled by editing the input. Thanks for the suggestion above on this approach.

**Comment by coffee-squirrel** [comment]
@danotorrey That all sounds great, thanks!  Having the Kinesis data stream ARN as part of the Input configuration certainly makes sense; it seems like a good idea for a pull-based Input to be very specific about its source, and not potentially change based upon external factors (e.g. config file-sourced AWS creds).

File: graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.tsx [hunk 1]
```diff
@@ -189,6 +239,10 @@ const StepReview = ({ onSubmit, onEditClick, externalInputSubmit = false }: Step
             <strong>Stream</strong>
             <span>{awsCloudWatchKinesisStream.value}</span>
           </li>
+          <li>
+            <strong>Stream ARN</strong>
+            <span>{awsCloudwatchKinesisStreamArn}</span>
```
Comment (danotorrey) [inline graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.tsx:244]: @Nithin-Kasam Can you please add an info/highlighted fallback for this value that tells the user which specific permission is needed (`kinesis:DescribeStream`) if the stream ARN could not be fetched? The idea would be to help provide some guidance the user that they will need to adjust permissions to fetch the value if desired. I'll make sure to update the public docs with this too.

File: changelog/unreleased/issue-22085.toml [hunk 2]
```diff
@@ -0,0 +1,4 @@
+type = "f"
+message = "Add missing data fileds to the messages."
```
Comment (danotorrey) [inline changelog/unreleased/issue-22085.toml:2]:
```suggestion
message = "Add additional data fields for the Kinesis/Cloudwatch input."
```

File: changelog/unreleased/issue-22137.toml [hunk 3]
```diff
@@ -0,0 +1,4 @@
+type = "f"
+message = "Fixes the error panel text readability in dark mode."
```
Comment (danotorrey) [inline changelog/unreleased/issue-22137.toml:2]:
```suggestion
message = "Improve error handling for the Kinesis/Cloudwatch input."
```

File: changelog/unreleased/issue-22138.toml [hunk 4]
```diff
@@ -0,0 +1,4 @@
+type = "f"
+message = "Fixes the user to create input even if stream does not contain any messages."
```
Comment (danotorrey) [inline changelog/unreleased/issue-22138.toml:2]:
```suggestion
message = "Allow the Kinesis/Cloudwatch input to be created for empty Kinesis streams."
```

File: changelog/unreleased/issue-22140.toml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+type = "f"
+message = "Added additional configuration field which supports overriding source."
```
Comment (danotorrey) [inline changelog/unreleased/issue-22140.toml:2]:
```suggestion
message = "Allow the source field to be overridden for the Kinesis/Cloudwatch input."
```

File: graylog2-server/src/main/java/org/graylog/integrations/aws/service/KinesisService.java [hunk 6]
```diff
@@ -534,4 +543,27 @@ private static String getRolePermissionsArn(IamClient iamClient, String roleName
...
         return iamClient.getRole(r -> r.roleName(roleName)).role().arn();
     }
+
+    public static String getStreamArn(String streamName, String regionName) {
+
+         /* For testing purpose,In order to prevent calling original
+             AWS SDK methods this condition is used.*/
+        if (streamName.isEmpty()) {
+            return "arn:aws:kinesis:" + regionName + ":000000000000:stream/";
+        }
```
Comment (danotorrey) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/service/KinesisService.java:553]: Can this be avoided with test mocks or other adjustments?

**Review by danotorrey — CHANGES_REQUESTED** [review]

File: graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.tsx (hunk 1 above)
Comment (Nithin-Kasam) [reply graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.tsx:244]: Screenshot 2025-05-29 at 3 05 21 PM
Is this fine?

File: graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java [hunk 7]
```diff
@@ -31,9 +31,15 @@
 import javax.annotation.Nonnull;
 import java.util.Optional;
 
+import static org.graylog.integrations.aws.transports.KinesisTransport.CK_KINESIS_STREAM_ARN;
+
 public class KinesisRawLogCodec extends AbstractKinesisCodec {
     public static final String NAME = "CloudWatchRawLog";
-    static final String SOURCE = "aws-kinesis-raw-logs";
+    public static final String SUBSCRIPTION_FILTERS = "subscription_filters";
+    public static final String STREAM_ARN = "stream_arn";
```
Comment (coffee-squirrel) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java:39]: Suggestion: `aws_kinesis_stream_arn`

https://github.com/Graylog2/graylog2-server/blob/6.2.2/graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/AbstractKinesisCodec.java#L38-L41

File: graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java [hunk 8]
```diff
@@ -31,9 +31,15 @@
 import javax.annotation.Nonnull;
 import java.util.Optional;
 
+import static org.graylog.integrations.aws.transports.KinesisTransport.CK_KINESIS_STREAM_ARN;
+
 public class KinesisRawLogCodec extends AbstractKinesisCodec {
     public static final String NAME = "CloudWatchRawLog";
-    static final String SOURCE = "aws-kinesis-raw-logs";
+    public static final String SUBSCRIPTION_FILTERS = "subscription_filters";
```
Comment (coffee-squirrel) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java:38]: Suggestion: `aws_subscription_filters`

https://github.com/Graylog2/graylog2-server/blob/6.2.2/graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/AbstractKinesisCodec.java#L38-L41

File: graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java [hunk 9]
```diff
@@ -190,7 +194,29 @@ public ConfigurationRequest combinedRequestedConfiguration() {
...
             return request;
         }
     }
+
+    public static TextField getOverrideSourceFieldDefinition() {
+        return new TextField(
+                CK_OVERRIDE_SOURCE,
+                "Override Source",
+                "",
+                "The source is set to the Kinesis message by default. Set this if you want to override it with a custom value.",
```
Comment (coffee-squirrel) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java:208]: Suggestion: `"The source is set to '%s' by default. Set this if you want to override it with a custom value.".formatted(KinesisRawLogCodec.SOURCE)`

File: graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java [hunk 10]
```diff
@@ -190,7 +194,29 @@ public ConfigurationRequest combinedRequestedConfiguration() {
...
+                ConfigurationField.Optional.OPTIONAL);
+    }
+
+    public static TextField getKinesisStreamARNDefinition() {
+        return new TextField(
+                KinesisTransport.CK_KINESIS_STREAM_ARN,
+                "Kinesis Stream Arn",
```
Comment (coffee-squirrel) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java:215]: ARN

File: graylog2-web-interface/src/integrations/aws/cloudwatch/FormAdvancedOptions.tsx [hunk 11]
```diff
@@ -54,6 +54,15 @@ const FormAdvancedOptions = ({ onChange }: FormAdvancedOptionsProps) => {
         help='Add field with the Flow Log prefix e. g. "src_addr" -> "flow_log_src_addr".'
       />
 
+      <Input
+        id="overrideSource"
+        type="text"
+        value={overrideSource?.value}
+        onChange={onChange}
+        label="Override Source (optional)"
+        help="The source is set to the Kinesis message by default. Set this if you want to override it with a custom value."
```
Comment (coffee-squirrel) [inline graylog2-web-interface/src/integrations/aws/cloudwatch/FormAdvancedOptions.tsx:63]: Similar to the comment on `graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java`, `"aws-kinesis-raw-logs"` is the current default value.

**Review by coffee-squirrel — COMMENTED** [review]
Apologies for stepping in with PR feedback, but figured it'd be better than after a merge...

File: graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java [hunk 12]
```diff
@@ -46,14 +52,19 @@ public KinesisRawLogCodec(@Assisted Configuration configuration, ObjectMapper ob
...
                     logEvent.message(),
                     source,
                     logEvent.timestamp()
             );
+            result.addField(FIELD_OWNER, logEvent.owner());
             result.addField(FIELD_KINESIS_STREAM, logEvent.kinesisStream());
             result.addField(FIELD_LOG_GROUP, logEvent.logGroup());
             result.addField(FIELD_LOG_STREAM, logEvent.logStream());
+            result.addField(FIELD_MESSAGE_TYPE, logEvent.messageType());
+            result.addField(SUBSCRIPTION_FILTERS, logEvent.subscriptionFilters());
```
Comment (coffee-squirrel) [inline graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/KinesisRawLogCodec.java:66]: Suggestion: `aws_subscription_filters`

https://github.com/Graylog2/graylog2-server/blob/6.2.2/graylog2-server/src/main/java/org/graylog/integrations/aws/codecs/AbstractKinesisCodec.java#L38-L41

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks like a few failing `KinesisServiceTest` cases need to be updated but otherwise looks good to me!

File: graylog2-web-interface/src/integrations/aws/common/FormWrap.tsx [hunk 13]
```diff
@@ -46,10 +61,10 @@ const ErrorOutput = styled.span`
   display: block;
 `;
 
-const ErrorToggleInfo = styled.button`
+const ErrorToggleInfo = styled.button<{ isDarkMode: boolean }>`
   border: 0;
   background: none;
-  color: #1f1f1f;
+  color:${({ isDarkMode }) => (isDarkMode ? 'white' : 'black')};
```
Comment (linuspahl) [inline graylog2-web-interface/src/integrations/aws/common/FormWrap.tsx:67]: @danotorrey @kingzacko1 @ryan-carroll-graylog Just some feedback for future changes.

1. In styled components we do not check if the dark mode is active, to display a different color. We point to a specific color in the theme, like `theme.colors.text.primary` and the theme will provide different colors depending on the selected theme mode (dark / light).
2. We avoid hard coded colors and only point to the theme, to be able to customize the colors easily.
3. When you define a variable, like `isDarkMode`, for a styled component it should be prefixed with a `$`, otherwise this will create an attribute for the DOM node. https://styled-components.com/docs/api#transient-props
