### PR TITLE
Propagate exceptions in message exports

### LINKED ISSUE #11662: /api/views/search/messages returns 200 even if Graylog is logging a lexical error
Take following query for a custom mapping type:ip field to /api/views/message
```
{
  "query_string": {
    "type": "elasticsearch",
    "query_string": "test_client_ip:(192.168.178.0/24)"
  },
  "timerange": {
    "type": "relative",
    "range": 86400
  },
  "chunk_size": "500",
  "streams": [
    "5f218679a45add539817c246",
    "5f218612a45add539817c1cc"
  ],
  "limit": "500",
  "fields_in_order": [
    "client_ip",
"url"
  ]
}
```

## Expected Behavior
API should return http code 422 or 400 with providing a useful hint.

## Current Behavior
Response is 200 and no content. Checking the logs, you will see a big stack trace coming from elasticsearch
```
Caused by: org.graylog2.indexer.ElasticsearchException: ElasticsearchException[Failed to execute Search After request]; nested: ElasticsearchException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: ElasticsearchException[Elasticsearch exception [type=tok
en_mgr_error, reason=token_mgr_error: Lexical error at line 1, column 31.  Encountered: <EOF> after : "/24"]];
```

## Possible Solution
Catch Exception during API call and return a proper, human-readable error message as an API error

## Steps to Reproduce (for bugs)
Feed the API with broken/invalid syntax search string

## Context
Trying to make use of slashes in REST query

Just for the note, correct syntax needs to include two backslashes, one for espacing the backslash which will esacpe the slash:
`  "query_string": {
    "type": "elasticsearch",
    "query_string": "test_client_ip:(192.168.178.0\\/24)"
  },`

## Your Environment

* Graylog Version: 4.2
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2
* Operating System: Ubuntu 20.04
* Browser version: Edge

### PR DESCRIPTION
**Pull request by todvora**
This PR solves the problem on two different levels:

## Validation of the query
With our new query validation service, we may detect invalid query even before the chunked output starts and return a proper HTTP status code and error message

## During the chunked output
There is no 100% optimal way how to propagate exceptions that happen during a chunked transfer. This PR tries at least to provide the exception message in one chunk as a text. The client should be able to detect that as an error (line with not expected column count) and interrupt evaluation of the data.

Fixes #11662.

## Screenshots (if appropriate):
Validation in action:
image

Error during the chunked output, this is how the output will look like (no proper HTTP code)
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java [hunk 1]
```diff
@@ -106,10 +115,24 @@ public MessagesResource(
...
+        final ValidationResponse validationResponse = queryValidationService.validate(validationReq.build());
+        if (validationResponse.status().equals(ValidationStatus.ERROR)) {
+            validationResponse.explanations().stream().findFirst().map(ValidationMessage::errorMessage).ifPresent(message -> {
+                throw new BadRequestException("Request validation failed: " + message);
+            });
+        }
+
         executionGuard.checkUserIsPermittedToSeeStreams(request.streams(), searchUser::canReadStream);
 
+        // TODO: add query validation service here
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java:134]: I think this `TODO` is now obsolete?

**Review by dennisoelkers — COMMENTED** [review]
Looks good so far and works! Just a tiny remark/question.

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java (hunk 1 above)
Comment (todvora) [reply graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java]: Removed, thanks!

**Review by dennisoelkers — APPROVED** [review]
