### PR TITLE
Reduce label size in MessageDetailsTitle

### LINKED ISSUE #10200: Styling issues in MessageShow
Loading a message in the Pipeline simulator looks like this for me:
2021-03-04 14 59 13 localhost 0fa234ac532e

The component in question is [`MessageShow`](https://github.com/Graylog2/graylog2-server/blob/f7f68aaadbe4833aa49a0362e02023b8f4085cf9/graylog2-web-interface/src/components/search/MessageShow.jsx).

## Steps to Reproduce (for bugs)
1. Go to `System -> Pipelines -> Simulator`
2. Fill out the form with a simple message (e.g. `{"short_message":"foo", "source":"bar", "version": "1.1"}`, and select `GELF` as codec)
3. See the original message below
4. On the right side, clicking on `More results -> Results preview`, seems to have the same issue

## Your Environment
* Graylog Version: Graylog 4.1.0-SNAPSHOT(2f5f55a5ffe0e5e29292d7601a5e4e5e0049021c)

### PR DESCRIPTION
**Pull request by edmundoa**
This change needs to be backported to 4.0/cloud-4.0.

Fixes #10200 

## Screenshots:

Screenshot 2021-03-18 at 15 25 30

### CODE REVIEW

File: graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx [hunk 1]
```diff
@@ -25,7 +25,7 @@ const Title = styled.h3(({ theme }) => css`
   }
 
   .label {
-    font-size: calc(${theme.fonts.size.small} + 50%);
+    font-size: calc(${theme.fonts.size.h3} - 40%);
```
Comment (kyleknighted) [inline graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx:28]:
```suggestion
    font-size: ${theme.fonts.size.tiny;
```

**Review by kyleknighted — CHANGES_REQUESTED** [review]

File: graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx (hunk 1 above)
Comment (kyleknighted) [reply graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx:28]: image

Comment (edmundoa) [reply graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx]: I like it 👍

**Review by kyleknighted — APPROVED** [review]
