### PR TITLE
Query parsing exception format adapted

### LINKED ISSUE #11737: Improve format of `ParseException` error messages when validating a query.
## Description

With Graylog2/graylog2-server#11534 we implemented a validation for the search bar query string. While the validation error messages are readable in most cases, but we need to improve the format for `ParseException` error messages.

Currently they look like this:
```
ParseException: Cannot parse 'action:': Encountered "<EOF>" at line 1, column 7. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ...
```

### PR DESCRIPTION
**Pull request by todvora**
This PR tries to provide more user-friendly error messages in case of query parsing exception during validation.

## Motivation and Context
Fixes  #11737

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryParsingException.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+ *
+ * You should have received a copy of the Server Side Public License
+ * along with this program. If not, see
+ * <http://www.mongodb.com/licensing/server-side-public-license>.
+ */
+package org.graylog.plugins.views.search.validation;
+
+import org.apache.lucene.queryparser.classic.ParseException;
+
+public class QueryParsingException extends Exception {
```
Comment (janheise) [inline graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryParsingException.java:21]: I can't find a reference to this class, remove it?

**Review by janheise — CHANGES_REQUESTED** [review]

**Review by janheise — APPROVED** [review]
LGTM!
