### PR TITLE
Improving search controls by adding text and dropdown, fixing reset.

### LINKED ISSUE #7162: "Empty search" button does nothing
The "Empty search" button is doing nothing for transient searches. This is confusing.

## Expected Behavior
I think it should actually reset to an empty transient search.

## Current Behavior
If no saved search is opened, the "Empty search" button actually does nothing although it's clickable.
empty-search-button

After opening a saved search it actually "unloads" the saved search and resets the screen to an empty default search. That's a useful feature, but "Empty search" to me implies modifying the saved search instead.

## Possible Solution
- Change the label (maybe to "Restore Default Search" or something, not sure)
- Implement restoring the default also for a modified transient search

## Steps to Reproduce (for bugs)
1. Navigate to "Search"
2. Enter a query
3. Click "Empty search"
4. Stare into void

* Graylog Version: 3.2.beta2
* Browser version: Firefox 72.0.1

### LINKED ISSUE #7168: Replace Search glyph controls with mixed glyphs/dropdown with text
Currently the search controls (for saving/loading/clearing/export a search) consist of a button group with icons. These are unclear, so most users have to wait for tooltips to appear. 

Instead, we should use a mixed glyph/text variant, which renders clear icons for the most common actions (saving, loading the current search, using a star/folder glyph and "save" / "load" text) and a "More" button opening a dropdown showing text items for other actions (clearing search, exporting to dashboard, ...)

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Prior to this change, the search controls consisted of icons only. This
required the user to remember their meaning or waiting for the tooltips
to appear.

This change is aiming to improve this by:

  - Adding text to the load/save buttons
  - Putting other options into a dropdown and adding text
  - Renaming "Empty search" to "Reset search"
  - Fixing the "Reset search" functionality

Fixes #7168.
Fixes #7162.

## Screenshots (if appropriate):

Screen Shot 2020-01-16 at 17 23 16

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by linuspahl** [comment]
The functionality of the reset button was broken after merging https://github.com/Graylog2/graylog2-server/pull/7177
@kmerz and I had a look at possible solutions. We found one for most use cases, but still need to have another look at some related topics:
- The `ViewLoaderContext` is needed to load a saved search. By default it loads the new view and changes the url. For all pages (excluding the `ShowViewPage`) it is enough to do a redirect, because the `ShowViewPage` will load the view.
- Using the browser navigation works, but not perfectly. E.g. clicking on the search page will create an entry in the history for `/search` and `/search?q=&rangetype=relative&relative=300`
This is also the case when loading a saved search or clicking on a stream. We should find a way to update the URL query params, without creating an entry in the browser history, while still creating an entry, when e.g. just changing the time range of the current search.

**Comment by linuspahl** [comment]
@kyleknighted The reset button is now disabled, until the query options have changed. 

Regarding the refresh, this happens only in the context of saved searches (as you mentioned also on load / create), I see the benefit of these improvements, but would like to do them in another PR.

File: graylog2-web-interface/src/views/logic/queries/Query.js [hunk 1]
```diff
@@ -32,6 +32,22 @@ export type ElasticsearchQueryString = {
 
 export const createElasticsearchQueryString = (query: string = ''): ElasticsearchQueryString => ({ type: 'elasticsearch', query_string: query });
 
+const _streamFilters = (selectedStreams: Array<string>): Array<{ type: string, id: string }> => {
+  return selectedStreams.map(stream => ({ type: 'stream', id: stream }));
+};
+
+export const filtersForQuery = (streams: ?Array<string>) => {
```
Comment (linuspahl) [inline graylog2-web-interface/src/views/logic/queries/Query.js]: I am not so sure where the best place for this helper function is. I can't use the `QueriesFilterStore`, due to a dependency cycle.
