### PR TITLE
Fix broken decorator with duplicate messages

### LINKED ISSUE #3399: Decorator broken with same message in different index sets
## Expected Behavior

Message decoration should work even when the same message with the same message ID is stored in different index sets.

## Current Behavior

The message decorator throws an exception when it encounters the same message ID twice.
```
2017-01-19T14:21:17.962Z ERROR [DecoratorProcessorImpl] Error decorating search response
java.lang.IllegalStateException: Duplicate key ResultMessageSummary{highlightRanges=null, message={gl2_source_collector=8beeb1ab-e69d-4016-8a30-92e7b36bcd22, offset=264972309, gl2_remote_ip=172.30.0.169, gl2_remote_port=50749, streams=[56b10473e4b0bcb63971300a, 5880af182c1e3e04da716daa], input_type=log, count=1, source=graylog-org-prod-02, message=172.30.0.107 - - [19/Jan/2017:14:00:43 +0000] "GET / HTTP/1.1" 200 5 "-" "ELB-HealthChecker/1.0", type=log, gl2_source_input=57ac55d02c1e3e02596bd27c, file=/var/log/nginx/localhost.access.log, torch_service=nginx, name=graylog, gl2_source_node=d301ec2b-ccf2-4240-ac8d-37f1a1773983, _id=af8042e1-de4f-11e6-9daf-06c919f0e5a9, facility=filebeat, timestamp=2017-01-19T14:00:47.360Z}, index=graylog_84, decorationStats=null}
	at java.util.stream.Collectors.lambda$throwingMerger$156(Collectors.java:133) ~[?:1.8.0_65]
	at java.util.HashMap.merge(HashMap.java:1245) ~[?:1.8.0_65]
	at java.util.stream.Collectors.lambda$toMap$214(Collectors.java:1320) ~[?:1.8.0_65]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_65]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_65]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_65]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_65]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_65]
	at org.graylog2.decorators.DecoratorProcessorImpl.decorate(DecoratorProcessorImpl.java:57) [graylog.jar:?]
	at org.graylog2.rest.resources.search.SearchResource.buildSearchResponse(SearchResource.java:184) [graylog.jar:?]
	at org.graylog2.rest.resources.search.RelativeSearchResource.searchRelative(RelativeSearchResource.java:113) [graylog.jar:?]
	at sun.reflect.GeneratedMethodAccessor289.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) [graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```
## Possible Solution

The message decorator creates a map of message keys to messages. This fails because building the map doesn't allow duplicate keys. It can be fixed by using a compound key of the index name and the message ID.

## Steps to Reproduce (for bugs)

1. Setup Graylog so that the same message will be written into two different index sets
2. Create a decorator
3. Search
4. Look at the server log and see the exception

## Your Environment

* Graylog Version: 2.2.0-beta.6

### PR DESCRIPTION
**Pull request by bernd**
Use compound key when mapping messages in the decorator.

The same message with the same ID can be stored in two different index sets so to avoid duplicate keys when mapping messages, we have to use a compound key of the index name and the message ID.

Fixes #3399

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/decorators/DecoratorProcessorImpl.java [hunk 1]
```diff
@@ -100,7 +106,7 @@ private SearchDecorationStats getSearchDecoratorStats(List<ResultMessageSummary>
 
         decoratedMessages.forEach(message -> {
             final DecorationStats decorationStats = message.decorationStats();
-            if (decoratedMessages != null) {
+            if (decorationStats != null) {
```
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/decorators/DecoratorProcessorImpl.java]: :+1:
