### PR TITLE
Stream alert panel

### LINKED ISSUE #7279: Color issue on stream rules test page
## Description

The colors of the stream rules test page notification look off:

image

image

## Steps to Reproduce (for bugs)
1. Go to the search page
2. Expand a single message
3. Click "Test against stream"
4. Choose a stream
5. Scroll down

## Your Environment

* Graylog Version: 3.2.0-beta.5-SNAPSHOT (rev 3e7cd98)

### PR DESCRIPTION
**Pull request by kyleknighted**
## Description

Updates the Stream Rule notification to use proper colors and tweak some general layout issues.

## Motivation and Context

Closes #7279 

## Screenshots (if appropriate):
image

image

image

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/components/streamrules/StreamRuleList.jsx [hunk 1]
```diff
@@ -14,36 +14,51 @@ class StreamRuleList extends React.Component {
...
+        onSubmit,
+        permissions,
+        stream,
+        streamRuleTypes,
+      } = this.props;
+
+      return streamRules.map(streamRule => (
+        <StreamRule key={streamRule.id}
+                    permissions={permissions}
+                    matchData={matchData}
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streamrules/StreamRuleList.jsx]: `matchData` is passed down, but never used.

File: graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx [hunk 2]
```diff
@@ -79,39 +94,45 @@ class StreamRulesEditor extends React.Component {
...
+    const { matchData } = this.state;
+
+    if (matchData) {
+      if (matchData.matches) {
         return (
-          <span>
-            <Icon name="check" style={{ color: 'green' }} /> This message would be routed to this stream.
-          </span>
+          <>
+            <Icon name="check" style={{ color: '#00AE42', marginRight: 3 }} /> This message would be routed to this stream!
```
[the remark this answers is not in the document]
Comment (kyleknighted) [reply graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: Was just using what was already there, i can easily convert them to SC

[the remark this answers is not in the document]
Comment (edmundoa) [reply graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: It's fine, I was wondering if there was any other reason :)

**Comment by kyleknighted** [comment]
@edmundoa this is ready for another round of reviews when you find time.

@bernd I updated the styles a bit to keep the granular pass/fail of each rule while also rendering them in a more consistent manner

**Comment by kyleknighted** [comment]
Note: not sure why the screenshots look so muddy - it's using the same colors as the rest of the app

**Comment by edmundoa** [comment]
@kyleknighted I think this needs a rebase after the last release, could you take care of that?

**Comment by kyleknighted** [comment]
@edmundoa pushed up a fix and updated screenshots in OP

File: graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx [hunk 3]
```diff
@@ -17,14 +18,35 @@ import StoreProvider from 'injection/StoreProvider';
 const StreamsStore = StoreProvider.getStore('Streams');
 const StreamRulesStore = StoreProvider.getStore('StreamRules');
 
+const StreamAlertHeader = styled.h4`
+  font-weight: bold;
+  margin: 0 0 12px;
+`;
+
+const MatchIcon = styled(Icon)(({ empty, matches }) => {
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: This will throw a console warning when `empty` or `matches` are `true`, since styled-components passes all props through: https://github.com/styled-components/styled-components/issues/1198#issuecomment-336628848

File: graylog2-web-interface/src/components/streamrules/StreamRule.jsx [hunk 4]
```diff
@@ -1,96 +1,109 @@
...
-  },
-});
+  };
+
+  const matchDataStyle = () => (matchData.rules[streamRule.id] ? 'success' : 'danger');
+  const actionItems = isPermitted(permissions, [`streams:edit:${stream.id}`]) ? _formatActionItems() : null;
+  const description = streamRule.description ? <small>{' '}({streamRule.description})</small> : null;
+
+  return (
+    <ListGroupItem bsStyle={!isEmpty(matchData) && matchDataStyle()}>
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streamrules/StreamRule.jsx]: This throws a warning because the value of `bsStyle` can be a boolean and it is not the right prop type. We should replace `&&` with a conditional operator.

File: graylog2-web-interface/src/components/streams/StreamMetaData.jsx [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+        </>
+      )}
+    </div>
+  );
+};
+
+StreamMetaData.propTypes = {
+  isDefaultStream: PropTypes.bool,
+  stream: PropTypes.shape({
+    id: PropTypes.number,
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streams/StreamMetaData.jsx]: Stream IDs should be strings instead of numbers.
```suggestion
    id: PropTypes.string,
```

File: graylog2-web-interface/src/components/streams/StreamMetaData.jsx [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+  };
+
+  return (
+    <div className="stream-metadata">
+      <StreamThroughput streamId={stream.id} />. {_formatNumberOfStreamRules()}
+
+      {!isDefaultStream && (
+        <>
+          <span className="stream-rules-link">
+            <Button bsStyle="link"
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streams/StreamMetaData.jsx]: Small thing: using an actual button here makes sense, but breaks the link alignment with text, since the browser will render it differently as a regular anchor:

Screenshot 2020-01-30 at 11 44 54

File: graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx (hunk 3 above)
Comment (kyleknighted) [reply graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: Good catch!

File: graylog2-web-interface/src/components/streams/StreamMetaData.jsx (hunk 6 above)
Comment (kyleknighted) [reply graylog2-web-interface/src/components/streams/StreamMetaData.jsx]: image

File: graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx [hunk 7]
```diff
@@ -79,83 +107,87 @@ class StreamRulesEditor extends React.Component {
...
 
-            <h2>
-              2. Manage stream rules
-            </h2>
+            <h2>2. Manage stream rules</h2>
 
-            {this._explainMatchResult()}
+            <MatchingTypeSwitcher stream={stream} onChange={this.loadData} />
+            <Panel bsStyle={styles}>
+              <StreamAlertHeader>{this._explainMatchResult()}</StreamAlertHeader>
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: It looks like when trying to load the "Manage rules" page there's an error:

```
Objects are not valid as a React child (found: object with keys {$$typeof, render, displayName, attrs, componentStyle, foldedComponentIds, styledComponentId, target, withComponent, warnTooManyClasses, toString}). If you meant to render a collection of children, use an array instead.
    in templateFunction (created by StreamRulesEditor)
    in h4 (created by Context.Consumer)
    in StyledComponent (created by StreamRulesEditor__StreamAlertHeader)
    in StreamRulesEditor__StreamAlertHeader (created by StreamRulesEditor)
    in div (created by Panel)
    in div (created by Panel)
    in Panel (created by Context.Consumer)
    in StyledComponent (created by Panel__StyledPanel)
    in Panel__StyledPanel (created by StreamRulesEditor)
    in div (created by Col)
    in Col (created by StreamRulesEditor)
    in div (created by Row)
    in Row (created by StreamRulesEditor)
    in StreamRulesEditor (created by StreamEditPage)
```

File: graylog2-web-interface/src/components/streams/StreamMetaData.jsx [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+
+      {!isDefaultStream && (
+        <>
+          <Button bsStyle="link"
+                  bsSize="xsmall"
+                  onClick={_onHandleToggle}>
+            {toggleText} stream rules
+          </Button>
+
+          <CollapsibleStreamRuleList key={`streamRules-${stream.id}`}
```
Comment (edmundoa) [inline graylog2-web-interface/src/components/streams/StreamMetaData.jsx]: With the last changes this doesn't look right:
Screenshot 2020-02-03 at 11 26 18

Comment (kyleknighted) [reply graylog2-web-interface/src/components/streams/StreamMetaData.jsx]: image

File: graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx (hunk 7 above)
Comment (kyleknighted) [reply graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx]: Bad parenthesis wrap in a styled-component 😩
