### PR TITLE
Provide necessary contexts for single message details page.

### LINKED ISSUE #11349: Displaying a single message triggers a frontend error
clicking on a single message in the search results in:

```
Cannot read properties of undefined (reading 'width')


Stack Trace:

TypeError: Cannot read properties of undefined (reading 'width')
    at MessageAugmentations (http://localhost:8080/app.js:58954:35)
    at renderWithHooks (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:14803:18)
    at mountIndeterminateComponent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:17482:13)
    at beginWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:18596:16)
    at HTMLUnknownElement.callCallback (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
```

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Prior to this change, the page showing a single message's details was
missing two contexts which were previously set up by the `MessageList`
component/the views pages. Missing those resulted in an exception being
thrown by the watchlist message augmentation relying on these.

This change is now adding these back. It is also doing some slight
refactoring of the `ShowMessagePage` component by extracting two hooks
for brevity.

Fixes #11349.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/pages/ShowMessagePage.tsx [hunk 1]
```diff
@@ -69,35 +83,61 @@ const ShowMessagePage = ({ params: { index, messageId } }: Props) => {
...
-            <InteractiveContext.Provider value={false}>
-              <MessageDetail fields={Immutable.List()}
-                             streams={streams}
-                             allStreams={allStreams}
-                             disableSurroundingSearch
-                             inputs={inputs}
-                             message={message} />
-            </InteractiveContext.Provider>
+            <WindowDimensionsContextProvider>
+              <FieldTypesProvider streams={messageStreams as Array<string>} timestamp={timestamp as string}>
```
Comment (linuspahl) [inline graylog2-web-interface/src/pages/ShowMessagePage.tsx:130]: What is the benefit of the type assertion here?

**Review by linuspahl — APPROVED** [review]
Looks good to me!
