### PR TITLE
Silence read timeout error

### LINKED ISSUE #25622: ReadTimeoutException error logs for Collector HTTP input
## Description

I am seeing the following logs on the Collector Ingest HTTP input from time to time.

```
2026-04-13 12:55:05,463 ERROR: org.graylog2.plugin.inputs.transports.AbstractTcpTransport - Error in Input [Collector Ingest (HTTP)/Collector Ingest (HTTP)/69d50bf088f58565d167b7ac] (channel [id: 0x72aa9a4a, L:/127.0.0.1:14401 ! R:/127.0.0.1:56044]) (cause io.netty.handler.timeout.ReadTimeoutException)
2026-04-13 12:55:06,784 ERROR: org.graylog2.plugin.inputs.transports.AbstractTcpTransport - Error in Input [Collector Ingest (HTTP)/Collector Ingest (HTTP)/69d50bf088f58565d167b7ac] (channel [id: 0x0c8bb6d1, L:/127.0.0.1:14401 ! R:/127.0.0.1:56056]) (cause io.netty.handler.timeout.ReadTimeoutException)
2026-04-13 13:11:01,436 ERROR: org.graylog2.plugin.inputs.transports.AbstractTcpTransport - Error in Input [Collector Ingest (HTTP)/Collector Ingest (HTTP)/69d50bf088f58565d167b7ac] (channel [id: 0x873b4c55, L:/127.0.0.1:14401 ! R:/127.0.0.1:56032]) (cause io.netty.handler.timeout.ReadTimeoutException)
```

The error logs showed up again after 5eb91e69d5 was merged.

Our `AbstractHttpTransport` installs a `ReadTimeoutHandler` to close idle connections after 60 seconds (by default) of no read traffic.

That timeout handler triggering is normal behavior on low traffic connections. It should not be logged as error.

Currently, the log message is silenced when the TCP keep-alive option is enabled. See:

https://github.com/Graylog2/graylog2-server/blob/70b76d13f0ddf5e2c0f19484fd2e57316c531e92/graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ExceptionLoggingChannelHandler.java#L47

This is wrong. The TCP keep-alive setting is unrelated to the `ReadTimeoutHandler`. We should just not log the `ReadTimeoutException`. (only on DEBUG or TRACE)

## Your Environment

* Graylog Version: 7.1.0-beta.2

### PR DESCRIPTION
**Pull request by thll**
Fixes #25622 by silencing error logs in HTTP inputs when idle connections are closed.

Previously, the logging behavior was depending on whether the TCP keepAlive option as enabled or disabled for the input. If it was enabled, no error was emitted, otherwise it was logged.

With this PR, we are not treating an idle read timeout as an error anymore. It is unrelated to the TCP keepAlive option.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java [hunk 1]
```diff
@@ -271,7 +271,7 @@ protected LinkedHashMap<String, Callable<? extends ChannelHandler>> getChildChan
             handlers.put("codec-aggregator", () -> new ByteBufMessageAggregationHandler(aggregator, localRegistry));
         }
         handlers.put("rawmessage-handler", () -> new RawMessageHandler(input));
-        handlers.put("exception-logger", () -> new ExceptionLoggingChannelHandler(input, LOG, this.tcpKeepalive));
+        handlers.put("exception-logger", () -> new ExceptionLoggingChannelHandler(input, LOG));
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java:274]: I guess we can remove the `exception-logger` handler here? We also add it in the `NettyTransport`. Or is this different because it's a child channel handler?

https://github.com/Graylog2/graylog2-server/blob/f35df42e165ac570b8b27de3f8eeac85e74ed610/graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/NettyTransport.java#L146

**Review by bernd — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java (hunk 1 above)
Comment (thll) [reply graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java:274]: I kept it for that reason (being a child channel handler) and assumed it was there on purpose. But I will double-check if we really need it.

Comment (thll) [reply graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java:274]: Yes, it's required. Otherwise exceptions are not reliably caught if they happen in child channel handlers. When removing it, I can trigger things like that:

```
2026-04-14 15:24:44,912 WARN : io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed with error(-54): Connection reset by peer
```

Comment (bernd) [reply graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java:274]: Thanks for checking!

**Review by bernd — APPROVED** [review]
