### PR TITLE
Fix Rule Builder definitions for regex extract and replace

### LINKED ISSUE #23016: Pipeline Rule Builder: "Extract regular expression to new field" appears twice
Pipeline Rule Builder: "Extract regular expression to new field" appears twice

Image

## Expected Behavior

Items only appear one time

## Current Behavior

"Extract regular expression to new field" appears twice

## Possible Solution

It seems this is added twice?

Image

* [once](https://github.com/Graylog2/graylog2-server/blob/59cb2420065f1e0f914f05eb4d10001ebb28d009/graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragments.java#L112)
* [twice](https://github.com/Graylog2/graylog2-server/blob/59cb2420065f1e0f914f05eb4d10001ebb28d009/graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragments.java#L145)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 6.2.4
* Java Version: Bundled
* OpenSearch Version: Data Node 6.2.4 (2.15.0)
* MongoDB Version: 7.0.20
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 137.0.7151.120 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by patrickmann**
Resolves #23016 

## Description

Update the name and description to distinguish it from the related "extract regular expression" function.
Also fixed an inconsistency in the handling of optional param replaceAll.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have requested a documentation update.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragments.java [hunk 1]
```diff
@@ -136,14 +135,14 @@ static RuleFragment createRegexReplacementExtractor() {
                                 string("field").description("Field to extract").build(),
                                 string("pattern").description("The regular expression used for extraction.").build(),
                                 string("replacement").description("The replacement used for the matching text. Please refer to the Matcher API documentation for the possible options.").build(),
-                                bool("replaceAll").description("Replace all occurences of the pattern, or only the first occurence. (default: true)").build(),
+                                bool("replaceAll").optional().description("Replace all occurrences of the pattern, or only the first occurrence. (default: true)").build(),
                                 string("newField").description("New field to copy value to").build()
                         ))
                         .returnType(String.class)
                         .description("Copy extracted regular expression of field value to a new field")
```
Comment (fpetersen-gl) [inline graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragments.java]: It would be cool to also update the description, as it still is the same for both functions:
image

Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragments.java]: Updated the description
