### PR TITLE
Fix repeating tokens reporting in query validation

### LINKED ISSUE #11712: Search Validation improvement, repeating tokens etc.
## What?
The Search Validation should handle a query like "and AND or OR and" better, the warnings are off.

image

### PR DESCRIPTION
**Pull request by todvora**
Report correctly repeated unknown fields or invalid operators

## Motivation and Context
Fixes #11712

## How Has This Been Tested?
Added one unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java [hunk 1]
```diff
@@ -34,13 +34,14 @@
 
     public LuceneQueryParser() {
         this.parser = new TermCollectingQueryParser(ParsedTerm.DEFAULT_FIELD, new StandardAnalyzer());
+        this.parser.setSplitOnWhitespace(true);
```
Comment (todvora) [inline graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java:37]: @janheise This is the most important change, otherwise the `and and and or or or` parsing failed as you noticed. Thx!

**Review by janheise — APPROVED** [review]
LGTM
