### PR TITLE
Fix setting receive buffer size for UDP-based transports (#1143)

### LINKED ISSUE #1143: UDP inputs should work with UDP packets larger than 8192 bytes
Currently, the receive buffer size of UDP transports (i. e. all UDP-based inputs) is hard-coded to 8192 bytes.

Since there is no technical reason to restrict this (at least not to anything below 65535 bytes), Graylog should rather use an [`AdaptiveReceiveBufferSizePredictor`](https://netty.io/3.9/api/org/jboss/netty/channel/AdaptiveReceiveBufferSizePredictor.html) instead of the currently used [`FixedReceiveBufferSizePredictor`](https://netty.io/3.9/api/org/jboss/netty/channel/FixedReceiveBufferSizePredictor.html) with the fixed size of 8192 bytes.

### PR DESCRIPTION
**Pull request by joschi**
This PR fixes the allocation of the receive buffer for UDP-based transports and increases the default receive buffer size for UDP-based transports to 64K.

While the receive buffer size for UDP-based transports could be configured for each transport, the effective size for the receive buffer was fixed to 8192 bytes by using a `FixedReceiveBufferSizePredictor` with a hard-coded value.

By changing the default receive buffer size for UDP-based transports to 65535 bytes and using the configured receive buffer size as value for the `FixedReceiveBufferSizePredictor`, the maximum UDP packet size that can be processed by UDP-based transports is now finally configurable.

As the practical maximum size for a UDP packet is 65507 bytes, the default of 65535 bytes for the receive buffer should be fine (at the cost of increased memory allocations).

Fixes #1143

### CODE REVIEW

**Comment by joschi** [comment]
We should probably discuss a good default receive buffer size for UDP-based transports. 65535 bytes seems a bit of overkill. I think 16384 bytes should generally be fine. People can still increase this in their transport/input configurations if they expect to receive larger messages.

If we want to stay backward-compatible, we should set the default receive buffer size to 8192 bytes.

File: graylog2-inputs/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+
+import static com.jayway.awaitility.Awaitility.await;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.Assume.assumeTrue;
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.when;
+
+public class UdpTransportTest {
+    private static final String BIND_ADDRESS = "127.0.0.1";
+    private static final int PORT = 5555;
```
Comment (joschi) [inline graylog2-inputs/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java]: This might clash with other tests and using a port of `0` (use random free port) would be nice. Unfortunately there's currently no way to get the allocated port from `NettyTransport`…

File: graylog2-inputs/src/main/java/org/graylog2/inputs/transports/UdpTransport.java [hunk 2]
```diff
@@ -77,11 +62,11 @@ private static Executor executorService(final String executorName, final String
 
     @Override
     public Bootstrap getBootstrap() {
-        final ConnectionlessBootstrap bootstrap =
-                new ConnectionlessBootstrap(new NioDatagramChannelFactory(workerExecutor));
+        final ConnectionlessBootstrap bootstrap = new ConnectionlessBootstrap(new NioDatagramChannelFactory(workerExecutor));
 
-        bootstrap.setOption("receiveBufferSizePredictorFactory", new FixedReceiveBufferSizePredictorFactory(8192));
-        bootstrap.setOption("receiveBufferSize", getRecvBufferSize());
+        final int recvBufferSize = Ints.saturatedCast(getRecvBufferSize());
```
Comment (joschi) [inline graylog2-inputs/src/main/java/org/graylog2/inputs/transports/UdpTransport.java]: Should we add a hard limit to 65535 bytes here?

File: graylog2-inputs/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java (hunk 1 above)
Comment (bernd) [inline graylog2-inputs/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java]: How about adding a method that returns the `SocketAddress` of the `Channel.getLocalAddress()` from Netty?

File: graylog2-inputs/src/main/java/org/graylog2/inputs/transports/UdpTransport.java (hunk 2 above)
Comment (bernd) [inline graylog2-inputs/src/main/java/org/graylog2/inputs/transports/UdpTransport.java]: I think that would be good. That would also deal with the problem that our previous receive buffer default for UDP was 1MB.

**Comment by bernd** [comment]
I agree with the default buffer of 16384.

> If we want to stay backward-compatible, we should set the default receive buffer size to 8192 bytes.

Can you think of any problems with choosing a bigger default here? (regarding backwards compatibility)

**Comment by joschi** [comment]
> Can you think of any problems with choosing a bigger default here? (regarding backwards compatibility)

A larger default will increase the memory consumption of UDP-based transports. If people get lots of messages via those transports, Graylog will suddenly require more memory (or tell the operating system to allocate more memory for receiving UDP packets). This might hit users who are operating at the upper capacity limit of their systems.
