### PR TITLE
Normalize timestamps in ingested messages to current time if in the future 

### LINKED ISSUE #21408: Normalize timestamps in ingested messages to current time if in the future
## Expected Behavior

When ingesting messages, a timestamp that is obviously in the future (maybe with a grace period) should be normalized to the current time of the Graylog node.

## Current Behavior

Currently, the timestamp of a messages will be taken as is, if it can be parsed. It is generally fine to trust the client, but it is also very easy to misconfigure (e.g. when using timestamps with a wrong resolution). Also, accidentally ingesting messages with timestamps far in the future will lead to the index range of the index this message ends up in to have an end date that leads to inclusion in far more search queries than necessary - potentially all "last five minute" searches until the end date is reached.

If we worry about backward compatibility/breaking weird setups, we could introduce a config setting to disable this.

## Possible Solution

We should - either by default or configurable - normalize the timestamp of a message ingested to the current time, if the timestamp of the message is `> now + grace`.

## Steps to Reproduce (for bugs)

1. Ingest message with future timestamp
2. Rotate indices of index set this message ended up in
3. Check index range of index
4. Check that index will be included in `now - 5m` queries as well

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by patrickmann**
Resolves #21408 

## Description

At ingest we check if a timestamp is in the future, allowing for a grace period of `timestamp_grace_period`. If it is, we overwrite with the raw receive time (if viable) or the current time. The original timestamp is preserved in `gl2_original_timestamp` and available for searches / dashboards.

Note that normalizing is off by default; it is only on by default in new installations (with 2 day grace period).

## Motivation and Context

Future timestamps are generally erroneous and cause much user confusion.
Additionally, this can cause problems with the proper management of data tiering.

## How Has This Been Tested?

Send a message with timestamp far in the future. E.g. for GELF HTTP:
> curl -v -k http://127.0.0.1:12201/gelf -p0 -d '{"short_message":"testing", "host":"myhost.graylog.local", "facility":"test", "timestamp":2737650328}'

Observe that the message timestamp is forced to the receive time.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/Configuration.java [hunk 1]
```diff
@@ -276,6 +276,14 @@ public class Configuration extends CaConfiguration implements CommonNodeConfigur
     @Parameter(value = INSTALL_OUTPUT_BUFFER_DRAINING_MAX_RETRIES, validators = PositiveIntegerValidator.class)
     private int installOutputBufferDrainingMaxRetries = DEFAULT_INSTALL_RETRIES;
 
+
+    @Parameter(value = "timestamp_grace_period", validators = PositiveDurationValidator.class)
```
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/Configuration.java:280]: I would greatly prefer this to be a cluster config value that can be edited at runtime instead of requiring a server restart.

In addition to the restarts, if this is configured per server, it can also become inconsistent across a cluster, which is really difficult to debug.

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java [hunk 2]
```diff
@@ -171,6 +173,7 @@ private void handleMessage(@Nonnull Message msg) {
 
             message.getStreams().forEach(s -> streamMetrics.markIncomingMeter(s.getId()));
             message.ensureValidTimestamp();
+            message.normalizeTimestamp(configuration.getTimestampGracePeriod());
```
Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java:176]: When the value is coming from the cluster config, we need to make sure we do not load it on every message.
Instead we need to ensure that we listen to changes and cache the value, as this is a very hot code path.

Comment (kroepke) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java:176]: `ensureValidTimestamp` contains similar code, can we unify the handling of the checks somehow to not add unnecessary overhead in a hot code path?

File: graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+import org.graylog2.plugin.TestMessageFactory;
+import org.graylog2.plugin.Tools;
+import org.joda.time.DateTime;
+import org.junit.jupiter.api.Test;
+
+import java.time.Duration;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+class MessageTimestampTest {
```
Comment (kroepke) [inline graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java:30]: These tests don't test the changed behavior of the ProcessBufferProcessor, I'd greatly prefer if we tested the overall change to the codebase as well as just the added method.

File: graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+    }
+
+    void normalize(Message msg, Duration gracePeriod) {
+        msg.ensureValidTimestamp();
+        msg.normalizeTimestamp(gracePeriod);
+    }
+
+    final static long fuzzyMillis = 100;
+
+    boolean fuzzyEquals(DateTime d1, DateTime d2) {
```
Comment (kroepke) [inline graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java:65]: We should never rely on timing in tests, especially when we control the entire code.
Instead please use a Clock (or something like https://github.com/Graylog2/graylog2-server/blob/f35df42e165ac570b8b27de3f8eeac85e74ed610/graylog2-server/src/main/java/org/graylog2/plugin/InstantMillisProvider.java#L25) and control the passage of time explicitly.
This makes the tests more robust and easier to reason about.

**Review by kroepke — CHANGES_REQUESTED** [review]
In addition to the inline comments, I'm not 100% convinced that forcing these messages to "now" is a good solution to the problem because it's an implicit extra processing step that users might not expect.
This is different than forcing incoming data to conform to some standard, as with this approach the user has no further recourse since it runs after all processing has been applied.

The negative effect of having indices being picked up for searches, even if they might've moved to warm tier (which motivated this change), would still be present with the proposed 30 day grace period. Ultimately this is not a technical decision, but I feel like the actual issue is with index management more than with future timestamps.
Thus I feel like this change is attempting to address the problem at the wrong end (but again, this is more of a business decisions than a technical one).

File: graylog2-server/src/main/java/org/graylog2/Configuration.java (hunk 1 above)
Comment (dennisoelkers) [reply graylog2-server/src/main/java/org/graylog2/Configuration.java:280]: 30 days also seems very long to me. I think a grace period would exist to cover jitter/issues with clock synchronization of the Graylog nodes, so I would have expected a couple of minutes/some hours, definitely not more than a day. 30 days is in the margin of an unsynchronized clock, where any grace period becomes completely arbitrary and potentially detrimental.

Comment (bernd) [reply graylog2-server/src/main/java/org/graylog2/Configuration.java:280]: Scratch my previous comment. It's not an issue because we talk about future times.

File: graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java (hunk 4 above)
Comment (patrickmann) [reply graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java]: fixed

File: graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java (hunk 3 above)
Comment (patrickmann) [reply graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java:47]: Revised to call through the `ProcessBufferProcessor` handler code path.

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java (hunk 2 above)
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java]: I kept this separate, because `ensureValidTimestamp` is called frequently via `getTimeStamp`. We only need to normalize once, not on every read operation.

File: graylog2-server/src/main/java/org/graylog2/Configuration.java (hunk 1 above)
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/Configuration.java]: Switched to a cached cluster config.
Default value is 2 days to not confuse issues with TZ offsets.

**Comment by patrickmann** [comment]
@Graylog2/architecture Could I get another review? We are looking to release this in the upcoming bug fix release.

File: graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java [hunk 5]
```diff
@@ -772,15 +772,7 @@ public void testTimestampNoConversionWithNullDate() {
     @Test
     public void testNullDateGetsReplacesWithCurrentDate() {
         final Message message = new Message("message", "source", null);
-
         assertThat(message.getTimestamp()).isInstanceOf(DateTime.class);
-
-        assertThat(message.processingErrors()).satisfies(e -> {
```
Comment (kroepke) [inline graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java:778]: Why do these tests have to go, aren't they all concerned with a missing timestamp and not the grace period handling?

File: graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java [hunk 6]
```diff
@@ -0,0 +1,132 @@
...
+import org.mockito.Mockito;
+
+import java.time.Duration;
+import java.util.HashSet;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.mockito.ArgumentMatchers.eq;
+import static org.mockito.Mockito.when;
+
+class MessageTimestampTest {
```
Comment (kroepke) [inline graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java:48]: It would be good to add a test that updates the grace period through the subscribe handler, to ensure that code path keeps working.

**Review by kroepke — CHANGES_REQUESTED** [review]

File: graylog2-server/src/main/java/org/graylog2/migrations/V202501301750_DefaultTimeStampConfig.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+    @Override
+    public ZonedDateTime createdAt() {
+        return ZonedDateTime.parse("2025-01-30T17:50:00Z");
+    }
+
+    @Override
+    public void upgrade() {
+        // Do not apply to existing installations pre-7.0.
+        if (!isFreshInstallation && IS_BEFORE_VERSION_7_0) {
```
[the remark this answers is not in the document]
Comment (tellistone) [reply graylog2-server/src/main/java/org/graylog2/migrations/V202501301750_DefaultTimeStampConfig.java:53]: Yeah, lets do this bit separately in 7.0

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+ * along with this program. If not, see
+ * <http://www.mongodb.com/licensing/server-side-public-license>.
+ */
+package org.graylog2.shared.buffers.processors;
+
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+import java.time.Duration;
+
+public record TimeStampConfig(@JsonProperty("grace_period") Duration gracePeriod) {
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java:23]: I intentionally used a generic config name in case we want to add other, related config values, consistent with e.g. `SearchesClusterConfig`. 
How about updating the field name to `timestampNormalizationThreshold`?

File: graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java (hunk 5 above)
Comment (patrickmann) [reply graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java:778]: Because we are no longer generating processing errors when the timestamp is adjusted; including null replacement.

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java [hunk 9]
```diff
@@ -53,46 +55,50 @@ public class ProcessBufferProcessor implements WorkHandler<MessageEvent> {
...
         this.failureSubmissionService = failureSubmissionService;
+        this.clusterConfigService = clusterConfigService;
 
         incomingMessages = metricRegistry.meter(name(ProcessBufferProcessor.class, "incomingMessages"));
         outgoingMessages = metricRegistry.meter(name(ProcessBufferProcessor.class, "outgoingMessages"));
         processTime = metricRegistry.timer(name(ProcessBufferProcessor.class, "processTime"));
         this.streamMetrics = streamMetrics;
         currentMessage = null;
+
+        eventBus.register(this);
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java:101]: added that

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+    public static final TimeStampConfig NONE = new TimeStampConfig(Duration.ofSeconds(0));
+    public static final TimeStampConfig DEFAULT = new TimeStampConfig(Duration.ofDays(2));
+}
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java:26]: done

File: graylog2-server/src/main/java/org/graylog2/plugin/Message.java [hunk 11]
```diff
@@ -489,6 +494,34 @@ public void ensureValidTimestamp() {
...
+     * @param gracePeriod do nothing if the timestamp is within this grace period
+     */
+    public void normalizeTimestamp(Duration gracePeriod) {
+        if (gracePeriod == null) {
+            return;
+        }
+        final DateTime timeStamp = getFieldAs(DateTime.class, FIELD_TIMESTAMP).withZone(UTC);
+        if (Tools.nowUTC().plus(gracePeriod.toMillis()).isBefore(timeStamp)) {
+            DateTime receiveTimeStamp = getReceiveTime();
+            if (receiveTimeStamp != null && Tools.nowUTC().plus(gracePeriod.toMillis()).isAfter(receiveTimeStamp)) {
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/plugin/Message.java:512]: done

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java [hunk 12]
```diff
@@ -189,6 +196,21 @@ private void handleMessage(@Nonnull Message msg) {
         }
     }
 
+    public Duration getTimeStampGracePeriod() {
+        if (cachedGracePeriod == null) {
+            cachedGracePeriod = clusterConfigService.getOrDefault(TimeStampConfig.class, TimeStampConfig.NONE).gracePeriod();
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java:201]: Good catch - fixed

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java [hunk 13]
```diff
@@ -189,6 +196,21 @@ private void handleMessage(@Nonnull Message msg) {
...
+        }
+        return cachedGracePeriod;
+    }
+
+    @Subscribe
+    @SuppressWarnings("unused")
+    public void handleGracePeriodUpdated(ClusterConfigChangedEvent event) {
+        if (TimeStampConfig.class.getCanonicalName().equals(event.type())) {
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java:209]: done

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java [hunk 14]
```diff
@@ -0,0 +1,26 @@
...
+ */
+package org.graylog2.shared.buffers.processors;
+
+import com.fasterxml.jackson.annotation.JsonProperty;
+
+import java.time.Duration;
+
+public record TimeStampConfig(@JsonProperty("grace_period") Duration gracePeriod) {
+    public static final TimeStampConfig NONE = new TimeStampConfig(Duration.ofSeconds(0));
+    public static final TimeStampConfig DEFAULT = new TimeStampConfig(Duration.ofDays(2));
```
[the remark this answers is not in the document]
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java]: The configuration UI looks a bit odd now though:
image

**Review by laura-b-g — CHANGES_REQUESTED** [review]
Code-wise the frontend looks good. 
However, I noticed a few things while testing:

Before changing anything in the system configuration, the default setting is a very weird number:
Screenshot 2025-02-13 at 18 25 15

Following tests were made with a GELF input:

- For me the grace period didn't work. I set it to 2 days, but when I sent a message with a timestamp 1 day in the future, it was still normalized.

Grace period setting:
Screenshot 2025-02-13 at 18 28 31

Message with normalized timestamp:
Screenshot 2025-02-13 at 18 29 30

Sent with following body:
Screenshot 2025-02-13 at 18 29 45

- For me the messages where still normalized after disabling this option in the system configuration

**Comment by patrickmann** [comment]
> For me the messages where still normalized after disabling this option in the system configuration

GELF timestamp format is Unix epoch. Your message had no valid timestamp, so we use the receive time.

**Review by laura-b-g — APPROVED** [review]
Tested again and all looks good now! 👍

File: graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (kroepke) [reply graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java:23]: Sounds good!

**Review by kroepke — APPROVED** [review]
looks good to me, thanks for the updates!

if you want to rename the class, I think it would be adding clarity, but it's definitely just a minor nitpick.

Thanks!

**Comment by patrickmann** [comment]
Merging as is so we don't need another round of reviews :)
