### PR TITLE
Verbose processing error when streamrule fails

### LINKED ISSUE #13499: StreamRouter timeout exception does not log the rule id
## Expected Behavior
The exception text should contain enough information for quickly identify while stream rule led to the error.

## Current Behavior
The only real information on default log levels is
> `2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null`
<details>

```
2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_342]
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:162) ~[graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.matchWithTimeOut(StreamRouterEngine.java:311) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.access$000(StreamRouterEngine.java:268) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine.match(StreamRouterEngine.java:195) [graylog.jar:?]
        at org.graylog2.streams.StreamRouter.route(StreamRouter.java:99) [graylog.jar:?]
        at org.graylog2.filters.StreamMatcherFilter.filter(StreamMatcherFilter.java:42) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:104) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:158) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:128) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:98) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:49) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
2022-09-20T07:49:09.037Z WARN  [StreamRouterEngine] Unexpected error during stream matching
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_342]
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:162) ~[graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.matchWithTimeOut(StreamRouterEngine.java:311) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine$Rule.access$000(StreamRouterEngine.java:268) [graylog.jar:?]
        at org.graylog2.streams.StreamRouterEngine.match(StreamRouterEngine.java:195) [graylog.jar:?]
        at org.graylog2.streams.StreamRouter.route(StreamRouter.java:99) [graylog.jar:?]
        at org.graylog2.filters.StreamMatcherFilter.filter(StreamMatcherFilter.java:42) [graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:104) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:158) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:128) [graylog.jar:?]
```

</details>

## Possible Solution
Add the current stream rule id and, if possible, additional information about the rule.

## Context
Regex stream rules, when they start backtracking, can lead to timeout exceptions. If you don't know which rule triggered it, it can become quite challenging finding the rule, especially if you have lots of them.

## Your Environment

* Graylog Version: 4.3

### PR DESCRIPTION
**Pull request by patrickmann**
Resolves #13499

Adds a processing error to the message when a stream rule fails to match - both for normal conditions and regex matching.

## How Has This Been Tested?
Force an exception and check processing errors stream messages for the new error message.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java [hunk 1]
```diff
@@ -329,6 +333,9 @@ public Stream call() throws Exception {
             } catch (Exception e) {
                 LOG.warn("Unexpected error during stream matching", e);
```
Comment (mpfz0r) [inline graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java:334]: since the original issue was about improving the log message,
we should log the improved `error` text here as well

File: graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java [hunk 2]
```diff
@@ -309,6 +310,9 @@ public Stream match(Message message) {
                     LOG.debug("Error matching stream rule <" + rule.getType() + "/" + rule.getValue() + ">: " + e.getMessage(), e);
                 }
                 streamMetrics.markExceptionMeter(streamId);
+                final String error = f("Error matching stream rule <%s> (%s)", streamRuleId, rule.getDescription());
```
Comment (mpfz0r) [inline graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java:313]: could we add the type and value as well? (see above debug message)
Finding the rule by ID might not be so easy in the UI. 
And also the streamId that this rule is referenced on might be useful to find it.

**Review by mpfz0r — APPROVED** [review]
