### PR TITLE
fix alertcondition tests

### LINKED ISSUE #1159: The alert condition tests are all ignored and fail
The alert condition tests for `org.graylog2.alerts.types` are all ignored using the `@Ignore` annotation. When enabling them, they fail with `java.lang.NoSuchMethodException` and other runtime errors.

### PR DESCRIPTION
**Pull request by kroepke**
- use a spy on AlertService
 - fix non-null value being returned by mocked object
 - constructors need Searches instance

fixes #1159

### CODE REVIEW

File: graylog2-server/src/test/java/org/graylog2/alerts/types/MessageCountAlertConditionTest.java [hunk 1]
```diff
@@ -22,25 +22,13 @@
...
-import static org.mockito.Mockito.any;
-import static org.mockito.Mockito.anyString;
-import static org.mockito.Mockito.mock;
-import static org.mockito.Mockito.never;
-import static org.mockito.Mockito.verify;
-import static org.mockito.Mockito.when;
-
-@Ignore
+import static org.junit.Assert.*;
+import static org.mockito.Mockito.*;
```
Comment (joschi) [inline graylog2-server/src/test/java/org/graylog2/alerts/types/MessageCountAlertConditionTest.java]: Please don't use wildcard imports (http://myshittycode.com/2013/12/30/intellij-preventing-wildcard-imports/).

**Comment by joschi** [comment]
LGTM except for the wildcard imports. :panda_face:
