### PR TITLE
prevent creation of loops with `clone_message()` calls

### LINKED ISSUE #5759: clone_message creates endless loop
In Graylog 3.0 using a rule that contains the clone_message() function creates an endless loop like described in #4722.
#5284 is related but I believe that this is a bug in the code not in the documentation.

## Expected Behavior

The debug output ist displayed once -> The rule is evaluated just once

## Current Behavior

The debug output gets repeated over and over until Graylog becomes completely unusable

## Possible Solution

It seems that clone_message() makes the cloned message immediately enter the same stream again and is therefore evaluated in an infinity loop.

## Steps to Reproduce (for bugs)

1. Create the following rule:
```
rule "clone"
when
    true
then
    debug("cloning message");
    clone_message();
end
```
2. Connect it to a stream over a pipeline
3. Then send a message to that stream or use the Simulator.

## Context

We are trying to forward a long message to a different stream, then shorten the message field to display in the same stream. Since we want the shortened field only in the original message and not in the one forwarded, we forward a cloned message.

## Your Environment

* Graylog Version: Graylog 3.0.0
* Elasticsearch Version: 6.5.4
* MongoDB Version: 4.0.4
* Operating System: OEL 6

### PR DESCRIPTION
**Pull request by moesterheld**
## Description
Functions can now retrieve the rule in which they are called from the `evaluationContext`.
The `clone_message()` function uses this to check if it was invoked more than once by the same rule for the same message.

An additional boolean parameter `preventLoops` is added to the function.
If this is set to `true`, `clone_message` will not clone a message more than once.
To provide backward compatibility, this parameter is set to `false` by default. However, if it is not explicitly set to `false`, `clone_message` will stop creating clones after the 100th clone and log an error. Existing edge cases where the same message was intentionally cloned more than 100 times therefore would have to set the parameter explicitly to `false`. 

## Motivation and Context
fixes #5759

## How Has This Been Tested?
see `MessageCreationLoopPreventionTest` for tests of the different cases.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change) -- only for hypothetical cases

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java [hunk 1]
```diff
@@ -26,26 +28,56 @@
...
+                return null;
+            }
+
+        }
 
         final Message clonedMessage = new Message(currentMessage.getMessage(), currentMessage.getSource(), currentMessage.getTimestamp());
         clonedMessage.addFields(currentMessage.getFields());
         clonedMessage.addStreams(currentMessage.getStreams());
+        clonedMessage.addField(CLONE_SOURCE, rule);
+        clonedMessage.addField(CLONE_NUMBER, ++cloneNumber);
```
Comment (bernd) [inline graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java:80]: How about using the metadata fields in `Message` instead of setting actual fields in the message?

https://github.com/Graylog2/graylog2-server/blob/ed3a4da30364e786df619a3067c1854346752791/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L1011-L1064

Otherwise, those fields would end up being indexed in OpenSearch. Or do I miss the removal of the fields somewhere?

Comment (moesterheld) [reply graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java:80]: thanks for the comment. I'll change that.

File: graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java [hunk 2]
```diff
@@ -56,7 +90,7 @@ public Message evaluate(FunctionArgs args, EvaluationContext context) {
     public FunctionDescriptor<Message> descriptor() {
         return FunctionDescriptor.<Message>builder()
                 .name(NAME)
-                .params(ImmutableList.of(messageParam))
+                .params(ImmutableList.of(loopDetectionParam, messageParam))
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java:93]:
```suggestion
                .params(ImmutableList.of(messageParam, loopDetectionParam))
```

I think we need to add the new parameter at the end. Otherwise, existing usages of the rule will break with an error like this:

```
2023-02-22 11:43:13,724 WARN : org.graylog.plugins.pipelineprocessor.processors.ConfigurationStateUpdater - Ignoring non parseable rule <clone/63f5ec78b3a3156cd887fe6c> with errors <[Expected type Boolean for argument preventLoops but found Message in call to function clone_message in line 5 pos 4]>

File: graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java [hunk 3]
```diff
@@ -33,19 +38,48 @@ public class CloneMessage extends AbstractFunction<Message> {
...
+        if (ObjectUtils.allNotNull(cloneSource, rule) && Objects.equals(cloneSource, rule)) { // message was cloned by the same rule before
+
+            if (preventLoops.orElse(false)) {
+                return null;
+            }
+
+            if (preventLoops.isEmpty() && cloneNumber >= MAX_CLONES) {
+                LOG.error("Message was cloned more than {} times by rule '{}'. Not allowing any more clones to prevent a potential endless loop. If this was intentional, please explicitly set the 'preventLoops' parameter to 'false'.",
+                        MAX_CLONES, cloneSource.name());
+                return null;
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java:71]: As we consider this an error, I think it should show up in our "Indexing and Processing Errors". I think we can achieve this with something along those lines:

```suggestion
               throw new IllegalStateException(
                        StringUtils.f("Message was cloned more than %d times by rule '%s'. Not allowing any more " +
                                        "clones to prevent a potential endless loop. If this was intentional, please " +
                                        "explicitly set the 'preventLoops' parameter to 'false'.",
                                MAX_CLONES, cloneSource.name()));
```

**Review by thll — CHANGES_REQUESTED** [review]
Looks good in general and works well, but I think we could improve the error handling a little in case we forcefully break the loop. Sorry that I didn't notice this before.

**Review by thll — APPROVED** [review]
LGTM
