### PR TITLE
Use spread object creation to copy configurations before update

### LINKED ISSUE #7760: Updating configuration does not propagate change to overview component
On the configuration page, when you save a configuration update, it is not reflected on the configurations page overview components.

## Steps to Reproduce (for bugs)

1. Goto to System / Configuration 
2. Click and update a configuration (ex. Sidecar System)
3. Save configuration
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by ousmaneo**
- create setConfigurationState and use cloneDeep to update
- Update methods to use setConfigurationState before propagateChanges

## Description

Before this change saving a configuration update on configuration page wasn't updating the overview on the same page because the different configuration were held in the same object inside the configurationStore. Resulting in the the connect function did not see change when a key of that object were updated. 
With these change we make sure to create a new object cloned from the current configuration and and set it back as configuration object after updating.

fixes #7760 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js [hunk 1]
```diff
@@ -49,7 +56,7 @@ const ConfigurationsStore = Reflux.createStore({
   list(configType) {
     const promise = fetch('GET', this._url(`/${configType}`));
     promise.then((response) => {
-      this.configuration[configType] = response;
+      this.setConfigurationState(configType, response);
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js]: I think we do not deep copying here. What we could do is creating a new object for `configuration` instead of mutating the existing one:

```suggestion
      this.configuration = { ...this.configuration, [configType]: response };
```

Comment (ousmaneo) [reply graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js]: Great ! much cleaner 👍
