### PR TITLE
Fail graciously when cannot get node metrics

### LINKED ISSUE #9315: Cannot load node metrics page under high load situations
Under certain high load situations a node may not be fast enough to return its metrics. At the moment we don't handle that case graciously, so we end up loading an error page with this message:

```
Cannot read property 'length' of undefined

Stack Trace:

TypeError: Cannot read property 'length' of undefined
    at t.render (https://<redacted>/assets/aa9d5b41-102.53c5a65f985b27d783a7.js:1:1441)
    at Wi (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:69874)
    at Pi (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:69669)
    at Ms (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:105468)
    at uc (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:96715)
    at sc (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:96640)
    at Qs (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:93670)
    at https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:45312
    at exports.unstable_runWithPriority (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:42:3988)
    at Xo (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:45021)
    at Ko (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:45257)
    at Uo (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:45192)
    at Gs (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:90455)
    at Object.enqueueSetState (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:26:48977)
    at t.y.setState (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:34:1296)
    at a.n (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:18:2700)
    at a.emit (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:133:220231)
    at f.trigger (https://<redacted>/assets/vendor.8d6aa5835c8302c41e2f.js:18:3581)
    at https://<redacted>/assets/builtins.53c5a65f985b27d783a7.js:35:262031

Component Stack:

    in ShowMetricsPage
    in n
    in div
    in t
    in div
    in t
    in t
    in AppWithoutSearchBar__StyledRow
    in div
    in t
    in div
    in t
    in AppContentGrid__Container
    ...
```
Request: `GET /api/cluster/<node_id>/metrics/namespace/org`
Response: 500 timeout error

**Note for devs** Beware that having your browser console opened while loading the metrics page in development mode may have a performance impact due to excessive logging (more than 5k warnings are logged after a couple minutes). This seems to only happen in 3.3.

## Expected Behavior
Node metrics page should load, even if loading node metrics was not possible.

## Current Behavior
Node metrics page does not load when metrics cannot be fetch.

## Steps to Reproduce (for bugs)
Since getting a node into the right situation may be tricky, I did this code change in development to get into the situation:
```
--- a/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
+++ b/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
@@ -120,6 +120,9 @@ public class ClusterNodeMetricsResource extends ProxiedResource {
                                               @ApiParam(name = "namespace", required = true)
                                               @PathParam("namespace") String namespace) throws IOException, NodeNotFoundException {
         final Response<MetricsSummaryResponse> result = getResourceForNode(nodeId).byNamespace(namespace).execute();
+        if (Math.random() > 0.25) {
+            throw new RuntimeException("YOLO");
+        }
         if (result.isSuccessful()) {
             return result.body();
         } else {
```
Once you apply that change, going into `System -> Nodes -> <Node> -> Metrics` should trigger the error in the description.

## Your Environment
* Graylog Version: 4.0.0-SNAPSHOT (d6af110dc9c5936f2ad4a4a1e76a7700f1cf60d7)

### PR DESCRIPTION
**Pull request by edmundoa**
Ensure we can load the node metrics page, also when it was not possible getting node metrics.

This was tested with the patch included in the issue description:

```
--- a/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
+++ b/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
@@ -120,6 +120,9 @@ public class ClusterNodeMetricsResource extends ProxiedResource {
                                               @ApiParam(name = "namespace", required = true)
                                               @PathParam("namespace") String namespace) throws IOException, NodeNotFoundException {
         final Response<MetricsSummaryResponse> result = getResourceForNode(nodeId).byNamespace(namespace).execute();
+        if (Math.random() > 0.25) {
+            throw new RuntimeException("YOLO");
+        }
         if (result.isSuccessful()) {
             return result.body();
         } else {
```

This also needs to be backported into 3.3.

Fixes #9315

### CODE REVIEW

**Comment by edmundoa** [comment]
Since this is an old component and this fix needs to be backported, I think it's best to ignore the linter errors. However, I can fix those if you think that would be better.

File: graylog2-web-interface/src/stores/metrics/MetricsStore.js [hunk 1]
```diff
@@ -169,6 +170,11 @@ const MetricsStore = Reflux.createStore({
 
       return fetch('GET', url).then((response) => {
         return { nodeId: nodeId, names: response.metrics };
+      }, (error) => {
+        UserNotification.error(`Fetching metrics for node [${nodeId}] failed with: ${error}.`,
+          'Could not fetch node metrics');
+        // When fetching metrics fails, keep previous available metrics around, letting user see them
+        return { nodeId: nodeId, names: this.metricsNames[nodeId], error: error };
```
Comment (dennisoelkers) [inline graylog2-web-interface/src/stores/metrics/MetricsStore.js:177]: We are returning `error` from the promise handler there. Do we want to make use of that in the error handling part of the `ShowMetricsPage` and show the error there?

**Review by dennisoelkers — COMMENTED** [review]
Looks good so far and works! Just added a question inline.

File: graylog2-web-interface/src/stores/metrics/MetricsStore.js (hunk 1 above)
Comment (edmundoa) [reply graylog2-web-interface/src/stores/metrics/MetricsStore.js:177]: I guess we could replace the toastr error notification with something less annoying, will take a quick look 👍

Comment (edmundoa) [reply graylog2-web-interface/src/stores/metrics/MetricsStore.js:174]: @dennisoelkers I reworked the UI a bit to display a text error next to the filter, instead of possibly multiple toaster notifications. I'll re-request for your review, let me know what you think :)

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
I encountered an issue when the state of the metrics page is recovering after showing the error, it is running into an exception because the theme seems to be unavailable:

```
Uncaught TypeError: Cannot read property 'variant' of undefined
    at MetricsComponent.jsx:9
    at flatten (styled-components.browser.esm.js:1058)
    at ComponentStyle.generateAndInjectStyles (styled-components.browser.esm.js:1299)
    at useInjectedStyle (styled-components.browser.esm.js:1515)
    at useStyledComponentImpl (styled-components.browser.esm.js:1543)
    at styled.div (styled-components.browser.esm.js:1610)
    at renderWithHooks (react-dom.development.js:14803)
    at updateForwardRef (react-dom.development.js:16816)
    at beginWork (react-dom.development.js:18645)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at eval (react-dom.development.js:11089)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at scheduleUpdateOnFiber (react-dom.development.js:21199)
    at Object.enqueueSetState (react-dom.development.js:12639)
    at Object.Component.setState (react.development.js:471)
    at EventEmitter.eventHandler (PublisherMethods.js:44)
    at EventEmitter.emit (index.js:137)
    at Store.trigger (PublisherMethods.js:113)
    at MetricsStore.js:186
```

File: graylog2-web-interface/src/stores/metrics/MetricsStore.js (hunk 1 above)
Comment (dennisoelkers) [reply graylog2-web-interface/src/stores/metrics/MetricsStore.js:174]: When I am going to the node metrics page with your patch applied, I end up [here]( https://github.com/Graylog2/graylog2-server/pull/9316/files#diff-7a1cae0ff3ded5ec2c3534169b8fd9650594e6a0cd1f848b272d69e4069383b8R66) (`ShowMetricsPage.jsx:66`), which does not show the error message of the error that occurred. Maybe we should centralize error handling in one of the two components (`ShowMetricsPage` vs. `MetricsComponent`) instead of doing it in both?

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
Update: The exception is happening whenever the metrics page loads, not when it recovers.

File: graylog2-web-interface/src/stores/metrics/MetricsStore.js (hunk 1 above)
Comment (edmundoa) [reply graylog2-web-interface/src/stores/metrics/MetricsStore.js:174]: I think you refer to the change in the page header for `ShowMetricsPage` (the link takes me somewhere else, somehow). I was thinking about putting the error message in the page header, but decided against it since it may take quite a bit of space and the error message will be displayed below anyway.

Right now all of the error handling is done in `MetricsComponent`, since it's the component rendering the page content and seemed cleaner that way (less imports and need to move stuff around). The only exception is the page header in `ShowMetricsPage`, and only because we indicate the number of metrics the node is reporting.

**Comment by edmundoa** [comment]
@dennisoelkers I pushed changes that I think addressed your review comments. Please let me know if you see anything else.

**Review by dennisoelkers — APPROVED** [review]
Works great now! Thanks! :tada:
