### PR TITLE
Use proper colors for pie chart outer labels

### LINKED ISSUE #9242: Colors for dark mode are too dark
## Expected Behavior

When using dark mode, the colors should still be light enough to pop a bit and enable users to read the text. 

## Current Behavior

* Text on widgets is too dark:
Screen Shot 2020-10-22 at 10 10 05 AM

* Color palate for notifications, warnings, etc. seems too gray/dark
Screen Shot 2020-10-22 at 10 48 16 AM
Screen Shot 2020-10-22 at 12 08 13 PM
CleanShot 2020-10-22 at 11 58 24@2x
CleanShot 2020-10-22 at 11 48 23@2x
CleanShot 2020-10-22 at 12 19 44@2x

## Possible Solution

In general, lightening up these colors a bit would make the notifications pop a bit better.

### LINKED ISSUE #9244: Teams / Permissions header navigation does not clearly indicate active page
2020-10-22-112221_311x126_scrot
2020-10-22-112211_278x119_scrot

Multiple buttons in the header navigation of new teams and permissions pages are not clearly indicating what page I am currently on, leading to severe confusion about where I am or what else I can do. In the beginning I even thought buttons are broken because the page would not change after a click, only to find out that I was on that page already.

## Your Environment

* Graylog Version: 4.0.0-beta.2

### PR DESCRIPTION
**Pull request by kyleknighted**
## Description

Closes #9242 

## Screenshots (if appropriate):
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx [hunk 1]
```diff
@@ -209,6 +209,10 @@ class GenericPlot extends React.Component<Props, State> {
             return chart;
           });
 
+          if (newChartData[0].type === 'pie') {
```
Comment (Gaya) [inline graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx:212]: Can we also do it inside of the `map` just above? It would make it purer and contained.

**Review by Gaya — APPROVED** [review]
