### PR TITLE
Corrected parameter description for handle_dup_keys in the pipline ru…

### LINKED ISSUE #17892: key_value function: parameter allow_dup_keys/handle_dup_keys missbehaving/wrong documentation
## Expected Behavior
I do use the key_value()-function from the ruleset to evaluate KV-pairs in messages. About the two parameters from this case the documentation from the quick lookup in Graylog states:
```
allow_dup_keys	Boolean		Whether to allow duplicate keys, defaults to true
handle_dup_keys	String		How to handle duplicate keys: 'take_first': only use first value, 'take_last': only take last value, default is to concatenate the values
```
I would expect:
* allow_dup_keys to always be true by default. If I don't set any additional parameters I would not loose information
* handle_dup_keys to be configurable to either take the first or last value, or to concatenate them all.
## Current Behavior
*  allow_dup_keys seems to be false by default, only if  handle_dup_keys  is set it changes by magic to true
*  handle_dup_keys: my input becomes the delimiter for values.

## Possible Solution
* update documentation
* allow handle_dup_keys to add the values to an array as another option (maybe feature-request?)

## Context
We are parsing messages from Check Point with layered rules. The same key appears with different values.

## Your Environment

*  Graylog Version: 5.2.2

### PR DESCRIPTION
**Pull request by kodjo-anipah**
## Description

Corrected parameter description for handle_dup_keys in the pipeline rule key_value function. If not specified, the function defaults to using the first encountered value for duplicate keys.

## Motivation and Context

resolves #17892
## How Has This Been Tested?

Locally Create a rule and add it to a pipeline: 
```
rule "Test keys_array"
when
  true
then
  let output_1 = get_field(
    field : "message"
  );
  let output_2 = to_string(
    value : output_1
  );
  let output_3 = key_value(
    value : output_2,
    ignore_empty_values : true,
    allow_dup_keys : true,
    handle_dup_keys : "array"
  );
  set_fields(
    fields : output_3
  );
end
```

send in following example message via gelf input:
````
curl -X POST -H "Content-Type: application/json" -d '{"version": "1.1", "host": "example.com", "short_message": "test=1 test=2 test2=3", "facility": "gelf-test"}' http://localhost:12201/gelf
````
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java [hunk 1]
```diff
@@ -173,49 +178,78 @@ private static class MapSplitter {
...
+            if (!allowDupeKeys) {
+                throw new IllegalArgumentException("Duplicate key " + key + " is not allowed in key_value function.");
+            }
+            switch (Strings.nullToEmpty(duplicateHandling).toLowerCase(Locale.ENGLISH)) {
+                case TAKE_FIRST:
+                    // ignore this value
+                    break;
+                case TAKE_LAST:
+                    // simply reset the entry
+                    map.put(key, entryFields.next());
```
Comment (kodjo-anipah) [inline graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java:214]:
```suggestion
                    map.put(key, processValue(entryFields.next()));
```

**Comment by moesterheld** [comment]
[Review PR `key_value`](https://trello.com/c/Rz83FfbS/1-review-maxwell-pr)

**Review by moesterheld — APPROVED** [review]
I like the new default parameter in the rule builder. Thanks for adding that.
Changes LGTM, but please change the PR description as the `array` parameter value has been removed from the pr again due to having no additional value.
