### PR TITLE
Fix DiskJournalPreflightCheck

### LINKED ISSUE #13454: Preflight Check for message_journal_max_size not working properly
Introduced in Version 4.3 according to the changelog:
>  The preflight check will also assert that the message_journal_dir is writable and has enough space to contain message_journal_max_size for the on-disk journal. Additionally, it will also apply a check to prevent the journal from using a network filesystem.

It seems that the check doesn't include the current size of the journal  into the calculation and only checks that there is the value specified in message_journal_max_size currently available. (https://github.com/Graylog2/graylog2-server/blob/4.3/graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java#L70).
Expected behavior would be: Filesystem Available + Current Journal Size > Max Journal Size

We have the following setup:
- dedicated filesystem for graylog journal with 250GB
- message_journal_max_size set to 230 GB so it can use the whole filesystem
- graylog doesn't start if journal grows over 20GB

```
$  grep -E '(message_journal_max_size|message_journal_dir)' /etc/graylog/server/server.conf
message_journal_dir = /srv/graylog/journal
message_journal_max_size = 230gb
$ df -h /srv/graylog
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        251G   66M  239G   1% /srv/graylog
$ ls -la /srv/graylog/
total 28
drwxr-xr-x 4 root    root     4096 Mär 25  2020 .
drwxr-xr-x 4 root    root     4096 Mär 25  2020 ..
drwxr-xr-x 3 graylog graylog  4096 Sep 14 13:31 journal
drwx------ 2 root    root    16384 Mär 25  2020 lost+found
```

```
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.Main.main(Main.java:45)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:292)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.ServerBootstrap.beforeInjectorCreation(ServerBootstrap.java:126)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.ServerBootstrap.runPreFlightChecks(ServerBootstrap.java:135)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.preflight.PreflightCheckService.runChecks(PreflightCheckService.java:51)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.runCheck(DiskJournalPreflightCheck.java:62)
Sep 14 09:16:22 graylog03 graylog-server[17925]:         at org.graylog2.bootstrap.preflight.DiskJournalPreflightCheck.checkJournalDirSizeAndType(DiskJournalPreflightCheck.java:71)
Sep 14 09:16:22 graylog03 graylog-server[17925]: Exception in thread "main" org.graylog2.bootstrap.preflight.PreflightCheckException: Journal directory </srv/graylog/journal> has not enough free space (193361 MB) to contain 'message_journal_max_size = 235520 MB'
```

## Expected Behavior
Graylog server should start even if the journal is almost full and there is still enough space to fill up the filesystem to the maximum size.

## Current Behavior
Graylog fails to start if there is less than message_journal_max_size available disk space.

## Possible Solution
Adjust the check to include the current size of the journal into the calculation.

## Your Environment

* Graylog Version: 4.3.6
* Java Version: openjdk version "11.0.16" 2022-07-19
* Elasticsearch Version:7.17.6
* MongoDB Version:4.2.22
* Operating System:Debian GNU/Linux 10 (buster)
* Browser version: N/A

### PR DESCRIPTION
**Pull request by mpfz0r**
Include the already used size of the journal directory into the size calcalation.

Fixes #13454

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java [hunk 1]
```diff
@@ -67,13 +68,17 @@ private void checkJournalDirSizeAndType() {
...
-                        journalMaxSize.toMegabytes()
-                ));
+            final long availableOnFS = journalFs.available();
+            if (availableOnFS > 0) {
+                final long usedByJournal = FileUtils.sizeOfDirectory(journalDirectory.toFile());
+                if (availableOnFS + usedByJournal < journalMaxSize.toBytes()) {
+                    throw new PreflightCheckException(StringUtils.f(
+                            "Journal directory <%s> has not enough free space (%d MB) to contain 'message_journal_max_size = %d MB' ",
+                            journalDirectory.toAbsolutePath(),
+                            Size.bytes(availableOnFS + usedByJournal).toMegabytes(),
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java:78]:
```suggestion
                            Size.bytes(availableOnFS).toMegabytes(),
```

**Review by thll — CHANGES_REQUESTED** [review]
Looks good and works.

But I think the log message is not quite correct anymore now.

File: graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java [hunk 2]
```diff
@@ -67,13 +68,17 @@ private void checkJournalDirSizeAndType() {
...
+                            journalMaxSize.toMegabytes()
+                    ));
```
Comment (thll) [inline graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java:80]:
```suggestion
                       throw new PreflightCheckException(StringUtils.f(
                            "Journal directory <%s> has not enough free space (only %d MB available). You need to free at least %d MB to contain 'message_journal_max_size = %d MB' ",
                            journalDirectory.toAbsolutePath(),
                            Size.bytes(availableOnFS).toMegabytes(),
                            Size.bytes(journalMaxSize.toBytes() - usedByJournal - availableOnFS).toMegabytes(),
                            journalMaxSize.toMegabytes()
                    ));
```

**Review by thll — CHANGES_REQUESTED** [review]

**Review by thll — APPROVED** [review]
