### PR TITLE
Remove quotation on string fields

### LINKED ISSUE #3155: Wrongly quoted fields in search page
As part of the work in #3106, string fields in the search page are quoted.

## Expected Behavior
Fields in search page are not quoted.

## Current Behavior
Fields in search page are quoted.

## Your Environment

* Graylog Version: 2.2.0-beta.1

### PR DESCRIPTION
**Pull request by edmundoa**
Only use `JSON.stringify()` to convert objects into strings, relying on `String()` for doing all other conversions. In this way we can properly display objects and arrays and not add any quotation on string fields.

Refs #3106, fixes #3155

### CODE REVIEW

File: graylog2-web-interface/src/components/search/MessageShow.jsx [hunk 1]
```diff
@@ -28,7 +28,8 @@ const MessageShow = React.createClass({
 
   possiblyHighlight(fieldName) {
     // No highlighting for the message details view.
-    return JSON.stringify(this.props.message.fields[fieldName]) || '';
+    const value = this.props.message.fields[fieldName];
+    return (typeof value === 'object' ? JSON.stringify(value) : String(value));
```
Comment (joschi) [inline graylog2-web-interface/src/components/search/MessageShow.jsx]: Would it make sense to extract this pattern into a common utility method?

Comment (edmundoa) [inline graylog2-web-interface/src/components/search/MessageShow.jsx]: Good point, will do that 👍
