### PR TITLE
Remove all access tokens of a user when the user is deleted

### LINKED ISSUE #4565: Leaking Access Tokens
## Expected Behavior
If a user with access tokens gets deleted, the associated access tokens should also be deleted.

## Current Behavior
Access tokens of a deleted user are still in the database, but can't be used anymore.

## Possible Solution
When deleting the user also delete the access tokens.

## Steps to Reproduce (for bugs)
1. Create a user
2. Add access tokens for this user
3. Delete the user via webinterface
4. Take a look in the mongodb for the accesstokens.

## Your Environment
* Graylog Version: pre 3.0.0
* Elasticsearch Version: 5.6.5
* MongoDB Version: 2.4.10
* Operating System: Ubuntu 16.04
* Browser version: Chrome 64

### PR DESCRIPTION
**Pull request by radykal-com**
## Description
Delete all user access tokens when deleting the user

## Motivation and Context
Fixes #4565 

## How Has This Been Tested?
1. Create a user (web interface)
2. Create multiple access tokens for the new user (web interface)
3. Delete the user (web interface)
4. Verify the user and the access tokens are deleted from the mongo db.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java [hunk 1]
```diff
@@ -118,4 +119,13 @@ public String save(AccessToken accessToken) throws ValidationException {
         collection(AccessTokenImpl.class).createIndex(new BasicDBObject(AccessTokenImpl.TOKEN, 1), new BasicDBObject("unique", true));
         return super.save(accessToken);
     }
+
+    @Override
+    public int deleteAllForUser(String username) {
+        LOG.debug("Deleting all access tokens of username \"{}\"", username);
+        final DBObject query = BasicDBObjectBuilder.start(AccessTokenImpl.USERNAME, username).get();
+        final int result = destroy(query, AccessTokenImpl.COLLECTION_NAME);
+        LOG.debug("Deleted {} access tokens", result);
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java]: Please add the user name to this debug message.

```java
LOG.debug("Deleted {} access tokens of user \"{}\"", result, username);
```

File: graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java [hunk 2]
```diff
@@ -118,4 +119,13 @@ public String save(AccessToken accessToken) throws ValidationException {
         collection(AccessTokenImpl.class).createIndex(new BasicDBObject(AccessTokenImpl.TOKEN, 1), new BasicDBObject("unique", true));
         return super.save(accessToken);
     }
+
+    @Override
+    public int deleteAllForUser(String username) {
+        LOG.debug("Deleting all access tokens of username \"{}\"", username);
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java]: Very minor nitpick, please change the log statement to:
```java
LOG.debug("Deleting all access tokens of user \"{}\"", username);
```

**Comment by radykal-com** [comment]
Fixed ;)
