### PR TITLE
Getting index statistics could contain failed shards

### LINKED ISSUE #2194: Every odd index rolled too early
### Problem description
Every second index stays unfilled to configured condition.
image
image

### Environment
* Graylog Version: 2.0 GA
* Elasticsearch Version: 2.3.1

### PR DESCRIPTION
**Pull request by kroepke**
During rotation and retention we requested all index statistics multiple times, which, in a overloaded cluster, could lead to shard failures due to timeouts.
This failure wasn't logged and could lead to using the wrong (older) index to base rotation decisions on, effectively rotating indices too early.

This change makes Graylog use a more lightweight API to determine all index names including their aliases, reducing the usage of the expensive Index Statistics to the indices page only.
The current rotation and retention strategies do not need to know all index statistics which require to touch every single shard in the cluster.

fixes #2194

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java [hunk 1]
```diff
@@ -182,29 +180,31 @@ public void cycle() {
...
 
             try {
-                indexNumbers.add(extractIndexNumber(indexName));
+                final int indexNumber = extractIndexNumber(indexName);
+                highestIndexNumber = Math.max(indexNumber, highestIndexNumber);
             } catch (NumberFormatException ex) {
-                LOG.debug("Couldn't extract index number from index name " + indexName, ex);
+                LOG.warn("Couldn't extract index number from index name " + indexName, ex);
             }
         }
```
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java]: What about replacing this with a streams call like this:

```
        final Optional<Integer> highestIndexNumber = indexNames.stream()
            .filter(indexName -> !this.isGraylogDeflectorIndex(indexName))
            .map(Deflector::extractIndexNumber)
            .max(Integer::max);
```
Makes it easier to grasp what is done (at least for me).

Comment (kroepke) [inline graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java]: In theory I agree, but in this case we'd need to refactor extractIndexNumber as well and its callers, because it throws an exception, and it already felt I changed a lot of code already :(

How about making those changes on master?

**Comment by bernd** [comment]
LGTM :+1:

File: graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java (hunk 1 above)
Comment (dennisoelkers) [inline graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java]: 👍
