### PR TITLE
Correct behavior when _cat/nodes API from the search engine returns n…

### LINKED ISSUE #12858: Null Pointer in org.graylog2.periodical.IndexerClusterCheckerThread
## Expected Behavior

No null Pointer
## Current Behavior

```
2022-06-09 10:10:51,556 ERROR: org.graylog2.periodical.IndexerClusterCheckerThread - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: Unable to retrieve nodes list
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:140) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:100) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.perform(CatApi.java:89) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.nodes(CatApi.java:51) ~[?:?]
        at org.graylog.storage.elasticsearch7.ClusterAdapterES7.nodes(ClusterAdapterES7.java:107) ~[?:?]
        at org.graylog.storage.elasticsearch7.ClusterAdapterES7.fileDescriptorStats(ClusterAdapterES7.java:100) ~[?:?]
        at org.graylog2.indexer.cluster.Cluster.getFileDescriptorStats(Cluster.java:90) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexerClusterCheckerThread.checkOpenFiles(IndexerClusterCheckerThread.java:75) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexerClusterCheckerThread.doRun(IndexerClusterCheckerThread.java:64) ~[graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.storage.elasticsearch7.cat.NodeResponse`, problem: Null diskUsed
 at [Source: (org.graylog.shaded.elasticsearch7.org.apache.http.nio.entity.ContentInputStream); line: 1, column: 1615] (through reference chain: java.util.ArrayList[8])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3078) ~[graylog.jar:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.returnType(CatApi.java:98) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.lambda$perform$4(CatApi.java:93) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:98) ~[?:?]
        ... 14 more
Caused by: java.lang.NullPointerException: Null diskUsed
        at org.graylog.storage.elasticsearch7.cat.AutoValue_NodeResponse.<init>(AutoValue_NodeResponse.java:55) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.NodeResponse.create(NodeResponse.java:58) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call(AnnotatedMethod.java:109) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014) ~[graylog.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3078) ~[graylog.jar:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.returnType(CatApi.java:98) ~[?:?]
        at org.graylog.storage.elasticsearch7.cat.CatApi.lambda$perform$4(CatApi.java:93) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:98) ~[?:?]
        ... 14 more
```
## Steps to Reproduce (for bugs)

1. unclear how it can be reproduced
2.
3.
4.

## Your Environment

* Graylog Version: 4.2.7
* Java Version: JDK 11
* Elasticsearch Version: 7.10.2
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by luk-kaminski**
…odes without disk/file statistics present.

## Description
Fixes #12858
It seems that "_cat/nodes" endpoint for ES can return nodes without populating disk/file related fields (i.e. diskUsage).
Our code assumed those fields are always present and is throwing an ugly NullPointerException in this case (please go to #12858 for full stacktrace).
This PR makes our code more tolerant to this kind of rare scenario. It excludes nodes that temporarily do not return their disk/file data from current "open file"/"disk usage" check (performed by IndexerClusterCheckerThread periodical).
It also logs basic information about those nodes.

## Motivation and Context
We do not want NullPointerException in the logs.
We do not want periodical to break because of one strange node, we want it to continue execution for other nodes in the cluster.
(We are also curious why some nodes do not have all the fields reported, maybe additional logging will give us a clue)

## How Has This Been Tested?
I have not been able to reproduce it on my local environment.
I have simulated the same scenario with unit test and verified they do not fail after the introduction of this fix.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java [hunk 1]
```diff
@@ -104,7 +104,14 @@ public Set<NodeFileDescriptorStats> fileDescriptorStats() {
     }
 
     private List<NodeResponse> nodes() {
-        return catApi.nodes();
+        final List<NodeResponse> allNodes = catApi.nodes();
+        final List<NodeResponse> nodesWithDiskStatistics = allNodes.stream().filter(NodeResponse::hasDiskStatistics).collect(Collectors.toList());
+        if (allNodes.size() != nodesWithDiskStatistics.size()) {
+            final List<NodeResponse> nodesWithMissingDiskStatistics = allNodes.stream().filter(nr -> !nr.hasDiskStatistics()).collect(Collectors.toList());
+            LOG.info("_cat/nodes API has returned " + nodesWithMissingDiskStatistics.size() + " nodes without disk statistics:");
```
Comment (todvora) [inline graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java:111]: What about a WARNING level instead of info?

**Review by todvora — COMMENTED** [review]
Thanks, good work, if you could just think about those two details, if they make sense.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java (hunk 1 above)
Comment (luk-kaminski) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java:111]: To be honest, I am not sure if this situation is normal or natural. We have one client reporting it, we do not know the details about why it is so. I am a little bit hesitant to use too high logging level, as I am not quite sure that it is smth user needs to be very concerned about...

File: graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java [hunk 2]
```diff
@@ -92,8 +92,21 @@ public Set<NodeFileDescriptorStats> fileDescriptorStats() {
                 final String host = jsonElement.path("host").asText(null);
                 final String ip = jsonElement.path("ip").asText();
                 final JsonNode fileDescriptorMax = jsonElement.path("fileDescriptorMax");
-                final Long maxFileDescriptors = fileDescriptorMax.isLong() ? fileDescriptorMax.asLong() : null;
-                setBuilder.add(NodeFileDescriptorStats.create(name, ip, host, maxFileDescriptors));
+                if (!fileDescriptorMax.isLong()) {
+                    try {
+                        //try parsing the String, it may represent a Long value
+                        setBuilder.add(NodeFileDescriptorStats.create(name, ip, host, Long.parseLong(fileDescriptorMax.asText())));
+                    } catch (Exception e) {
```
[the remark this answers is not in the document]
Comment (luk-kaminski) [reply graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java:99]: I can switch to that, I don't see that "asText()" method could throw any exceptions.

File: graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java (hunk 1 above)
Comment (todvora) [reply graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java:111]: Then let's keep it to info and adapt afterwards if needed :+1:

**Review by todvora — APPROVED** [review]
